#include <bits/stdc++.h>
using namespace std;
struct V{double x,y,z;};
static inline V operator+(V a,V b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline V operator-(V a,V b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline V operator*(V a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline V operator/(V a,double s){return {a.x/s,a.y/s,a.z/s};}
static inline double dot(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline V cross(V a,V b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(V a){return dot(a,a);} static inline double len(V a){return sqrt(max(0.0,n2(a)));}
static inline V unit(V a){double l=len(a);return l>1e-300?a/l:V{0,0,0};}
struct F{int a,b,c; bool on=true;};
struct Q{double q[10];Q(){memset(q,0,sizeof q);}void add(const Q&o){for(int i=0;i<10;i++)q[i]+=o.q[i];}
 void plane(double a,double b,double c,double d,double w){q[0]+=w*a*a;q[1]+=w*a*b;q[2]+=w*a*c;q[3]+=w*a*d;q[4]+=w*b*b;q[5]+=w*b*c;q[6]+=w*b*d;q[7]+=w*c*c;q[8]+=w*c*d;q[9]+=w*d*d;}
 double eval(V p)const{double x=p.x,y=p.y,z=p.z;return q[0]*x*x+2*q[1]*x*y+2*q[2]*x*z+2*q[3]*x+q[4]*y*y+2*q[5]*y*z+2*q[6]*y+q[7]*z*z+2*q[8]*z+q[9];}};
static inline uint64_t ek(int a,int b){if(a>b)swap(a,b);return (uint64_t)(uint32_t)a<<32|(uint32_t)b;}
static inline array<int,3> tk(int a,int b,int c){array<int,3> r{a,b,c};sort(r.begin(),r.end());return r;}
static inline bool has(const F&f,int v){return f.a==v||f.b==v||f.c==v;}
int N,M; vector<V>P0,P; vector<F>F0,Fc; double diagL=1,tau=1,tau2=1; chrono::steady_clock::time_point T0;
static inline bool timeok(){return chrono::duration<double>(chrono::steady_clock::now()-T0).count()<18.7;}
struct KD{vector<V>*p; vector<int> id; struct Node{int l,r,axis,idx;}; vector<Node> tr; KD(){} KD(vector<V>&pts){build(pts);} int rec(int l,int r,int dep){if(l>=r)return -1;int m=(l+r)/2,ax=dep%3;nth_element(id.begin()+l,id.begin()+m,id.begin()+r,[&](int a,int b){return ax==0?(*p)[a].x<(*p)[b].x:ax==1?(*p)[a].y<(*p)[b].y:(*p)[a].z<(*p)[b].z;});int cur=tr.size();tr.push_back({-1,-1,ax,id[m]});tr[cur].l=rec(l,m,dep+1);tr[cur].r=rec(m+1,r,dep+1);return cur;} void build(vector<V>&pts){p=&pts;id.resize(pts.size());iota(id.begin(),id.end(),0);tr.reserve(pts.size());rec(0,id.size(),0);} double coord(V a,int ax)const{return ax==0?a.x:ax==1?a.y:a.z;} void qry(int t,V q,double&best)const{if(t<0)return;const Node&nd=tr[t];double d=n2(q-(*p)[nd.idx]);if(d<best)best=d;double diff=coord(q,nd.axis)-coord((*p)[nd.idx],nd.axis);int first=diff<0?nd.l:nd.r,second=diff<0?nd.r:nd.l;qry(first,q,best);if(diff*diff<best)qry(second,q,best);} double nearest2(V q)const{double b=1e300;qry(0,q,b);return b;}};
static bool closedMesh(const vector<V>&Vv,const vector<F>&Fs){if(Vv.size()<4||Fs.size()<4||Vv.size()>(size_t)::N)return false;unordered_map<uint64_t,int> ec;ec.reserve(Fs.size()*3+9);set<array<int,3>> ts;double mina=max(1e-32,1e-28*diagL*diagL*diagL*diagL);for(auto f:Fs){if(f.a<0||f.b<0||f.c<0||f.a>=(int)Vv.size()||f.b>=(int)Vv.size()||f.c>=(int)Vv.size())return false;if(f.a==f.b||f.b==f.c||f.a==f.c)return false;if(n2(cross(Vv[f.b]-Vv[f.a],Vv[f.c]-Vv[f.a]))<=mina)return false;if(!ts.insert(tk(f.a,f.b,f.c)).second)return false;ec[ek(f.a,f.b)]++;ec[ek(f.b,f.c)]++;ec[ek(f.c,f.a)]++;}for(auto &kv:ec)if(kv.second!=2)return false;return true;}
static bool vertexHausdorffOK(vector<V>&A,vector<V>&B){if(B.size()>A.size())return false;KD ka(A),kb(B);double lim=tau2*0.999999;for(auto &v:B)if(ka.nearest2(v)>lim)return false;for(auto &v:A)if(kb.nearest2(v)>lim)return false;return true;}
static void orientFace(vector<V>&Vv,F&f,V cen){V cr=cross(Vv[f.b]-Vv[f.a],Vv[f.c]-Vv[f.a]);V cc=(Vv[f.a]+Vv[f.b]+Vv[f.c])/3.0;if(dot(cr,cc-cen)<0)swap(f.b,f.c);} 
static bool validateCandidate(vector<V>&Vv,vector<F>&Fs){if(!closedMesh(Vv,Fs))return false;return vertexHausdorffOK(P0,Vv);} 
static bool ellipsoidCandidate(vector<V>&OV,vector<F>&OF){if(N<900)return false;V mn=P0[0],mx=P0[0];for(auto p:P0){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);}V c=(mn+mx)/2.0;double rx=(mx.x-mn.x)/2,ry=(mx.y-mn.y)/2,rz=(mx.z-mn.z)/2,rmax=max({rx,ry,rz});if(min({rx,ry,rz})<rmax*0.08||rmax<=1e-12)return false;double rms=0,ma=0;for(auto p:P0){double s=sqrt((p.x-c.x)*(p.x-c.x)/(rx*rx)+(p.y-c.y)*(p.y-c.y)/(ry*ry)+(p.z-c.z)*(p.z-c.z)/(rz*rz));double e=fabs(s-1.0)*rmax;rms+=e*e;ma=max(ma,e);}rms=sqrt(rms/N);if(ma>tau*0.42||rms>tau*0.10)return false;double step=max(tau*0.78,1e-12);int lon=max(12,(int)ceil(2*M_PI*rmax/step));int lat=max(6,(int)ceil(M_PI*rmax/step));lon=min(lon,160);lat=min(lat,80);if(2+(lat-1)*lon>=N)return false;OV.clear();OF.clear();OV.push_back({c.x,c.y,c.z+rz});for(int i=1;i<lat;i++){double th=M_PI*i/lat,st=sin(th),ct=cos(th);for(int j=0;j<lon;j++){double ph=2*M_PI*j/lon;OV.push_back({c.x+rx*st*cos(ph),c.y+ry*st*sin(ph),c.z+rz*ct});}}int bot=OV.size();OV.push_back({c.x,c.y,c.z-rz});auto id=[&](int r,int j){return 1+(r-1)*lon+(j%lon+lon)%lon;};auto add=[&](int a,int b,int cc){F f{a,b,cc,true};orientFace(OV,f,c);OF.push_back(f);};for(int j=0;j<lon;j++)add(0,id(1,j),id(1,j+1));for(int i=1;i<lat-1;i++)for(int j=0;j<lon;j++){add(id(i,j),id(i+1,j),id(i,j+1));add(id(i,j+1),id(i+1,j),id(i+1,j+1));}for(int j=0;j<lon;j++)add(bot,id(lat-1,j+1),id(lat-1,j));return validateCandidate(OV,OF);} 
static void axisCoord(V p,int ax,double&t,double&u,double&v){if(ax==0){t=p.x;u=p.y;v=p.z;}else if(ax==1){t=p.y;u=p.x;v=p.z;}else{t=p.z;u=p.x;v=p.y;}}
static V makeAxis(int ax,double t,double u,double v){if(ax==0)return {t,u,v};if(ax==1)return {u,t,v};return {u,v,t};}
static bool torusCandidate(vector<V>&OV,vector<F>&OF){if(N<1200)return false;for(int ax=0;ax<3;ax++){double tmin=1e100,tmax=-1e100,umin=1e100,umax=-1e100,vmin=1e100,vmax=-1e100;for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);tmin=min(tmin,t);tmax=max(tmax,t);umin=min(umin,u);umax=max(umax,u);vmin=min(vmin,v);vmax=max(vmax,v);}double ct=(tmin+tmax)/2,cu=(umin+umax)/2,cv=(vmin+vmax)/2;double rmin=1e100,rmax=0;for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);double rho=hypot(u-cu,v-cv);rmin=min(rmin,rho);rmax=max(rmax,rho);}double R=(rmax+rmin)/2,r=(rmax-rmin)/2,rt=(tmax-tmin)/2;if(R<r*1.25||r<=1e-12||fabs(rt-r)>tau*0.45)continue;double rms=0,ma=0;for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);double rho=hypot(u-cu,v-cv);double e=fabs(hypot(rho-R,t-ct)-r);rms+=e*e;ma=max(ma,e);}rms=sqrt(rms/N);if(ma>tau*0.38||rms>tau*0.085)continue;int U=max(16,(int)ceil(2*M_PI*(R+r)/(tau*0.78)));int W=max(8,(int)ceil(2*M_PI*r/(tau*0.78)));U=min(U,220);W=min(W,80);if(U*W>=N)continue;OV.clear();OF.clear();OV.reserve(U*W);for(int i=0;i<U;i++){double th=2*M_PI*i/U;for(int j=0;j<W;j++){double ph=2*M_PI*j/W;double rr=R+r*cos(ph);OV.push_back(makeAxis(ax,ct+r*sin(ph),cu+rr*cos(th),cv+rr*sin(th)));}}auto id=[&](int i,int j){return ((i%U+U)%U)*W+(j%W+W)%W;};auto pred=[&](V p){double t,u,v;axisCoord(p,ax,t,u,v);double th=atan2(v-cv,u-cu);double rho=hypot(u-cu,v-cv);return makeAxis(ax,t-ct,(rho-R)*cos(th),(rho-R)*sin(th));};for(int i=0;i<U;i++)for(int j=0;j<W;j++){int a=id(i,j),b=id(i+1,j),c1=id(i+1,j+1),d=id(i,j+1);F f1{a,b,c1,true};V cen=(OV[a]+OV[b]+OV[c1])/3.0;if(dot(cross(OV[f1.b]-OV[f1.a],OV[f1.c]-OV[f1.a]),pred(cen))<0)swap(f1.b,f1.c);OF.push_back(f1);F f2{a,c1,d,true};cen=(OV[a]+OV[c1]+OV[d])/3.0;if(dot(cross(OV[f2.b]-OV[f2.a],OV[f2.c]-OV[f2.a]),pred(cen))<0)swap(f2.b,f2.c);OF.push_back(f2);}if(validateCandidate(OV,OF))return true;}return false;}
static bool gridTorusCandidate(vector<V>&OV,vector<F>&OF){if(N<600||M!=2*N)return false;vector<pair<int,int>> fac;for(int d=6;d*d<=N;d++)if(N%d==0){fac.push_back({d,N/d});fac.push_back({N/d,d});}auto same=[&](F f,int a,int b,int c){return tk(f.a,f.b,f.c)==tk(a,b,c);};for(auto [U,VN]:fac){if(U<6||VN<6)continue;int ok=0,tot=0,step=max(1,N/700);for(int q=0;q<N&&tot<700;q+=step){int i=q/VN,j=q%VN;int a=i*VN+j,b=((i+1)%U)*VN+j,c=((i+1)%U)*VN+(j+1)%VN,d=i*VN+(j+1)%VN;if(2*q+1>=M)break;if(same(F0[2*q],a,b,c)&&same(F0[2*q+1],a,c,d))ok++;tot++;}if(tot<100||ok*100<tot*96)continue;int su=1,sv=1;while(U/(su+1)>=6){bool good=true;for(int i=0;i<U;i+=su+1)for(int j=0;j<VN;j+=sv){(void)i;(void)j;}su++; if(su>U)break;}int U2=U,V2=VN;auto trySet=[&](int a,int b){U2=max(6,a);V2=max(6,b);};trySet(max(6,(int)ceil(2*M_PI/(tau/diagL+1e-12))),max(6,VN/4));U2=min(U2,U);V2=min(V2,VN);for(int pass=0;pass<8;pass++){OV.clear();OF.clear();for(int i=0;i<U2;i++){int oi=(long long)i*U/U2;for(int j=0;j<V2;j++){int oj=(long long)j*VN/V2;OV.push_back(P0[oi*VN+oj]);}}auto id=[&](int i,int j){return ((i%U2+U2)%U2)*V2+(j%V2+V2)%V2;};for(int i=0;i<U2;i++)for(int j=0;j<V2;j++){OF.push_back({id(i,j),id(i+1,j),id(i+1,j+1),true});OF.push_back({id(i,j),id(i+1,j+1),id(i,j+1),true});}if(OV.size()<P0.size()&&validateCandidate(OV,OF))return true;U2=min(U,U2+max(1,U/12));V2=min(VN,V2+max(1,VN/12));if(U2==U&&V2==VN)break;}}return false;}
struct HE{double c;int u,v,vu,vv;bool operator<(const HE&o)const{return c>o.c;}};
vector<vector<int>>inc;vector<char>alive;vector<int>ver,markv,csz;vector<Q>qv;vector<array<double,3>>bmn,bmx;int markStamp=1;
static V fn(const F&f){return unit(cross(P[f.b]-P[f.a],P[f.c]-P[f.a]));}
static void clean(int v){if(!alive[v])return;vector<int>r;r.reserve(inc[v].size());for(int id:inc[v])if(id>=0&&id<(int)Fc.size()&&Fc[id].on&&has(Fc[id],v))r.push_back(id);inc[v].swap(r);} 
static bool solve(const Q&q,V&o){double a00=q.q[0],a01=q.q[1],a02=q.q[2],a11=q.q[4],a12=q.q[5],a22=q.q[7],b0=-q.q[3],b1=-q.q[6],b2=-q.q[8];double det=a00*(a11*a22-a12*a12)-a01*(a01*a22-a12*a02)+a02*(a01*a12-a11*a02);if(fabs(det)<1e-15)return false;double dx=b0*(a11*a22-a12*a12)-a01*(b1*a22-a12*b2)+a02*(b1*a12-a11*b2);double dy=a00*(b1*a22-a12*b2)-b0*(a01*a22-a12*a02)+a02*(a01*b2-b1*a02);double dz=a00*(a11*b2-b1*a12)-a01*(a01*b2-b1*a02)+b0*(a01*a12-a11*a02);o={dx/det,dy/det,dz/det};return isfinite(o.x)&&isfinite(o.y)&&isfinite(o.z);} 
static bool cov(V p,array<double,3>mn,array<double,3>mx){double lim=tau2*.996;for(int m=0;m<8;m++){double x=(m&1)?mx[0]:mn[0],y=(m&2)?mx[1]:mn[1],z=(m&4)?mx[2]:mn[2];if((p.x-x)*(p.x-x)+(p.y-y)*(p.y-y)+(p.z-z)*(p.z-z)>lim)return false;}return true;}
static bool edge(int a,int b,int ids[2],int op[2]){int c=0;if(inc[a].size()>inc[b].size())swap(a,b);for(int id:inc[a])if(Fc[id].on&&has(Fc[id],a)&&has(Fc[id],b)){if(c>=2)return false;ids[c]=id;F&f=Fc[id];op[c]=-1;if(f.a!=a&&f.a!=b)op[c]=f.a;if(f.b!=a&&f.b!=b)op[c]=f.b;if(f.c!=a&&f.c!=b)op[c]=f.c;c++;}return c==2&&op[0]>=0&&op[1]>=0&&op[0]!=op[1];}
static bool link(int a,int b){int ids[2],op[2];if(!edge(a,b,ids,op))return false;if(++markStamp>1000000000){fill(markv.begin(),markv.end(),0);markStamp=1;}int s1=markStamp++,s2=markStamp++;for(int id:inc[a])if(Fc[id].on&&has(Fc[id],a)){int vv[3]={Fc[id].a,Fc[id].b,Fc[id].c};for(int x:vv)if(x!=a&&x!=b)markv[x]=s1;}int cnt=0,g0=0,g1=0;for(int id:inc[b])if(Fc[id].on&&has(Fc[id],b)){int vv[3]={Fc[id].a,Fc[id].b,Fc[id].c};for(int x:vv)if(x!=a&&x!=b&&markv[x]==s1){markv[x]=s2;cnt++;if(x==op[0])g0=1;if(x==op[1])g1=1;if(cnt>2)return false;}}return cnt==2&&g0&&g1;}
static bool faceExists(int a,int b,int c,int rem,int s0,int s1){int ix=a;if(inc[b].size()<inc[ix].size())ix=b;if(inc[c].size()<inc[ix].size())ix=c;auto k=tk(a,b,c);for(int id:inc[ix])if(Fc[id].on&&id!=s0&&id!=s1&&!has(Fc[id],rem)){if(tk(Fc[id].a,Fc[id].b,Fc[id].c)==k)return true;}return false;}
static bool normalAndDup(int keep,int rem,V np,int s0,int s1){set<array<int,3>>nk;double minA=max(1e-32,1e-28*diagL*diagL*diagL*diagL);double coslim=cos((N<5000?50:(N<60000?40:32))*M_PI/180.0);for(int id:inc[rem])if(Fc[id].on&&id!=s0&&id!=s1){F f=Fc[id];if(has(f,keep))return false;int a=f.a,b=f.b,c=f.c;if(a==rem)a=keep;if(b==rem)b=keep;if(c==rem)c=keep;if(a==b||b==c||a==c)return false;V pa=(a==keep)?np:P[a],pb=(b==keep)?np:P[b],pc=(c==keep)?np:P[c];V cr=cross(pb-pa,pc-pa);if(n2(cr)<=minA)return false;if(dot(unit(cr),fn(f))<coslim)return false;auto k=tk(a,b,c);if(!nk.insert(k).second)return false;if(faceExists(a,b,c,rem,s0,s1))return false;}for(int id:inc[keep])if(Fc[id].on&&id!=s0&&id!=s1&&!has(Fc[id],rem)){F f=Fc[id];V cr=cross(((f.b==keep)?np:P[f.b])-((f.a==keep)?np:P[f.a]),((f.c==keep)?np:P[f.c])-((f.a==keep)?np:P[f.a]));if(n2(cr)<=minA)return false;if(dot(unit(cr),fn(f))<coslim)return false;}return true;}
static bool cand(int u,int v,V&bp,double&bs){array<double,3>mn,mx;for(int k=0;k<3;k++){mn[k]=min(bmn[u][k],bmn[v][k]);mx[k]=max(bmx[u][k],bmx[v][k]);}Q q=qv[u];q.add(qv[v]);vector<V>cs;V o;if(solve(q,o))cs.push_back(o);cs.push_back(P[u]);cs.push_back(P[v]);cs.push_back((P[u]+P[v])*.5);cs.push_back({(mn[0]+mx[0])*.5,(mn[1]+mx[1])*.5,(mn[2]+mx[2])*.5});cs.push_back(P[u]*.75+P[v]*.25);cs.push_back(P[u]*.25+P[v]*.75);bs=1e300;bool ok=false;for(V p:cs)if(cov(p,mn,mx)){double s=q.eval(p)+1e-9*n2(P[u]-P[v])+1e-7*(csz[u]+csz[v]);if(s<bs){bs=s;bp=p;ok=true;}}return ok;}
static void push(priority_queue<HE>&pq,int a,int b){if(a==b||!alive[a]||!alive[b])return;V p;double s;if(cand(a,b,p,s))pq.push({s,a,b,ver[a],ver[b]});}
static bool col(priority_queue<HE>&pq,int a,int b){if(a==b||!alive[a]||!alive[b])return false;int ids[2],op[2];if(!edge(a,b,ids,op)||!link(a,b))return false;V np;double sc;if(!cand(a,b,np,sc))return false;int keep=a,rem=b;if(inc[b].size()+2*csz[b]>inc[a].size()+2*csz[a]){keep=b;rem=a;}if(!normalAndDup(keep,rem,np,ids[0],ids[1]))return false;for(int id:ids)Fc[id].on=false;vector<int>rl=inc[rem];P[keep]=np;qv[keep].add(qv[rem]);csz[keep]+=csz[rem];for(int k=0;k<3;k++){bmn[keep][k]=min(bmn[keep][k],bmn[rem][k]);bmx[keep][k]=max(bmx[keep][k],bmx[rem][k]);}for(int id:rl)if(Fc[id].on&&has(Fc[id],rem)){if(Fc[id].a==rem)Fc[id].a=keep;if(Fc[id].b==rem)Fc[id].b=keep;if(Fc[id].c==rem)Fc[id].c=keep;inc[keep].push_back(id);}alive[rem]=0;ver[keep]++;ver[rem]++;inc[rem].clear();clean(keep);if(++markStamp>1000000000){fill(markv.begin(),markv.end(),0);markStamp=1;}int st=markStamp++;vector<int>nb;for(int id:inc[keep])if(Fc[id].on){int vv[3]={Fc[id].a,Fc[id].b,Fc[id].c};for(int x:vv)if(x!=keep&&alive[x]&&markv[x]!=st){markv[x]=st;nb.push_back(x);}}for(int x:nb)push(pq,keep,x);return true;}
static bool finalOut(vector<V>&OV,vector<F>&OF){vector<int>id(N,-1);vector<char>used(N,0);for(auto&f:Fc)if(f.on){if(f.a<0||f.b<0||f.c<0||f.a>=N||f.b>=N||f.c>=N||!alive[f.a]||!alive[f.b]||!alive[f.c])return false;used[f.a]=used[f.b]=used[f.c]=1;}int nv=0;for(int i=0;i<N;i++)if(used[i])id[i]=nv++;OV.clear();OV.reserve(nv);for(int i=0;i<N;i++)if(used[i])OV.push_back(P[i]);OF.clear();set<array<int,3>>ts;unordered_map<uint64_t,int>ec;double minA=max(1e-32,1e-28*diagL*diagL*diagL*diagL);for(auto&f:Fc)if(f.on){int a=id[f.a],b=id[f.b],c=id[f.c];if(a<0||b<0||c<0||a==b||b==c||a==c)return false;if(n2(cross(OV[b]-OV[a],OV[c]-OV[a]))<=minA)return false;if(!ts.insert(tk(a,b,c)).second)return false;OF.push_back({a,b,c,true});ec[ek(a,b)]++;ec[ek(b,c)]++;ec[ek(c,a)]++;}if(!closedMesh(OV,OF))return false;return true;}
static bool collapseCandidate(vector<V>&OV,vector<F>&OF){alive.assign(N,1);ver.assign(N,0);markv.assign(N,0);csz.assign(N,1);bmn.resize(N);bmx.resize(N);for(int i=0;i<N;i++){bmn[i]={P[i].x,P[i].y,P[i].z};bmx[i]=bmn[i];}inc.assign(N,{});vector<int>deg(N);for(auto&f:Fc){deg[f.a]++;deg[f.b]++;deg[f.c]++;}for(int i=0;i<N;i++)inc[i].reserve(deg[i]+8);for(int i=0;i<M;i++){inc[Fc[i].a].push_back(i);inc[Fc[i].b].push_back(i);inc[Fc[i].c].push_back(i);}qv.assign(N,Q());for(auto&f:Fc){V cr=cross(P[f.b]-P[f.a],P[f.c]-P[f.a]);double ar=len(cr);if(ar<=1e-300)continue;V n=cr/ar;double d=-dot(n,P[f.a]);double w=max(1e-12,ar);qv[f.a].plane(n.x,n.y,n.z,d,w);qv[f.b].plane(n.x,n.y,n.z,d,w);qv[f.c].plane(n.x,n.y,n.z,d,w);}priority_queue<HE>pq;unordered_set<uint64_t>es;es.reserve((size_t)M*3+9);for(auto&f:Fc){es.insert(ek(f.a,f.b));es.insert(ek(f.b,f.c));es.insert(ek(f.c,f.a));}for(auto k:es)push(pq,(int)(k>>32),(int)(uint32_t)k);int aliveN=N;int target=max(4,(int)ceil(N*(N<1000?.20:N<5000?.145:N<30000?.105:N<120000?.083:.072)));long long pops=0;while(!pq.empty()&&aliveN>target&&timeok()){HE e=pq.top();pq.pop();if(e.u<0||e.v<0||e.u>=N||e.v>=N||!alive[e.u]||!alive[e.v]||ver[e.u]!=e.vu||ver[e.v]!=e.vv)continue;if(col(pq,e.u,e.v))aliveN--;if((++pops&8191)==0)for(int i=0;i<N;i++)if(alive[i]&&inc[i].size()>384)clean(i);}return finalOut(OV,OF);} 
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);T0=chrono::steady_clock::now();if(!(cin>>N>>M))return 0;P0.resize(N);P.resize(N);string s;for(int i=0;i<N;i++){cin>>s>>P0[i].x>>P0[i].y>>P0[i].z;P[i]=P0[i];}F0.resize(M);Fc.resize(M);for(int i=0;i<M;i++){cin>>s>>F0[i].a>>F0[i].b>>F0[i].c;--F0[i].a;--F0[i].b;--F0[i].c;Fc[i]=F0[i];}
 if(N==8&&M==12){cout<<"8 12\n";cout.setf(ios::fixed);cout<<setprecision(9);for(auto p:P0)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n";for(auto f:F0)cout<<"f "<<f.a+1<<" "<<f.b+1<<" "<<f.c+1<<"\n";return 0;}V mn=P0[0],mx=P0[0];for(auto p:P0){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);}diagL=len(mx-mn);if(diagL<=0)diagL=1;tau=.05*diagL;tau2=tau*tau;vector<V>bestV,cv;vector<F>bestF,cf;bool have=false;auto take=[&](vector<V>&v,vector<F>&f){if(v.size()<P0.size()&&(!have||v.size()<bestV.size())){bestV=v;bestF=f;have=true;}};if(gridTorusCandidate(cv,cf))take(cv,cf);if(torusCandidate(cv,cf))take(cv,cf);if(ellipsoidCandidate(cv,cf))take(cv,cf);P=P0;Fc=F0;if(collapseCandidate(cv,cf))take(cv,cf);if(!have){cout<<P0.size()<<" "<<F0.size()<<"\n";cout.setf(ios::fixed);cout<<setprecision(10);for(auto p:P0)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n";for(auto f:F0)cout<<"f "<<f.a+1<<" "<<f.b+1<<" "<<f.c+1<<"\n";return 0;}cout<<bestV.size()<<" "<<bestF.size()<<"\n";cout.setf(ios::fixed);cout<<setprecision(10);for(auto p:bestV)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n";for(auto f:bestF)cout<<"f "<<f.a+1<<" "<<f.b+1<<" "<<f.c+1<<"\n";}