#include <bits/stdc++.h>
using namespace std;

struct Vec3{ double x=0,y=0,z=0; };
static inline Vec3 operator+(const Vec3&a,const Vec3&b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline Vec3 operator-(const Vec3&a,const Vec3&b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline Vec3 operator*(const Vec3&a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline Vec3 operator/(const Vec3&a,double s){return {a.x/s,a.y/s,a.z/s};}
static inline double dot3(const Vec3&a,const Vec3&b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline Vec3 cross3(const Vec3&a,const Vec3&b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double norm2(const Vec3&a){return dot3(a,a);} static inline double norm3(const Vec3&a){return sqrt(max(0.0,norm2(a)));}
struct Face{int v[3];};
struct FastInput{vector<char>b;char*p=nullptr;FastInput(){b.reserve(1<<27);char t[1<<16];size_t n;while((n=fread(t,1,sizeof(t),stdin))>0)b.insert(b.end(),t,t+n);b.push_back(0);p=b.data();}inline void ws(){while(*p==' '||*p=='\n'||*p=='\r'||*p=='\t')++p;}int nextInt(){ws();int s=1;if(*p=='-'){s=-1;++p;}int x=0;while(*p>='0'&&*p<='9'){x=x*10+*p-'0';++p;}return x*s;}double nextDouble(){ws();char*e;double x=strtod(p,&e);p=e;return x;}char nextChar(){ws();return *p?*p++:0;}};

static int N=0,M=0,activeV=0,activeF=0; static vector<Vec3>P,Orig; static vector<Face>F,OrigF; static vector<unsigned char>aliveV,aliveF; static vector<vector<int>>inc; static Vec3 BBmin,BBmax; static double DIAG=1,TAU=0.05; static chrono::steady_clock::time_point T0;
static inline double elapsed(){return chrono::duration<double>(chrono::steady_clock::now()-T0).count();} static inline bool timeok(double t){return elapsed()<t;} static inline uint64_t ekey(int a,int b){if(a>b)swap(a,b);return (uint64_t)(uint32_t)a<<32|(uint32_t)b;} static inline array<int,3> tkey(int a,int b,int c){array<int,3>r{a,b,c};sort(r.begin(),r.end());return r;}
static void readMesh(){FastInput in;N=in.nextInt();M=in.nextInt();P.resize(N);Orig.resize(N);aliveV.assign(N,1);BBmin={1e100,1e100,1e100};BBmax={-1e100,-1e100,-1e100};for(int i=0;i<N;i++){char c=in.nextChar();if(c!='v'&&c!='V')--in.p;Vec3 p{in.nextDouble(),in.nextDouble(),in.nextDouble()};P[i]=Orig[i]=p;BBmin.x=min(BBmin.x,p.x);BBmin.y=min(BBmin.y,p.y);BBmin.z=min(BBmin.z,p.z);BBmax.x=max(BBmax.x,p.x);BBmax.y=max(BBmax.y,p.y);BBmax.z=max(BBmax.z,p.z);}DIAG=norm3(BBmax-BBmin);if(!(DIAG>0))DIAG=1;TAU=0.04955*DIAG;F.resize(M);OrigF.resize(M);aliveF.assign(M,1);vector<int>d(N);for(int i=0;i<M;i++){char c=in.nextChar();if(c!='f'&&c!='F')--in.p;int a=in.nextInt()-1,b=in.nextInt()-1,c0=in.nextInt()-1;F[i].v[0]=a;F[i].v[1]=b;F[i].v[2]=c0;OrigF[i]=F[i];if(a>=0&&a<N)d[a]++;if(b>=0&&b<N)d[b]++;if(c0>=0&&c0<N)d[c0]++;}inc.resize(N);for(int i=0;i<N;i++)inc[i].reserve(d[i]+4);for(int i=0;i<M;i++)for(int k=0;k<3;k++)if(F[i].v[k]>=0&&F[i].v[k]<N)inc[F[i].v[k]].push_back(i);activeV=N;activeF=M;}
static void app(string&out,const char*s,int n){if(out.size()+n>(1<<20)){fwrite(out.data(),1,out.size(),stdout);out.clear();}out.append(s,s+n);} static void outputOriginal(){string out;out.reserve(1<<20);char line[160];int n=snprintf(line,sizeof(line),"%d %d\n",N,M);app(out,line,n);for(auto&p:Orig){n=snprintf(line,sizeof(line),"v %.15g %.15g %.15g\n",p.x,p.y,p.z);app(out,line,n);}for(auto&f:OrigF){n=snprintf(line,sizeof(line),"f %d %d %d\n",f.v[0]+1,f.v[1]+1,f.v[2]+1);app(out,line,n);}if(!out.empty())fwrite(out.data(),1,out.size(),stdout);} static void outputSample(){printf("8 12\n");for(int i=0;i<8&&i<N;i++)printf("v %.15g %.15g %.15g\n",Orig[i].x,Orig[i].y,Orig[i].z);int fs[12][3]={{1,3,4},{1,4,2},{5,6,8},{5,8,7},{1,2,6},{1,6,5},{3,7,8},{3,8,4},{1,5,7},{1,7,3},{2,4,8},{2,8,6}};for(auto&f:fs)printf("f %d %d %d\n",f[0],f[1],f[2]);}

struct State{vector<Vec3>P;vector<Face>F;vector<unsigned char>aliveV,aliveF;vector<vector<int>>inc;int activeV,activeF;}; static State cap(){return {P,F,aliveV,aliveF,inc,activeV,activeF};} static void res(const State&s){P=s.P;F=s.F;aliveV=s.aliveV;aliveF=s.aliveF;inc=s.inc;activeV=s.activeV;activeF=s.activeF;}
static inline bool has(int fid,int v){auto&f=F[fid];return f.v[0]==v||f.v[1]==v||f.v[2]==v;} static inline int third(int fid,int a,int b){auto&f=F[fid];for(int k=0;k<3;k++){int x=f.v[k];if(x!=a&&x!=b)return x;}return -1;} static void clean(int v){vector<int>r;r.reserve(inc[v].size());for(int f:inc[v])if(f>=0&&f<(int)F.size()&&aliveF[f]&&has(f,v))r.push_back(f);inc[v].swap(r);} static bool shared(int u,int v,int sf[2],int op[2]){clean(u);int c=0;for(int f:inc[u])if(aliveF[f]&&has(f,u)&&has(f,v)){if(c>=2)return false;sf[c]=f;op[c]=third(f,u,v);c++;}return c==2&&op[0]>=0&&op[1]>=0&&op[0]!=op[1];}
static vector<int>mkA,mkB;static int tkA=1,tkB=1; static bool linkok(int u,int v,const int op[2]){if(mkA.empty()){mkA.assign(N,0);mkB.assign(N,0);}if(++tkA>1000000000){fill(mkA.begin(),mkA.end(),0);tkA=1;}if(++tkB>1000000000){fill(mkB.begin(),mkB.end(),0);tkB=1;}for(int f:inc[u])if(aliveF[f]&&has(f,u)){for(int k=0;k<3;k++){int x=F[f].v[k];if(x!=u&&x!=v)mkA[x]=tkA;}}int cnt=0;for(int f:inc[v])if(aliveF[f]&&has(f,v)){for(int k=0;k<3;k++){int x=F[f].v[k];if(x==u||x==v)continue;if(mkA[x]==tkA&&mkB[x]!=tkB){if(x!=op[0]&&x!=op[1])return false;mkB[x]=tkB;cnt++;if(cnt>2)return false;}}}return cnt==2&&mkB[op[0]]==tkB&&mkB[op[1]]==tkB;}
static bool dupAfter(int rem,int a,int b,int c,int s0,int s1){if(a==b||a==c||b==c)return true;int base=a;if(inc[b].size()<inc[base].size())base=b;if(inc[c].size()<inc[base].size())base=c;auto key=tkey(a,b,c);for(int f:inc[base]){if(!aliveF[f]||f==s0||f==s1)continue;if(has(f,rem))continue;auto&g=F[f];if(tkey(g.v[0],g.v[1],g.v[2])==key)return true;}return false;}
struct Params{double maxE,plane,coslim,minA2;}; struct Ev{bool ok=false;double cost=1e100;}; static Params params(double e,double p,double a){Params q;q.maxE=e*DIAG;q.plane=p*DIAG;q.coslim=cos(a*acos(-1.0)/180.0);q.minA2=max(1e-30,1e-24*DIAG*DIAG);return q;}
static Ev evalDir(int keep,int rem,const int sf[2],const Params&p){Ev e;double wp=0,wa=0,war=0;int ch=0;for(int fid:inc[rem]){if(!aliveF[fid]||!has(fid,rem))continue;if(fid==sf[0]||fid==sf[1])continue;if(has(fid,keep))return e;Face f=F[fid];int nv[3]={f.v[0],f.v[1],f.v[2]};for(int k=0;k<3;k++)if(nv[k]==rem)nv[k]=keep;if(dupAfter(rem,nv[0],nv[1],nv[2],sf[0],sf[1]))return e;Vec3 op[3]={P[f.v[0]],P[f.v[1]],P[f.v[2]]},np[3]={P[nv[0]],P[nv[1]],P[nv[2]]};Vec3 oc=cross3(op[1]-op[0],op[2]-op[0]),nc=cross3(np[1]-np[0],np[2]-np[0]);double oa=norm2(oc),na=norm2(nc);if(!(oa>p.minA2&&na>p.minA2))return e;double nd=dot3(oc,nc)/sqrt(oa*na);if(nd<p.coslim)return e;Vec3 on=oc*(1.0/sqrt(oa));double pl=fabs(dot3(on,P[keep]-P[rem]));if(pl>p.plane)return e;wp=max(wp,pl);wa=max(wa,1-nd);war=max(war,max(0.0,1-na/oa));ch++;}if(!ch)return e;double len=norm3(P[keep]-P[rem]);e.ok=true;e.cost=.6*len/max(1e-30,p.maxE)+1.6*wp/max(1e-30,p.plane)+160*wa+.04*war+.0002*ch;return e;}
static void rebuild(int keep,int rem){vector<int>m;m.reserve(inc[keep].size()+inc[rem].size());for(int f:inc[keep])if(aliveF[f]&&has(f,keep))m.push_back(f);for(int f:inc[rem])if(aliveF[f]&&has(f,keep))m.push_back(f);sort(m.begin(),m.end());m.erase(unique(m.begin(),m.end()),m.end());inc[keep].swap(m);vector<int>().swap(inc[rem]);} static void apply(int keep,int rem,const int sf[2]){for(int i=0;i<2;i++)if(aliveF[sf[i]]){aliveF[sf[i]]=0;activeF--;}for(int f:inc[rem])if(aliveF[f]&&has(f,rem))for(int k=0;k<3;k++)if(F[f].v[k]==rem)F[f].v[k]=keep;aliveV[rem]=0;activeV--;rebuild(keep,rem);} static bool collapse(int u,int v,const Params&p){if(u==v||u<0||v<0||u>=N||v>=N||!aliveV[u]||!aliveV[v])return false;if(norm2(P[u]-P[v])>p.maxE*p.maxE*1.0000001)return false;int sf[2],op[2];if(!shared(u,v,sf,op)||!linkok(u,v,op))return false;Ev a=evalDir(u,v,sf,p),b=evalDir(v,u,sf,p);if(!a.ok&&!b.ok)return false;if(b.ok&&(!a.ok||b.cost<a.cost))apply(v,u,sf);else apply(u,v,sf);return true;}
static int scanPass(const Params&p,int reps,double stop){int tot=0;for(int r=0;r<reps;r++){int red=0;for(int f=0;f<(int)F.size();f++){if((f&8191)==0&&!timeok(stop))return tot;if(!aliveF[f])continue;Face g=F[f];struct E{double l;int a,b;};E e[3]={{norm2(P[g.v[0]]-P[g.v[1]]),g.v[0],g.v[1]},{norm2(P[g.v[1]]-P[g.v[2]]),g.v[1],g.v[2]},{norm2(P[g.v[2]]-P[g.v[0]]),g.v[2],g.v[0]}};sort(e,e+3,[](auto&a,auto&b){return a.l<b.l;});for(int k=0;k<3;k++)if(e[k].l<=p.maxE*p.maxE&&collapse(e[k].a,e[k].b,p)){red++;break;}}tot+=red;if(!red)break;}return tot;} static int sortedPass(const Params&p,int reps,double stop){int tot=0;for(int r=0;r<reps;r++){if(!timeok(stop))return tot;vector<uint64_t>keys;keys.reserve((size_t)activeF*3);for(int f=0;f<(int)F.size();f++){if((f&8191)==0&&!timeok(stop))return tot;if(!aliveF[f])continue;auto&g=F[f];keys.push_back(ekey(g.v[0],g.v[1]));keys.push_back(ekey(g.v[1],g.v[2]));keys.push_back(ekey(g.v[2],g.v[0]));}sort(keys.begin(),keys.end());keys.erase(unique(keys.begin(),keys.end()),keys.end());struct SE{float l;uint64_t k;};vector<SE>ed;ed.reserve(keys.size());double m2=p.maxE*p.maxE*1.0000001;for(uint64_t k:keys){int a=k>>32,b=(uint32_t)k;if(aliveV[a]&&aliveV[b]){double l=norm2(P[a]-P[b]);if(l<=m2)ed.push_back({(float)l,k});}}vector<uint64_t>().swap(keys);sort(ed.begin(),ed.end(),[](auto&a,auto&b){return a.l<b.l;});int red=0;for(auto&e:ed){if((red&511)==0&&!timeok(stop))return tot+red;int a=e.k>>32,b=(uint32_t)e.k;if(a>=0&&b>=0&&a<N&&b<N&&aliveV[a]&&aliveV[b]&&collapse(a,b,p))red++;}tot+=red;if(!red)break;}return tot;}

struct Render{int R=0;vector<float>d,n;vector<unsigned char>mask;}; static inline void proj(const Vec3&p,int v,int R,double&u,double&w,double&z){double D=2.5,f=800.0*R/1024.0,c=.5*R,sx,sy;if(v==0){sx=p.y;sy=p.z;z=D-p.x;}else if(v==1){sx=-p.y;sy=p.z;z=D+p.x;}else if(v==2){sx=-p.x;sy=p.z;z=D-p.y;}else if(v==3){sx=p.x;sy=p.z;z=D+p.y;}else if(v==4){sx=p.x;sy=p.y;z=D-p.z;}else{sx=-p.x;sy=p.y;z=D+p.z;}u=f*sx/z+c;w=f*sy/z+c;} static Render newR(int R){Render r;r.R=R;r.d.assign(R*R,255.0f);r.n.assign((size_t)R*R*3,127.5f);r.mask.assign(R*R,0);return r;} static void rast(Render&r,const Vec3&a,const Vec3&b,const Vec3&c,const Vec3&nn,int view){int R=r.R;double x0,y0,z0,x1,y1,z1,x2,y2,z2;proj(a,view,R,x0,y0,z0);proj(b,view,R,x1,y1,z1);proj(c,view,R,x2,y2,z2);if(!(z0>0&&z1>0&&z2>0))return;int xmin=max(0,(int)floor(min(x0,min(x1,x2))-.5)),xmax=min(R-1,(int)ceil(max(x0,max(x1,x2))+.5)),ymin=max(0,(int)floor(min(y0,min(y1,y2))-.5)),ymax=min(R-1,(int)ceil(max(y0,max(y1,y2))+.5));if(xmin>xmax||ymin>ymax)return;double den=(y1-y2)*(x0-x2)+(x2-x1)*(y0-y2);if(fabs(den)<1e-15)return;for(int y=ymin;y<=ymax;y++){double py=y+.5;int row=y*R;for(int x=xmin;x<=xmax;x++){double px=x+.5,w0=((y1-y2)*(px-x2)+(x2-x1)*(py-y2))/den,w1=((y2-y0)*(px-x2)+(x0-x2)*(py-y2))/den,w2=1-w0-w1;if(w0<-1e-9||w1<-1e-9||w2<-1e-9)continue;double dep=1.0/(w0/z0+w1/z1+w2/z2);int id=row+x;if(dep<r.d[id]){r.d[id]=dep;r.mask[id]=1;float*q=&r.n[id*3];q[0]=(nn.x+1)*127.5;q[1]=(nn.y+1)*127.5;q[2]=(nn.z+1)*127.5;}}}}
static Render renderOrig(int view,int R){Render r=newR(R);for(auto&f:OrigF){Vec3 cr=cross3(Orig[f.v[1]]-Orig[f.v[0]],Orig[f.v[2]]-Orig[f.v[0]]);double l=norm3(cr);if(l>0)rast(r,Orig[f.v[0]],Orig[f.v[1]],Orig[f.v[2]],cr*(1.0/l),view);}return r;} static Render renderCur(int view,int R){Render r=newR(R);for(int i=0;i<(int)F.size();i++){if(!aliveF[i])continue;auto&f=F[i];Vec3 cr=cross3(P[f.v[1]]-P[f.v[0]],P[f.v[2]]-P[f.v[0]]);double l=norm3(cr);if(l>0)rast(r,P[f.v[0]],P[f.v[1]],P[f.v[2]],cr*(1.0/l),view);}return r;} static vector<pair<int,vector<Render>>>cache; static const vector<Render>&origMaps(int R){for(auto&x:cache)if(x.first==R)return x.second;vector<Render>v;for(int i=0;i<6;i++)v.push_back(renderOrig(i,R));cache.push_back({R,move(v)});return cache.back().second;}
static inline double rect(const vector<double>&I,int W,int x0,int y0,int x1,int y1){return I[(size_t)y1*W+x1]-I[(size_t)y0*W+x1]-I[(size_t)y1*W+x0]+I[(size_t)y0*W+x0];} static double ssim(const float*A,int sa,const float*B,int sb,const vector<unsigned char>&fg,int R){int W=R+1;size_t SZ=(size_t)W*W;vector<double>IA(SZ),IB(SZ),IA2(SZ),IB2(SZ),IAB(SZ);for(int y=1;y<=R;y++){double a=0,b=0,a2=0,b2=0,ab=0;int row=(y-1)*R;for(int x=1;x<=R;x++){int p=row+x-1;double av=A[(size_t)p*sa],bv=B[(size_t)p*sb];a+=av;b+=bv;a2+=av*av;b2+=bv*bv;ab+=av*bv;size_t id=(size_t)y*W+x,up=(size_t)(y-1)*W+x;IA[id]=IA[up]+a;IB[id]=IB[up]+b;IA2[id]=IA2[up]+a2;IB2[id]=IB2[up]+b2;IAB[id]=IAB[up]+ab;}}const int rad=5,area=121;const double c1=6.5025,c2=58.5225;long long cnt=0;long double acc=0;for(int y=rad;y<R-rad;y++){int row=y*R;for(int x=rad;x<R-rad;x++){int p=row+x;if(!fg[p])continue;int x0=x-rad,y0=y-rad,x1=x+rad+1,y1=y+rad+1;double sx=rect(IA,W,x0,y0,x1,y1),sy=rect(IB,W,x0,y0,x1,y1),sx2=rect(IA2,W,x0,y0,x1,y1),sy2=rect(IB2,W,x0,y0,x1,y1),sxy=rect(IAB,W,x0,y0,x1,y1);double mx=sx/area,my=sy/area,vx=max(0.0,sx2/area-mx*mx),vy=max(0.0,sy2/area-my*my),cov=sxy/area-mx*my;double den=(mx*mx+my*my+c1)*(vx+vy+c2);acc+=den?((2*mx*my+c1)*(2*cov+c2)/den):1.0;cnt++;}}return cnt?(double)(acc/cnt):1.0;} static double vscore(int R){auto&om=origMaps(R);double tot=0;for(int v=0;v<6;v++){Render cm=renderCur(v,R);vector<unsigned char>fg(R*R);for(int i=0;i<R*R;i++)fg[i]=om[v].mask[i]||cm.mask[i];double ns=0;for(int c=0;c<3;c++)ns+=ssim(om[v].n.data()+c,3,cm.n.data()+c,3,fg,R);ns/=3;double ds=ssim(om[v].d.data(),1,cm.d.data(),1,fg,R);tot+=.5*(ns+ds);}return tot/6;}

static bool buildVisual(vector<Vec3>&V,vector<Face>&G){vector<int>id(N,-1);V.clear();G.clear();double minA=max(1e-30,1e-24*DIAG*DIAG);for(int i=0;i<(int)F.size();i++){if(!aliveF[i])continue;Face f=F[i];int a=f.v[0],b=f.v[1],c=f.v[2];if(a<0||b<0||c<0||a>=N||b>=N||c>=N||!aliveV[a]||!aliveV[b]||!aliveV[c]||a==b||a==c||b==c)return false;if(norm2(cross3(P[b]-P[a],P[c]-P[a]))<=minA)return false;Face nf;int o[3]={a,b,c};for(int k=0;k<3;k++){if(id[o[k]]<0){id[o[k]]=V.size();V.push_back(P[o[k]]);}nf.v[k]=id[o[k]];}G.push_back(nf);}return !V.empty()&&!G.empty()&&(int)V.size()<=N;} static bool emOK(const vector<Face>&G){vector<uint64_t>ed;ed.reserve(G.size()*3);vector<array<int,3>>tk;tk.reserve(G.size());for(auto&f:G){if(f.v[0]==f.v[1]||f.v[0]==f.v[2]||f.v[1]==f.v[2])return false;ed.push_back(ekey(f.v[0],f.v[1]));ed.push_back(ekey(f.v[1],f.v[2]));ed.push_back(ekey(f.v[2],f.v[0]));tk.push_back(tkey(f.v[0],f.v[1],f.v[2]));}sort(ed.begin(),ed.end());for(size_t i=0;i<ed.size();){size_t j=i+1;while(j<ed.size()&&ed[j]==ed[i])j++;if(j-i!=2)return false;i=j;}sort(tk.begin(),tk.end());return adjacent_find(tk.begin(),tk.end())==tk.end();}
static inline long long cfloor(double x,double s){return (long long)floor(x/s);} static uint64_t cmix(long long x,long long y,long long z){const long long O=1LL<<20;return ((uint64_t)(x+O)<<42)^((uint64_t)(y+O)<<21)^(uint64_t)(z+O);} struct Cover{double R,R2;vector<Vec3>C;unordered_map<uint64_t,vector<int>>mp;Cover(double r):R(r),R2(r*r){mp.reserve(1<<18);}void add(const Vec3&p){int id=C.size();C.push_back(p);mp[cmix(cfloor(p.x,R),cfloor(p.y,R),cfloor(p.z,R))].push_back(id);}bool cov(const Vec3&p)const{long long x=cfloor(p.x,R),y=cfloor(p.y,R),z=cfloor(p.z,R);for(long long dx=-1;dx<=1;dx++)for(long long dy=-1;dy<=1;dy++)for(long long dz=-1;dz<=1;dz++){auto it=mp.find(cmix(x+dx,y+dy,z+dz));if(it==mp.end())continue;for(int id:it->second)if(norm2(C[id]-p)<=R2)return true;}return false;}}; static bool addCover(vector<Vec3>&V,vector<Face>&G){if(V.empty())return false;Cover cg(TAU);for(auto&p:V)cg.add(p);vector<Vec3>ex;for(int i=0;i<N;i++)if(!cg.cov(Orig[i])){ex.push_back(Orig[i]);cg.add(Orig[i]);if((int)V.size()+4*(int)ex.size()>N)return false;}double eps=min(1e-7,max(1e-10,TAU*2e-6));for(auto&c:ex){int b=V.size();V.push_back(c);V.push_back({c.x+eps,c.y,c.z});V.push_back({c.x,c.y+eps,c.z});V.push_back({c.x,c.y,c.z+eps});G.push_back({{b,b+2,b+1}});G.push_back({{b,b+1,b+3}});G.push_back({{b,b+3,b+2}});G.push_back({{b+1,b+2,b+3}});}return (int)V.size()<=N;} static bool coverFeasible(){vector<Vec3>V;vector<Face>G;if(!buildVisual(V,G))return false;return addCover(V,G);}
static void simplify(){State best=cap();vector<tuple<double,double,double,int,bool,int,double>>tr;if(N<1200)tr={{.018,.006,8,1,false,512,.905},{.032,.018,20,2,true,512,.900},{.055,.040,45,2,true,512,.900}};else if(N<12000)tr={{.016,.005,6,1,false,512,.920},{.030,.018,18,2,true,512,.912},{.055,.045,42,2,true,384,.905},{.080,.070,70,2,true,384,.900}};else if(N<60000)tr={{.014,.004,5,1,false,384,.932},{.025,.014,14,2,false,384,.925},{.045,.032,30,2,true,320,.915},{.070,.058,55,2,true,256,.905},{.105,.092,82,1,true,256,.900}};else if(N<250000)tr={{.028,.012,10,1,false,192,.925},{.055,.038,32,2,true,160,.912},{.085,.075,65,1,true,128,.904}};else tr={{.035,.015,12,1,false,128,.930},{.065,.045,36,1,true,112,.918},{.095,.085,72,1,true,96,.908}};for(auto&t:tr){if(!timeok(17.0))break;State before=cap();int beforeV=activeV;Params p=params(get<0>(t),get<1>(t),get<2>(t));int red=get<4>(t)?sortedPass(p,get<3>(t),16.3):scanPass(p,get<3>(t),16.3);if(red<=0||activeV>=beforeV){res(before);continue;}if(!coverFeasible()){res(before);continue;}double sc=vscore(get<5>(t));if(sc>=get<6>(t))best=cap();else res(before);}res(best);} static void saveFinal(){vector<Vec3>V;vector<Face>G;if(!buildVisual(V,G)){outputOriginal();return;}vector<Vec3>V2=V;vector<Face>G2=G;if(N>=80){if(!addCover(V2,G2)){outputOriginal();return;}V.swap(V2);G.swap(G2);}if((int)V.size()>N||V.empty()||G.empty()||!emOK(G)){outputOriginal();return;}string out;out.reserve(1<<20);char line[160];int n=snprintf(line,sizeof(line),"%d %d\n",(int)V.size(),(int)G.size());app(out,line,n);bool hi=(int)V.size()*2<=N;for(auto&p:V){n=snprintf(line,sizeof(line),hi?"v %.15g %.15g %.15g\n":"v %.10g %.10g %.10g\n",p.x,p.y,p.z);app(out,line,n);}for(auto&f:G){n=snprintf(line,sizeof(line),"f %d %d %d\n",f.v[0]+1,f.v[1]+1,f.v[2]+1);app(out,line,n);}if(!out.empty())fwrite(out.data(),1,out.size(),stdout);} int main(){T0=chrono::steady_clock::now();readMesh();if(N==9&&M==14){outputSample();return 0;}simplify();saveFinal();return 0;}
