#include <bits/stdc++.h>
using namespace std;

struct V3{double x,y,z;};
static inline V3 operator+(const V3&a,const V3&b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline V3 operator-(const V3&a,const V3&b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline V3 operator*(const V3&a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline V3 operator/(const V3&a,double s){return {a.x/s,a.y/s,a.z/s};}
static inline double dotv(const V3&a,const V3&b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline V3 crossv(const V3&a,const V3&b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double len2(const V3&a){return dotv(a,a);} static inline double lenv(const V3&a){return sqrt(max(0.0,len2(a)));}
struct F3{int a,b,c;};
struct Q{double q[10]; Q(){memset(q,0,sizeof(q));}};
static inline void qadd(Q&a,const Q&b){for(int i=0;i<10;i++)a.q[i]+=b.q[i];}
static Q planeQ(const V3&p,V3 n){double l=lenv(n); Q r; if(l<=0)return r; n=n/l; double v[4]={n.x,n.y,n.z,-dotv(n,p)}; int k=0; for(int i=0;i<4;i++)for(int j=i;j<4;j++)r.q[k++]=v[i]*v[j]; return r;}
static double qval(const Q&r,const V3&p){double x=p.x,y=p.y,z=p.z;return r.q[0]*x*x+2*r.q[1]*x*y+2*r.q[2]*x*z+2*r.q[3]*x+r.q[4]*y*y+2*r.q[5]*y*z+2*r.q[6]*y+r.q[7]*z*z+2*r.q[8]*z+r.q[9];}
static bool solveQ(const Q&r,V3&x){double a[3][4]={{r.q[0],r.q[1],r.q[2],-r.q[3]},{r.q[1],r.q[4],r.q[5],-r.q[6]},{r.q[2],r.q[5],r.q[7],-r.q[8]}}; for(int c=0;c<3;c++){int p=c; for(int i=c+1;i<3;i++)if(fabs(a[i][c])>fabs(a[p][c]))p=i; if(fabs(a[p][c])<1e-12)return false; if(p!=c)for(int j=c;j<4;j++)swap(a[p][j],a[c][j]); double d=a[c][c]; for(int j=c;j<4;j++)a[c][j]/=d; for(int i=0;i<3;i++)if(i!=c){double t=a[i][c]; for(int j=c;j<4;j++)a[i][j]-=t*a[c][j];}} x={a[0][3],a[1][3],a[2][3]}; return isfinite(x.x)&&isfinite(x.y)&&isfinite(x.z);}

int N,M; vector<V3>P,P0; vector<F3>F,F0; vector<unsigned char>av,af,pin; vector<double>coverR; double D=1,EPS=1;
static inline unsigned long long keyE(int a,int b){if(a>b)swap(a,b);return (unsigned long long)(unsigned int)a<<32 | (unsigned int)b;}
static inline V3 rawN(const F3&f,const vector<V3>&V){return crossv(V[f.b]-V[f.a],V[f.c]-V[f.a]);}
static inline double area2(const F3&f,const vector<V3>&V){return lenv(rawN(f,V));}
static inline bool has(const F3&f,int v){return f.a==v||f.b==v||f.c==v;}
static inline int third(const F3&f,int u,int v){if(f.a!=u&&f.a!=v)return f.a; if(f.b!=u&&f.b!=v)return f.b; return f.c;}

struct Topo{vector<vector<int>> vf; unordered_map<unsigned long long,array<int,2>> ef; vector<pair<int,int>> edges; bool ok=true;};
static Topo build(){Topo T; T.vf.assign(N,{}); T.ef.reserve((size_t)M*3+7); for(int i=0;i<M;i++)if(af[i]){F3 f=F[i]; if(f.a<0||f.b<0||f.c<0||!av[f.a]||!av[f.b]||!av[f.c]||f.a==f.b||f.a==f.c||f.b==f.c||area2(f,P)<=D*D*1e-20){af[i]=0;continue;} T.vf[f.a].push_back(i); T.vf[f.b].push_back(i); T.vf[f.c].push_back(i); int v[3]={f.a,f.b,f.c}; for(int e=0;e<3;e++){auto k=keyE(v[e],v[(e+1)%3]); auto it=T.ef.find(k); if(it==T.ef.end())T.ef[k]={i,-1}; else if(it->second[1]<0)it->second[1]=i; else T.ok=false;}} for(auto &kv:T.ef){if(kv.second[0]<0||kv.second[1]<0)T.ok=false; int a=(int)(kv.first>>32),b=(int)(kv.first&0xffffffffu); T.edges.push_back({a,b});} return T;}

static void markPins(){
    if(N<=8){fill(pin.begin(),pin.end(),1);return;}
    V3 mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100}; for(auto&p:P){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);} vector<V3>vn(N,{0,0,0});
    for(auto&f:F){V3 n=rawN(f,P); double l=lenv(n); if(l>0)n=n/l; vn[f.a]=vn[f.a]+n; vn[f.b]=vn[f.b]+n; vn[f.c]=vn[f.c]+n;}
    int S=(N>70000?96:(N>30000?80:(N>12000?64:48))); struct C{double front=-1e300,back=1e300,sil=-1,curv=-1;int fi=-1,bi=-1,si=-1,ci=-1;};
    auto pass=[&](int ax,int sg){vector<C> G(S*S); double rx=max(1e-30,mx.x-mn.x),ry=max(1e-30,mx.y-mn.y),rz=max(1e-30,mx.z-mn.z); for(int i=0;i<N;i++){double u,v,d;if(ax==0){u=(P[i].y-mn.y)/ry;v=(P[i].z-mn.z)/rz;d=sg*P[i].x;}else if(ax==1){u=(P[i].x-mn.x)/rx;v=(P[i].z-mn.z)/rz;d=sg*P[i].y;}else{u=(P[i].x-mn.x)/rx;v=(P[i].y-mn.y)/ry;d=sg*P[i].z;} int iu=min(S-1,max(0,(int)(u*S))),iv=min(S-1,max(0,(int)(v*S))); C&c=G[iu*S+iv]; if(d>c.front){c.front=d;c.fi=i;} if(d<c.back){c.back=d;c.bi=i;} V3 n=vn[i]; double nl=lenv(n), comp=0; if(nl>0){n=n/nl; comp=(ax==0?fabs(n.x):(ax==1?fabs(n.y):fabs(n.z)));} double sil=1-comp; if(sil>c.sil){c.sil=sil;c.si=i;}} for(auto&c:G){if(c.fi>=0)pin[c.fi]=1;if(c.bi>=0)pin[c.bi]=1;if(c.si>=0&&c.sil>0.28)pin[c.si]=1;}};
    for(int ax=0;ax<3;ax++){pass(ax,1);pass(ax,-1);} int K=max(10,(int)sqrt((double)N)); for(int ax=0;ax<3;ax++)for(int sg=-1;sg<=1;sg+=2){vector<pair<double,int>> ord;ord.reserve(N);for(int i=0;i<N;i++)ord.push_back({(ax==0?P[i].x:(ax==1?P[i].y:P[i].z))*sg,i}); nth_element(ord.begin(),ord.begin()+min(K,N-1),ord.end()); for(int i=0;i<min(K,N);i++)pin[ord[i].second]=1;}
}

static vector<Q> quadrics(){vector<Q> R(N); for(int i=0;i<M;i++)if(af[i]){F3 f=F[i]; Q q=planeQ(P[f.a],rawN(f,P)); qadd(R[f.a],q);qadd(R[f.b],q);qadd(R[f.c],q);} return R;}

static bool linkOK(int u,int v,const Topo&T,int&f1,int&f2,int&o1,int&o2){auto it=T.ef.find(keyE(u,v)); if(it==T.ef.end())return false; f1=it->second[0]; f2=it->second[1]; if(f1<0||f2<0||f1==f2)return false; o1=third(F[f1],u,v); o2=third(F[f2],u,v); if(o1<0||o2<0||o1==o2)return false; unordered_set<int> A; A.reserve(T.vf[u].size()*2+8); for(int id:T.vf[u])if(af[id]){int a[3]={F[id].a,F[id].b,F[id].c}; for(int x:a)if(x!=u&&x!=v)A.insert(x);} unordered_set<int>S; bool h1=false,h2=false; for(int id:T.vf[v])if(af[id]){int a[3]={F[id].a,F[id].b,F[id].c}; for(int x:a)if(x!=u&&x!=v&&A.count(x)){S.insert(x); if(x==o1)h1=true; if(x==o2)h2=true;}} return S.size()==2&&h1&&h2;}
static bool dupAfter(int keep,int rem,int f1,int f2,const Topo&T){vector<int> ids=T.vf[keep]; ids.insert(ids.end(),T.vf[rem].begin(),T.vf[rem].end()); sort(ids.begin(),ids.end()); ids.erase(unique(ids.begin(),ids.end()),ids.end()); unordered_set<unsigned long long> seen; seen.reserve(ids.size()*2+8); for(int id:ids)if(af[id]&&id!=f1&&id!=f2){int a=F[id].a,b=F[id].b,c=F[id].c; if(a==rem)a=keep;if(b==rem)b=keep;if(c==rem)c=keep; if(a==b||a==c||b==c)continue; int v[3]={a,b,c}; sort(v,v+3); unsigned long long h=((unsigned long long)(unsigned int)v[0]<<42)^((unsigned long long)(unsigned int)v[1]<<21)^(unsigned int)v[2]; if(seen.count(h))return true; seen.insert(h);} return false;}

struct Cand{bool ok=false; double cost=1e100; int k=-1,r=-1,f1=-1,f2=-1; V3 p; double nr=0;};
static Cand evalDir(int k,int r,int f1,int f2,const Topo&T,const vector<Q>&Qv,const vector<V3>&opts,double nmin,double pmax){Cand best; best.k=k;best.r=r;best.f1=f1;best.f2=f2; if(pin[r]&&!pin[k])return best; if(dupAfter(k,r,f1,f2,T))return best; vector<int> ids=T.vf[k]; ids.insert(ids.end(),T.vf[r].begin(),T.vf[r].end()); sort(ids.begin(),ids.end()); ids.erase(unique(ids.begin(),ids.end()),ids.end()); Q qq=Qv[k];qadd(qq,Qv[r]); for(V3 np:opts){double dk=lenv(np-P[k]),dr=lenv(np-P[r]); double nr=max(coverR[k]+dk,coverR[r]+dr); if(nr>EPS*0.985)continue; if(pin[r]&&dk+dr>EPS*0.58)continue; bool ok=true; double wn=0,wp=0,wa=0; for(int id:ids)if(af[id]&&id!=f1&&id!=f2){F3 old=F[id], nf=old; if(nf.a==r)nf.a=k;if(nf.b==r)nf.b=k;if(nf.c==r)nf.c=k; if(nf.a==nf.b||nf.a==nf.c||nf.b==nf.c){ok=false;break;} V3 oldn=rawN(old,P); double ao=lenv(oldn); if(ao<=D*D*1e-20){ok=false;break;} V3 a=(nf.a==k?np:P[nf.a]),b=(nf.b==k?np:P[nf.b]),c=(nf.c==k?np:P[nf.c]); V3 newn=crossv(b-a,c-a); double an=lenv(newn); if(an<=D*D*1e-20){ok=false;break;} double nd=dotv(oldn,newn)/(ao*an); if(nd<nmin){ok=false;break;} V3 un=oldn/ao; double pd=fabs(dotv(un,np-P[old.a])); if(pd>pmax){ok=false;break;} if(an<ao*2e-6){ok=false;break;} wn=max(wn,1-nd); wp=max(wp,pd/max(1e-30,pmax)); wa=max(wa,max(0.0,1.0-an/ao)); } if(!ok)continue; double cost=qval(qq,np)+0.035*nr/EPS+30*wn+0.7*wp+0.15*wa+(pin[k]?0.05:0)+(pin[r]?0.7:0); if(cost<best.cost){best.ok=true;best.cost=cost;best.p=np;best.nr=nr;}} return best;}
static Cand evalEdge(int u,int v,const Topo&T,const vector<Q>&Qv,double nmin,double pmax){Cand z; if(!av[u]||!av[v])return z; int f1,f2,o1,o2; if(!linkOK(u,v,T,f1,f2,o1,o2))return z; Q qq=Qv[u]; qadd(qq,Qv[v]); V3 qpt; bool sq=solveQ(qq,qpt); V3 mid=(P[u]+P[v])*0.5; vector<V3> opts={P[u],P[v],mid,(P[u]*0.75+P[v]*0.25),(P[u]*0.25+P[v]*0.75)}; if(sq&&lenv(qpt-mid)<D*0.12)opts.push_back(qpt); Cand a=evalDir(u,v,f1,f2,T,Qv,opts,nmin,pmax), b=evalDir(v,u,f1,f2,T,Qv,opts,nmin,pmax); if(a.ok&&(!b.ok||a.cost<=b.cost))return a; return b;}
static void apply(const Cand&c){V3 oldk=P[c.k], oldr=P[c.r]; P[c.k]=c.p; coverR[c.k]=max(coverR[c.k]+lenv(c.p-oldk),coverR[c.r]+lenv(c.p-oldr)); if(coverR[c.k]>EPS)coverR[c.k]=EPS*0.999; pin[c.k]=pin[c.k]||pin[c.r]; af[c.f1]=0; af[c.f2]=0; for(int i=0;i<M;i++)if(af[i]){if(F[i].a==c.r)F[i].a=c.k;if(F[i].b==c.r)F[i].b=c.k;if(F[i].c==c.r)F[i].c=c.k;if(F[i].a==F[i].b||F[i].a==F[i].c||F[i].b==F[i].c)af[i]=0;} av[c.r]=0;}
static bool validClosed(){unordered_map<unsigned long long,int> C; C.reserve((size_t)M*3+8); int fc=0; for(int i=0;i<M;i++)if(af[i]){F3 f=F[i]; if(!av[f.a]||!av[f.b]||!av[f.c]||f.a==f.b||f.a==f.c||f.b==f.c||area2(f,P)<=D*D*1e-20)return false; fc++; int v[3]={f.a,f.b,f.c}; for(int e=0;e<3;e++)C[keyE(v[e],v[(e+1)%3])]++;} if(fc==0)return false; for(auto&kv:C)if(kv.second!=2)return false; return true;}
static int aliveCnt(){int c=0;for(auto x:av)c+=x?1:0;return c;}

static void simplify(){if(N<=8)return; auto saveP=P; auto saveF=F; auto saveav=av, saveaf=af; markPins(); auto t0=chrono::steady_clock::now(); double nminA[6]={0.99985,0.9992,0.9975,0.994,0.988,0.978}; double lenA[6]={0.014,0.022,0.032,0.043,0.055,0.068}; for(int pass=0;pass<6;pass++){Topo T=build(); if(!T.ok)break; auto Qv=quadrics(); vector<pair<double,pair<int,int>>> ord; ord.reserve(T.edges.size()); for(auto&e:T.edges){double l=lenv(P[e.first]-P[e.second]); if(l<=D*lenA[pass]) ord.push_back({l,e});} sort(ord.begin(),ord.end()); int ch=0,lim=0; for(auto&oe:ord){if(++lim>260000)break; int u=oe.second.first,v=oe.second.second; if(!av[u]||!av[v])continue; Cand c=evalEdge(u,v,T,Qv,nminA[pass],D*(0.0035+0.0022*pass)); if(!c.ok)continue; apply(c); ch++; if((ch&127)==0){T=build(); if(!T.ok)goto done; Qv=quadrics();} if(chrono::duration<double>(chrono::steady_clock::now()-t0).count()>1.92)goto done;} if(ch<12&&pass>=2){} if(aliveCnt()<max(8,N/25))break; if(chrono::duration<double>(chrono::steady_clock::now()-t0).count()>1.92)break;} done: if(!validClosed()){P=saveP;F=saveF;av=saveav;af=saveaf;}}
static void output(){vector<int> id(N,-1); int vc=0,fc=0; for(int i=0;i<N;i++)if(av[i])id[i]=++vc; for(int i=0;i<M;i++)if(af[i]&&av[F[i].a]&&av[F[i].b]&&av[F[i].c]&&F[i].a!=F[i].b&&F[i].a!=F[i].c&&F[i].b!=F[i].c&&area2(F[i],P)>D*D*1e-20)fc++; cout<<vc<<' '<<fc<<'\n'; cout.setf(ios::fixed); cout<<setprecision(10); for(int i=0;i<N;i++)if(av[i])cout<<"v "<<P[i].x<<' '<<P[i].y<<' '<<P[i].z<<'\n'; for(int i=0;i<M;i++)if(af[i]&&av[F[i].a]&&av[F[i].b]&&av[F[i].c]&&F[i].a!=F[i].b&&F[i].a!=F[i].c&&F[i].b!=F[i].c&&area2(F[i],P)>D*D*1e-20)cout<<"f "<<id[F[i].a]<<' '<<id[F[i].b]<<' '<<id[F[i].c]<<'\n';}
int main(){ios::sync_with_stdio(false);cin.tie(nullptr); if(!(cin>>N>>M))return 0; P.resize(N);P0.resize(N);F.resize(M);F0.resize(M); V3 mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100}; char ch; for(int i=0;i<N;i++){cin>>ch>>P[i].x>>P[i].y>>P[i].z;P0[i]=P[i];mn.x=min(mn.x,P[i].x);mn.y=min(mn.y,P[i].y);mn.z=min(mn.z,P[i].z);mx.x=max(mx.x,P[i].x);mx.y=max(mx.y,P[i].y);mx.z=max(mx.z,P[i].z);} for(int i=0;i<M;i++){cin>>ch>>F[i].a>>F[i].b>>F[i].c;--F[i].a;--F[i].b;--F[i].c;F0[i]=F[i];} D=lenv(mx-mn); if(!(D>0))D=1; EPS=D*0.04915; av.assign(N,1);af.assign(M,1);pin.assign(N,0);coverR.assign(N,0); simplify(); output(); }