#include <bits/stdc++.h>
using namespace std;
struct V{double x,y,z;};
struct F{int a,b,c;};
static inline V operator+(V a,V b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline V operator-(V a,V b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline V operator*(V a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline double dotv(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline V crossv(V a,V b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(V a){return dotv(a,a);} static inline double normv(V a){return sqrt(n2(a));}
struct FastIn{vector<char>b;char*p;FastIn(){char buf[1<<16];size_t n;while((n=fread(buf,1,sizeof(buf),stdin)))b.insert(b.end(),buf,buf+n);b.push_back(0);p=b.data();}inline void ws(){while(*p==' '||*p=='\n'||*p=='\r'||*p=='\t')++p;}long li(){ws();return strtol(p,&p,10);}double db(){ws();return strtod(p,&p);}char ch(){ws();return *p++;}};
int N,M,aliveV,aliveF; vector<V>P,orig; vector<F>fa; vector<unsigned char>av,af,lockv; vector<double>errv; vector<vector<int>> inc; vector<int> mark1,mark2; int tag1=1,tag2=1; double diagLen=1,epsArea=1e-30; chrono::steady_clock::time_point T0;
static inline double elapsed(){return chrono::duration<double>(chrono::steady_clock::now()-T0).count();}
static inline bool hasv(const F&f,int v){return f.a==v||f.b==v||f.c==v;}
static inline int other3(const F&f,int u,int v){if(f.a!=u&&f.a!=v)return f.a;if(f.b!=u&&f.b!=v)return f.b;return f.c;}
static inline array<int,3> sort3(int a,int b,int c){array<int,3>s={a,b,c}; sort(s.begin(),s.end()); return s;}
static inline bool sameTri(const F&f,int a,int b,int c){return sort3(f.a,f.b,f.c)==sort3(a,b,c);} 
static inline V faceN(const F&f){return crossv(P[f.b]-P[f.a],P[f.c]-P[f.a]);}
static inline unsigned long long ekey(int a,int b){if(a>b)swap(a,b);return (unsigned long long)(unsigned int)a<<32 | (unsigned int)b;}
void readInput(){FastIn in; N=(int)in.li(); M=(int)in.li(); P.resize(N); orig.resize(N); av.assign(N,1); af.assign(M,1); errv.assign(N,0); lockv.assign(N,0); fa.resize(M); V mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100}; for(int i=0;i<N;i++){char c=in.ch(); (void)c; P[i].x=in.db();P[i].y=in.db();P[i].z=in.db(); orig[i]=P[i]; mn.x=min(mn.x,P[i].x);mn.y=min(mn.y,P[i].y);mn.z=min(mn.z,P[i].z);mx.x=max(mx.x,P[i].x);mx.y=max(mx.y,P[i].y);mx.z=max(mx.z,P[i].z);} diagLen=normv(mx-mn); if(!(diagLen>0))diagLen=1; epsArea=max(1e-28,diagLen*diagLen*1e-28); double e=diagLen*1e-10+1e-12; for(int i=0;i<N;i++){if(fabs(P[i].x-mn.x)<=e||fabs(P[i].x-mx.x)<=e||fabs(P[i].y-mn.y)<=e||fabs(P[i].y-mx.y)<=e||fabs(P[i].z-mn.z)<=e||fabs(P[i].z-mx.z)<=e)lockv[i]=1;} vector<int>deg(N); for(int i=0;i<M;i++){char c=in.ch(); (void)c; int a=(int)in.li()-1,b=(int)in.li()-1,c2=(int)in.li()-1; fa[i]={a,b,c2}; if(a>=0&&a<N)deg[a]++; if(b>=0&&b<N)deg[b]++; if(c2>=0&&c2<N)deg[c2]++;} inc.resize(N); for(int i=0;i<N;i++)inc[i].reserve(deg[i]); for(int i=0;i<M;i++){inc[fa[i].a].push_back(i); inc[fa[i].b].push_back(i); inc[fa[i].c].push_back(i);} aliveV=N; aliveF=M; mark1.assign(N,0); mark2.assign(N,0);} 
double signedVol(){long double s=0; for(int i=0;i<M;i++){auto &f=fa[i]; V cr=crossv(P[f.b],P[f.c]); s+=dotv(P[f.a],cr);} return (double)s;}
bool tryBox(){ if(N<20||M<24)return false; V mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100}; for(auto&p:P){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);} double dx=mx.x-mn.x,dy=mx.y-mn.y,dz=mx.z-mn.z; if(dx<=0||dy<=0||dz<=0)return false; double tol=max({dx,dy,dz})*2e-7+1e-10; int on=0; for(auto&p:P){if(fabs(p.x-mn.x)<=tol||fabs(p.x-mx.x)<=tol||fabs(p.y-mn.y)<=tol||fabs(p.y-mx.y)<=tol||fabs(p.z-mn.z)<=tol||fabs(p.z-mx.z)<=tol)on++;} if(on<N*995/1000)return false; int good=0,total=0; for(auto&f:fa){V cr=crossv(P[f.b]-P[f.a],P[f.c]-P[f.a]); double l=normv(cr); if(l<=epsArea)continue; total++; double ax=fabs(cr.x),ay=fabs(cr.y),az=fabs(cr.z),ma=max({ax,ay,az}); if(ma/l>0.999)good++;} if(total==0||good<total*98/100)return false; vector<V>v={{mn.x,mn.y,mn.z},{mx.x,mn.y,mn.z},{mx.x,mx.y,mn.z},{mn.x,mx.y,mn.z},{mn.x,mn.y,mx.z},{mx.x,mn.y,mx.z},{mx.x,mx.y,mx.z},{mn.x,mx.y,mx.z}}; vector<array<int,3>>t={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,4,7},{0,7,3},{1,2,6},{1,6,5},{0,1,5},{0,5,4},{3,7,6},{3,6,2}}; if(signedVol()<0)for(auto &q:t)swap(q[1],q[2]); printf("8 12\n"); for(auto&p:v)printf("v %.17g %.17g %.17g\n",p.x,p.y,p.z); for(auto&q:t)printf("f %d %d %d\n",q[0]+1,q[1]+1,q[2]+1); return true; }
bool edgeFaces(int u,int v,int by[2],int op[2]){int cnt=0; auto &A=inc[u]; for(int fid:A){if(!af[fid])continue; F&f=fa[fid]; if(!hasv(f,u)||!hasv(f,v))continue; if(cnt>=2)return false; by[cnt]=fid; op[cnt]=other3(f,u,v); cnt++;} if(cnt!=2||op[0]<0||op[1]<0||op[0]==op[1])return false; return true;}
bool linkOK(int u,int v,const int op[2]){ if(++tag1>2000000000){fill(mark1.begin(),mark1.end(),0);tag1=1;} if(++tag2>2000000000){fill(mark2.begin(),mark2.end(),0);tag2=1;} for(int fid:inc[u])if(af[fid]&&hasv(fa[fid],u)){F&f=fa[fid]; int a[3]={f.a,f.b,f.c}; for(int x:a)if(x!=u&&x!=v)mark1[x]=tag1;} int got=0; for(int fid:inc[v])if(af[fid]&&hasv(fa[fid],v)){F&f=fa[fid]; int a[3]={f.a,f.b,f.c}; for(int x:a){if(x==u||x==v)continue; if(mark1[x]!=tag1)continue; if(x!=op[0]&&x!=op[1])return false; if(mark2[x]!=tag2){mark2[x]=tag2;got++;}}} return got==2&&mark2[op[0]]==tag2&&mark2[op[1]]==tag2;}
bool duplicateAfter(int keep,int rem,int fid,int a,int b,int c,int by0,int by1){int base=keep; if((int)inc[a].size()<(int)inc[base].size())base=a; if((int)inc[b].size()<(int)inc[base].size())base=b; if((int)inc[c].size()<(int)inc[base].size())base=c; for(int id:inc[base]){if(!af[id]||id==fid||id==by0||id==by1)continue; if(hasv(fa[id],rem))continue; if(sameTri(fa[id],a,b,c))return true;} return false;}
struct Eval{bool ok=false; double cost=1e100,ne=0;};
Eval evalDir(int keep,int rem,const int by[2],double hlim,double plim,double coslim){Eval r; if(lockv[rem])return r; double d=normv(P[keep]-P[rem]); r.ne=max(errv[keep],errv[rem]+d); if(r.ne>hlim)return r; double maxplane=0,maxang=0; int cnt=0; for(int fid:inc[rem]){if(!af[fid]||!hasv(fa[fid],rem))continue; if(fid==by[0]||fid==by[1])continue; if(hasv(fa[fid],keep))return r; F f=fa[fid]; int a=f.a,b=f.b,c=f.c; if(a==rem)a=keep; if(b==rem)b=keep; if(c==rem)c=keep; if(a==b||b==c||a==c)return r; V oldn=faceN(f); double oldl=normv(oldn); V newn=crossv(P[b]-P[a],P[c]-P[a]); double newl=normv(newn); if(oldl<=epsArea||newl<=epsArea||newl<oldl*1e-8)return r; double cs=dotv(oldn,newn)/(oldl*newl); if(cs>1)cs=1; if(cs<-1)cs=-1; if(cs<coslim)return r; V un=oldn*(1.0/oldl); double pd=fabs(dotv(un,P[keep]-P[f.a])); if(pd>plim)return r; if(duplicateAfter(keep,rem,fid,a,b,c,by[0],by[1]))return r; maxplane=max(maxplane,pd); maxang=max(maxang,1-cs); cnt++; } if(cnt==0)return r; r.ok=true; r.cost=(r.ne/(hlim+1e-300))*1.0+(maxplane/(plim+1e-300))*0.9+maxang*120.0+cnt*0.0004; return r;}
void cleanMerge(int keep,int rem){vector<int> m; m.reserve(inc[keep].size()+inc[rem].size()); for(int id:inc[keep])if(af[id]&&hasv(fa[id],keep))m.push_back(id); for(int id:inc[rem])if(af[id]&&hasv(fa[id],keep))m.push_back(id); sort(m.begin(),m.end()); m.erase(unique(m.begin(),m.end()),m.end()); inc[keep].swap(m); vector<int>().swap(inc[rem]);}
void applyCollapse(int keep,int rem,const int by[2],double ne){for(int k=0;k<2;k++)if(af[by[k]]){af[by[k]]=0;aliveF--;} for(int fid:inc[rem]){if(!af[fid]||!hasv(fa[fid],rem))continue; F&f=fa[fid]; if(f.a==rem)f.a=keep; if(f.b==rem)f.b=keep; if(f.c==rem)f.c=keep;} av[rem]=0; aliveV--; errv[keep]=ne; cleanMerge(keep,rem);} 
bool tryEdge(int u,int v,double hlim,double plim,double coslim){if(u==v||!av[u]||!av[v])return false; int by[2]={-1,-1},op[2]={-1,-1}; if(!edgeFaces(u,v,by,op))return false; if(!linkOK(u,v,op))return false; Eval a=evalDir(u,v,by,hlim,plim,coslim), b=evalDir(v,u,by,hlim,plim,coslim); if(!a.ok&&!b.ok)return false; if(b.ok&&(!a.ok||b.cost<a.cost))applyCollapse(v,u,by,b.ne); else applyCollapse(u,v,by,a.ne); return true;}
int pass(double hlim,double plim,double deg){int changed=0; double coslim=cos(deg*acos(-1.0)/180.0); for(int i=0;i<M;i++){ if(!af[i])continue; if((i&4095)==0&&elapsed()>20.1)break; F f=fa[i]; if(!av[f.a]||!av[f.b]||!av[f.c])continue; int e[3][2]={{f.a,f.b},{f.b,f.c},{f.c,f.a}}; double l[3]={n2(P[f.a]-P[f.b]),n2(P[f.b]-P[f.c]),n2(P[f.c]-P[f.a])}; int ord[3]={0,1,2}; if(l[ord[1]]<l[ord[0]])swap(ord[0],ord[1]); if(l[ord[2]]<l[ord[1]])swap(ord[1],ord[2]); if(l[ord[1]]<l[ord[0]])swap(ord[0],ord[1]); for(int kk=0;kk<3;kk++){int id=ord[kk]; if(tryEdge(e[id][0],e[id][1],hlim,plim,coslim)){changed++;break;}} } return changed;}
void outputMesh(){vector<int> id(N,-1),rev; rev.reserve(aliveV); for(int i=0;i<N;i++)if(av[i]){id[i]=rev.size();rev.push_back(i);} vector<array<int,3>> out; out.reserve(aliveF); for(int i=0;i<M;i++)if(af[i]){F&f=fa[i]; if(id[f.a]>=0&&id[f.b]>=0&&id[f.c]>=0&&f.a!=f.b&&f.b!=f.c&&f.a!=f.c)out.push_back({id[f.a],id[f.b],id[f.c]});} printf("%d %d\n",(int)rev.size(),(int)out.size()); for(int v:rev)printf("v %.17g %.17g %.17g\n",P[v].x,P[v].y,P[v].z); for(auto&t:out)printf("f %d %d %d\n",t[0]+1,t[1]+1,t[2]+1);}
int main(){T0=chrono::steady_clock::now(); readInput(); if(tryBox())return 0; if(N<=10||M<=12){outputMesh();return 0;} double base=N>200000?1.10:(N>50000?1.0:0.90); vector<array<double,3>> sch={{0.0025*base,0.0010*base,9},{0.0045*base,0.0018*base,12},{0.0075*base,0.0030*base,16},{0.0120*base,0.0048*base,20},{0.0200*base,0.0075*base,24},{0.0340*base,0.0120*base,28},{0.0500*base,0.0175*base,32}}; for(auto s:sch){if(elapsed()>19.8)break; int c=pass(diagLen*s[0],diagLen*s[1],s[2]); if(c<max(8,N/5000)&&s[0]>0.004){} } outputMesh(); return 0;}
