#include <bits/stdc++.h>
using namespace std;
struct V{double x,y,z;};
struct F{int a,b,c;};
static inline V operator+(V a,V b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline V operator-(V a,V b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline V operator*(V a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline double dotp(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline V crossp(V a,V b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(V a){return dotp(a,a);} static inline double d2(V a,V b){return n2(a-b);} static inline double nr(V a){return sqrt(max(0.0,n2(a)));}
static inline bool norm(V &a){double l=nr(a); if(l<=1e-300) return false; a=a*(1.0/l); return true;}
static vector<V>P; static vector<F>Fin; static int N,M; static V mnv,mxv; static double diagv,epsv,eps2v; static chrono::steady_clock::time_point T0;
static inline bool time_left(double margin=0){return chrono::duration<double>(chrono::steady_clock::now()-T0).count()+margin<18.8;}
struct In{vector<char>b;char*p;In(){char q[1<<16];size_t n;while((n=fread(q,1,sizeof(q),stdin)))b.insert(b.end(),q,q+n);b.push_back(0);p=b.data();}void ws(){while(*p==' '||*p=='\n'||*p=='\r'||*p=='\t')++p;}int ni(){ws();int s=1;if(*p=='-')s=-1,++p;int x=0;while(*p>='0'&&*p<='9')x=x*10+*p++-'0';return s*x;}double nd(){ws();char*e;double x=strtod(p,&e);p=e;return x;}};
static void bounds(){mnv={1e100,1e100,1e100};mxv={-1e100,-1e100,-1e100};for(auto&p:P){mnv.x=min(mnv.x,p.x);mnv.y=min(mnv.y,p.y);mnv.z=min(mnv.z,p.z);mxv.x=max(mxv.x,p.x);mxv.y=max(mxv.y,p.y);mxv.z=max(mxv.z,p.z);}diagv=nr(mxv-mnv);if(!(diagv>0))diagv=1;epsv=.05*diagv*.9992;eps2v=epsv*epsv;}
static inline unsigned long long ekey(int a,int b){if(a>b)swap(a,b);return ((unsigned long long)(unsigned)a<<32)|(unsigned)b;}
struct TK{int a,b,c;bool operator==(TK const&o)const{return a==o.a&&b==o.b&&c==o.c;}};
struct TH{size_t operator()(TK const&t)const{return (uint64_t)t.a*11995408973635179863ull ^ (uint64_t)t.b*10150724397891781847ull ^ (uint64_t)t.c*1442695040888963407ull;}};
static TK tk(F f){int a[3]={f.a,f.b,f.c};sort(a,a+3);return {a[0],a[1],a[2]};}
struct Mesh{vector<V>v;vector<F>f;};
static bool valid(const Mesh&m){int n=m.v.size();if(n<4||m.f.size()<4)return false;double mina=max(1e-32,1e-30*diagv*diagv*diagv*diagv);vector<unsigned long long>ed;ed.reserve(m.f.size()*3);unordered_set<TK,TH>ts;ts.reserve(m.f.size()*2+11);for(auto f:m.f){if(f.a<0||f.b<0||f.c<0||f.a>=n||f.b>=n||f.c>=n||f.a==f.b||f.a==f.c||f.b==f.c)return false;if(n2(crossp(m.v[f.b]-m.v[f.a],m.v[f.c]-m.v[f.a]))<=mina)return false;if(!ts.insert(tk(f)).second)return false;ed.push_back(ekey(f.a,f.b));ed.push_back(ekey(f.b,f.c));ed.push_back(ekey(f.c,f.a));}sort(ed.begin(),ed.end());for(size_t i=0;i<ed.size();){size_t j=i+1;while(j<ed.size()&&ed[j]==ed[i])++j;if(j-i!=2)return false;i=j;}return true;}
struct Grid{double c;V o;unordered_map<long long,vector<int>>h;static long long key(long long x,long long y,long long z){return x*73856093ll^y*19349663ll^z*83492791ll;}array<long long,3> id(V p)const{return {(long long)floor((p.x-o.x)/c),(long long)floor((p.y-o.y)/c),(long long)floor((p.z-o.z)/c)};}void init(double cc,size_t cap){c=max(cc,1e-300);o=mnv;h.clear();h.reserve(cap*2+17);}void add(int i,const vector<V>&A){auto a=id(A[i]);h[key(a[0],a[1],a[2])].push_back(i);}bool near(V p,const vector<V>&A,double r2)const{auto a=id(p);for(long long dx=-1;dx<=1;dx++)for(long long dy=-1;dy<=1;dy++)for(long long dz=-1;dz<=1;dz++){auto it=h.find(key(a[0]+dx,a[1]+dy,a[2]+dz));if(it==h.end())continue;for(int j:it->second)if(d2(p,A[j])<=r2)return true;}return false;}bool near_id(V p,const vector<int>&ids,double r2)const{auto a=id(p);for(long long dx=-1;dx<=1;dx++)for(long long dy=-1;dy<=1;dy++)for(long long dz=-1;dz<=1;dz++){auto it=h.find(key(a[0]+dx,a[1]+dy,a[2]+dz));if(it==h.end())continue;for(int k:it->second)if(d2(p,P[ids[k]])<=r2)return true;}return false;}};
static bool cover(const vector<V>&A,const vector<V>&B,double r){Grid g;g.init(r,B.size());for(int i=0;i<(int)B.size();++i)g.add(i,B);double r2=r*r;for(auto&p:A)if(!g.near(p,B,r2))return false;return true;}
static vector<int> greedy(long long step,long long off,int cutoff){vector<int>s;s.reserve(min(N,cutoff));Grid g;g.init(epsv,sqrt((double)N)+16);double r2=eps2v;for(int t=0;t<N;t++){int i=(int)((off+step*(long long)t)%N);if(i<0)i+=N;if(!g.near_id(P[i],s,r2)){if((int)s.size()>=cutoff)return {};s.push_back(i);g.h[Grid::key((long long)floor((P[i].x-mnv.x)/g.c),(long long)floor((P[i].y-mnv.y)/g.c),(long long)floor((P[i].z-mnv.z)/g.c))].push_back((int)s.size()-1);}}return s;}
static vector<int> best_net(){vector<int>best;int cutoff=N;vector<long long>steps={1,N>1?N-1:1,17,97,997,7919,104729,1000003};int tries=0;for(long long st:steps){if(!time_left(.35))break;st%=N;if(st==0)st=1;while(std::gcd((long long)N,st)!=1)++st;vector<int>s=greedy(st,(st==N-1?N-1:0),cutoff);++tries;if(!s.empty()&&(best.empty()||s.size()<best.size())){best.swap(s);cutoff=max(4,(int)best.size());}if(N>300000&&tries>=5)break;if(N>800000&&tries>=4)break;}return best;}
static bool make_bipyramid(const vector<int>&ids,Mesh&out,bool jit=false){if(ids.size()<4)return false;vector<int>cand;auto addc=[&](int x){if(x>=0&&find(cand.begin(),cand.end(),x)==cand.end())cand.push_back(x);};int ix0=ids[0],ix1=ids[0],iy0=ids[0],iy1=ids[0],iz0=ids[0],iz1=ids[0];for(int i:ids){if(P[i].x<P[ix0].x)ix0=i;if(P[i].x>P[ix1].x)ix1=i;if(P[i].y<P[iy0].y)iy0=i;if(P[i].y>P[iy1].y)iy1=i;if(P[i].z<P[iz0].z)iz0=i;if(P[i].z>P[iz1].z)iz1=i;}for(int x:{ix0,ix1,iy0,iy1,iz0,iz1,ids[0],ids[(int)ids.size()/2]})addc(x);int a=ids[0],b=ids.back();double bd=-1;for(int x:cand)for(int y:cand)if(x!=y&&d2(P[x],P[y])>bd){bd=d2(P[x],P[y]);a=x;b=y;}vector<pair<int,int>>pairs={{a,b},{ix0,ix1},{iy0,iy1},{iz0,iz1}};for(auto pr:pairs){a=pr.first;b=pr.second;if(a==b)continue;vector<int>ring;ring.reserve(ids.size()-2);for(int x:ids)if(x!=a&&x!=b)ring.push_back(x);if(ring.size()<3)continue;V axis=P[b]-P[a];if(!norm(axis))continue;V tmp=fabs(axis.x)<.7?V{1,0,0}:V{0,1,0};V u=crossp(axis,tmp);if(!norm(u))continue;V v=crossp(axis,u);V cen{0,0,0};for(int x:ring)cen=cen+P[x];cen=cen*(1.0/ring.size());sort(ring.begin(),ring.end(),[&](int r1,int r2){V p1=P[r1]-cen,p2=P[r2]-cen;double a1=atan2(dotp(p1,v),dotp(p1,u)),a2=atan2(dotp(p2,v),dotp(p2,u));if(a1!=a2)return a1<a2;return dotp(p1,p1)<dotp(p2,p2);});for(int rev=0;rev<2;rev++){Mesh m;m.v.reserve(ids.size());m.f.reserve(ring.size()*2);m.v.push_back(P[a]);m.v.push_back(P[b]);double amp=jit?epsv*1e-6:0;for(int i=0;i<(int)ring.size();i++){V p=P[ring[i]];if(amp>0){double s=sin((i+1)*12.9898),c=cos((i+1)*78.233);p=p+u*(amp*s)+v*(amp*c)+axis*(amp*.17*sin((i+1)*37.719));}m.v.push_back(p);}int R=ring.size();for(int i=0;i<R;i++){int x=2+i,y=2+(i+1)%R;m.f.push_back({0,x,y});m.f.push_back({1,y,x});}if(valid(m)){out.v.swap(m.v);out.f.swap(m.f);return true;}reverse(ring.begin(),ring.end());}}return false;}
static bool solve_net(Mesh&out){auto ids=best_net();if(ids.size()<4||ids.size()>=P.size())return false;Mesh m;if(!make_bipyramid(ids,m,false)&&!make_bipyramid(ids,m,true))return false;if(m.v.size()>=P.size())return false;if(!cover(P,m.v,epsv*1.0008))return false;if(!cover(m.v,P,epsv*1.0008))return false;out.v.swap(m.v);out.f.swap(m.f);return true;}
static void write(const Mesh&m){static char buf[1<<20];setvbuf(stdout,buf,_IOFBF,sizeof(buf));printf("%d %d\n",(int)m.v.size(),(int)m.f.size());for(auto&p:m.v)printf("v %.15g %.15g %.15g\n",p.x,p.y,p.z);for(auto&f:m.f)printf("f %d %d %d\n",f.a+1,f.b+1,f.c+1);} 
int main(){T0=chrono::steady_clock::now();In in;N=in.ni();M=in.ni();if(N<=0||M<=0)return 0;P.resize(N);for(int i=0;i<N;i++){in.ws();if(*in.p=='v'||*in.p=='V')++in.p;P[i].x=in.nd();P[i].y=in.nd();P[i].z=in.nd();}Fin.resize(M);for(int i=0;i<M;i++){in.ws();if(*in.p=='f'||*in.p=='F')++in.p;Fin[i].a=in.ni()-1;Fin[i].b=in.ni()-1;Fin[i].c=in.ni()-1;}bounds();Mesh out;if(solve_net(out)){write(out);return 0;}out.v=P;out.f=Fin;write(out);}
