#include <bits/stdc++.h>
using namespace std;
struct V3{double x,y,z;};
struct F3{int a,b,c;};
static inline V3 operator+(const V3&a,const V3&b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline V3 operator-(const V3&a,const V3&b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline V3 operator*(const V3&a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline V3 operator/(const V3&a,double s){return {a.x/s,a.y/s,a.z/s};}
static inline double dotp(const V3&a,const V3&b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline V3 crossp(const V3&a,const V3&b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(const V3&a){return dotp(a,a);} static inline double nrm(const V3&a){return sqrt(max(0.0,n2(a)));}
static inline V3 unit(V3 a){double l=nrm(a); return l>1e-300?a/l:V3{0,0,0};}
static vector<V3>P; static vector<F3>F; static int N,M; static V3 mnv,mxv,ctr; static double diagLen=1,tau=0,tau2=0; static chrono::steady_clock::time_point T0;
static inline double elap(){return chrono::duration<double>(chrono::steady_clock::now()-T0).count();}
struct In{vector<char>b;char*p;In(){char buf[1<<16];size_t n;while((n=fread(buf,1,sizeof(buf),stdin))>0)b.insert(b.end(),buf,buf+n);b.push_back(0);p=b.data();}inline void ws(){while(*p==' '||*p=='\n'||*p=='\r'||*p=='\t')++p;}int ni(){ws();int s=1;if(*p=='-')s=-1,++p;int x=0;while(*p>='0'&&*p<='9')x=x*10+(*p++-'0');return x*s;}double nd(){ws();char*e;double x=strtod(p,&e);p=e;return x;}char nc(){ws();return *p++;}};
static uint64_t ekey(int a,int b){if(a>b)swap(a,b);return (uint64_t)(uint32_t)a<<32|(uint32_t)b;}
static void read(){In in;N=in.ni();M=in.ni();P.resize(N);F.resize(M);mnv={1e100,1e100,1e100};mxv={-1e100,-1e100,-1e100};for(int i=0;i<N;i++){in.nc();P[i].x=in.nd();P[i].y=in.nd();P[i].z=in.nd();mnv.x=min(mnv.x,P[i].x);mnv.y=min(mnv.y,P[i].y);mnv.z=min(mnv.z,P[i].z);mxv.x=max(mxv.x,P[i].x);mxv.y=max(mxv.y,P[i].y);mxv.z=max(mxv.z,P[i].z);}for(int i=0;i<M;i++){in.nc();F[i].a=in.ni()-1;F[i].b=in.ni()-1;F[i].c=in.ni()-1;}ctr=(mnv+mxv)*0.5;diagLen=nrm(mxv-mnv);if(!(diagLen>0))diagLen=1;tau=0.05*diagLen*0.999; tau2=tau*tau;}
static double orientSignOrig(){long double s=0;int st=max(1,M/200000),cnt=0;for(int i=0;i<M;i+=st){auto f=F[i];V3 cr=crossp(P[f.b]-P[f.a],P[f.c]-P[f.a]);V3 cc=(P[f.a]+P[f.b]+P[f.c])/3.0;s+=dotp(cr,cc-ctr); if(++cnt>200000)break;}return s>=0?1.0:-1.0;}
static void addFace(vector<V3>&V, vector<F3>&A, int a,int b,int c, const V3&C, double sg){F3 f{a,b,c};V3 cr=crossp(V[b]-V[a],V[c]-V[a]);V3 cc=(V[a]+V[b]+V[c])/3.0;if(dotp(cr,cc-C)*sg<0)swap(f.b,f.c);A.push_back(f);} 
static bool validMesh(const vector<V3>&V,const vector<F3>&A){if(V.empty()||A.empty()||V.size()>(size_t)N)return false;double eps=max(1e-30,1e-24*diagLen*diagLen);vector<uint64_t>ed;ed.reserve(A.size()*3);vector<array<int,3>>tk;tk.reserve(A.size());for(auto f:A){if(f.a<0||f.b<0||f.c<0||f.a>=(int)V.size()||f.b>=(int)V.size()||f.c>=(int)V.size())return false;if(f.a==f.b||f.a==f.c||f.b==f.c)return false;if(n2(crossp(V[f.b]-V[f.a],V[f.c]-V[f.a]))<=eps)return false;ed.push_back(ekey(f.a,f.b));ed.push_back(ekey(f.b,f.c));ed.push_back(ekey(f.c,f.a));array<int,3>x{f.a,f.b,f.c};sort(x.begin(),x.end());tk.push_back(x);}sort(tk.begin(),tk.end());if(adjacent_find(tk.begin(),tk.end())!=tk.end())return false;sort(ed.begin(),ed.end());for(size_t i=0;i<ed.size();){size_t j=i+1;while(j<ed.size()&&ed[j]==ed[i])++j;if(j-i!=2)return false;i=j;}return true;}
static void writeMesh(const vector<V3>&V,const vector<F3>&A){string out;out.reserve(V.size()*42+A.size()*24+64);char line[128];auto add=[&](const char*s,int l){if(out.size()+l>1<<20){fwrite(out.data(),1,out.size(),stdout);out.clear();}out.append(s,s+l);};int l=snprintf(line,sizeof(line),"%d %d\n",(int)V.size(),(int)A.size());add(line,l);for(auto p:V){l=snprintf(line,sizeof(line),"v %.15g %.15g %.15g\n",p.x,p.y,p.z);add(line,l);}for(auto f:A){l=snprintf(line,sizeof(line),"f %d %d %d\n",f.a+1,f.b+1,f.c+1);add(line,l);}if(!out.empty())fwrite(out.data(),1,out.size(),stdout);} 
static void writeOriginal(){writeMesh(P,F);} 
// rendering / SSIM evaluator clone (reduced resolution)
struct Maps{int R=0,PIX=0;vector<float>d,n;};
static inline void proj(const V3&p,int view,int R,double&u,double&v,double&z){double D=2.5,f=800.0*R/1024.0,c=0.5*R,sx,sy;if(view==0){sx=p.y;sy=p.z;z=D-p.x;}else if(view==1){sx=-p.y;sy=p.z;z=D+p.x;}else if(view==2){sx=-p.x;sy=p.z;z=D-p.y;}else if(view==3){sx=p.x;sy=p.z;z=D+p.y;}else if(view==4){sx=p.x;sy=p.y;z=D-p.z;}else{sx=-p.x;sy=p.y;z=D+p.z;}u=f*sx/z+c;v=f*sy/z+c;}
static void render(const vector<V3>&V,const vector<F3>&A,Maps&m,int R){int PIX=R*R;m.R=R;m.PIX=PIX;m.d.assign((size_t)6*PIX,255.f);m.n.assign((size_t)6*PIX*3,127.5f);int nv=V.size();vector<float>U(nv),W(nv),Z(nv);vector<V3>FN(A.size());for(size_t i=0;i<A.size();i++){auto t=A[i];FN[i]=unit(crossp(V[t.b]-V[t.a],V[t.c]-V[t.a]));}for(int view=0;view<6;view++){for(int i=0;i<nv;i++){double u,v,z;proj(V[i],view,R,u,v,z);U[i]=u;W[i]=v;Z[i]=z;}float*zbuf=m.d.data()+(size_t)view*PIX;float*nbuf=m.n.data()+(size_t)view*PIX*3;for(size_t ti=0;ti<A.size();ti++){auto t=A[ti];int a=t.a,b=t.b,c=t.c;float x0=U[a],y0=W[a],z0=Z[a],x1=U[b],y1=W[b],z1=Z[b],x2=U[c],y2=W[c],z2=Z[c];if(!(z0>0&&z1>0&&z2>0))continue;int X0=max(0,(int)floor(min(x0,min(x1,x2))-.5f)),X1=min(R-1,(int)ceil(max(x0,max(x1,x2))+.5f));int Y0=max(0,(int)floor(min(y0,min(y1,y2))-.5f)),Y1=min(R-1,(int)ceil(max(y0,max(y1,y2))+.5f));if(X0>X1||Y0>Y1)continue;float den=(y1-y2)*(x0-x2)+(x2-x1)*(y0-y2);if(fabs(den)<1e-20f)continue;float inv=1.f/den;V3 nn=FN[ti];float nr=(nn.x+1)*127.5f,ng=(nn.y+1)*127.5f,nb=(nn.z+1)*127.5f;for(int yy=Y0;yy<=Y1;yy++){float py=yy+.5f;int row=yy*R;for(int xx=X0;xx<=X1;xx++){float px=xx+.5f;float w0=((y1-y2)*(px-x2)+(x2-x1)*(py-y2))*inv,w1=((y2-y0)*(px-x2)+(x0-x2)*(py-y2))*inv,w2=1.f-w0-w1;if(w0<-1e-6f||w1<-1e-6f||w2<-1e-6f)continue;float dep=1.f/(w0/z0+w1/z1+w2/z2);int id=row+xx;if(dep<zbuf[id]){zbuf[id]=dep;float*q=nbuf+id*3;q[0]=nr;q[1]=ng;q[2]=nb;}}}}}}
static inline double rsum(const vector<double>&I,int W,int x0,int y0,int x1,int y1){return I[(size_t)y1*W+x1]-I[(size_t)y0*W+x1]-I[(size_t)y1*W+x0]+I[(size_t)y0*W+x0];}
static double ssimCh(const float*X,int sx,const float*Y,int sy,const float*dX,const float*dY,int R,vector<double>&IX,vector<double>&IY,vector<double>&IX2,vector<double>&IY2,vector<double>&IXY){int W=R+1;size_t SZ=(size_t)W*W;fill(IX.begin(),IX.begin()+SZ,0);fill(IY.begin(),IY.begin()+SZ,0);fill(IX2.begin(),IX2.begin()+SZ,0);fill(IY2.begin(),IY2.begin()+SZ,0);fill(IXY.begin(),IXY.begin()+SZ,0);for(int y=1;y<=R;y++){double ax=0,ay=0,ax2=0,ay2=0,axy=0;int row=(y-1)*R;for(int x=1;x<=R;x++){int p=row+x-1;double vx=X[(size_t)p*sx],vy=Y[(size_t)p*sy];ax+=vx;ay+=vy;ax2+=vx*vx;ay2+=vy*vy;axy+=vx*vy;size_t id=(size_t)y*W+x,up=(size_t)(y-1)*W+x;IX[id]=IX[up]+ax;IY[id]=IY[up]+ay;IX2[id]=IX2[up]+ax2;IY2[id]=IY2[up]+ay2;IXY[id]=IXY[up]+axy;}}const int rad=5,area=121;const double c1=6.5025,c2=58.5225;long long cnt=0;long double acc=0;for(int y=rad;y<R-rad;y++){int row=y*R;for(int x=rad;x<R-rad;x++){int p=row+x;if(!(dX[p]<254.f||dY[p]<254.f))continue;int x0=x-rad,y0=y-rad,x1=x+rad+1,y1=y+rad+1;double sxv=rsum(IX,W,x0,y0,x1,y1),syv=rsum(IY,W,x0,y0,x1,y1),sx2=rsum(IX2,W,x0,y0,x1,y1),sy2=rsum(IY2,W,x0,y0,x1,y1),sxy=rsum(IXY,W,x0,y0,x1,y1);double mx=sxv/area,my=syv/area;double vx=max(0.0,sx2/area-mx*mx),vy=max(0.0,sy2/area-my*my),cov=sxy/area-mx*my;double den=(mx*mx+my*my+c1)*(vx+vy+c2);acc+=den?((2*mx*my+c1)*(2*cov+c2)/den):1.0;++cnt;}}return cnt?(double)(acc/cnt):1.0;}
static double ssim(const Maps&A,const Maps&B){int R=A.R,PIX=R*R,W=R+1;vector<double>IX((size_t)W*W),IY((size_t)W*W),IX2((size_t)W*W),IY2((size_t)W*W),IXY((size_t)W*W);double total=0;for(int v=0;v<6;v++){const float*ad=A.d.data()+(size_t)v*PIX;const float*bd=B.d.data()+(size_t)v*PIX;double ns=0;for(int c=0;c<3;c++){const float*an=A.n.data()+(size_t)v*PIX*3+c;const float*bn=B.n.data()+(size_t)v*PIX*3+c;ns+=ssimCh(an,3,bn,3,ad,bd,R,IX,IY,IX2,IY2,IXY);}ns/=3.0;double ds=ssimCh(ad,1,bd,1,ad,bd,R,IX,IY,IX2,IY2,IXY);total+=0.5*(ns+ds);}return total/6.0;}
static Maps ORIG256,ORIG512; static bool H256=false,H512=false;
static double visualScore(const vector<V3>&V,const vector<F3>&A,int R){Maps cand;if(R>=512){if(!H512){render(P,F,ORIG512,512);H512=true;}render(V,A,cand,512);return ssim(ORIG512,cand);}else{if(!H256){render(P,F,ORIG256,256);H256=true;}render(V,A,cand,256);return ssim(ORIG256,cand);}}
// sorted spatial hash for analytic generated-vertex -> original-vertex Hausdorff direction
struct HashPts{double cell;vector<pair<unsigned long long,int>>h;static unsigned long long key(int ix,int iy,int iz){return ((uint64_t)(ix+1048576)<<42)^((uint64_t)(iy+1048576)<<21)^(uint64_t)(iz+1048576);}void build(){cell=max(1e-9,tau);h.clear();h.reserve(P.size());for(int i=0;i<N;i++){int ix=floor(P[i].x/cell),iy=floor(P[i].y/cell),iz=floor(P[i].z/cell);h.push_back({key(ix,iy,iz),i});}sort(h.begin(),h.end());}bool nearOrig(const V3&p)const{int ix=floor(p.x/cell),iy=floor(p.y/cell),iz=floor(p.z/cell);for(int dx=-1;dx<=1;dx++)for(int dy=-1;dy<=1;dy++)for(int dz=-1;dz<=1;dz++){auto k=key(ix+dx,iy+dy,iz+dz);auto r=equal_range(h.begin(),h.end(),make_pair(k,-1),[](auto&a,auto&b){return a.first<b.first;});for(auto it=r.first;it!=r.second;++it)if(n2(P[it->second]-p)<=tau2*1.0001)return true;}return false;}};static HashPts HP;static bool HPH=false;
static bool generatedNearOriginal(const vector<V3>&V){if(!HPH){HP.build();HPH=true;}for(auto&p:V)if(!HP.nearOrig(p))return false;return true;}
static double distPointSetGrid(const V3&p,const vector<V3>&V,const vector<int>&ids){double b=1e100;for(int id:ids)if(id>=0&&id<(int)V.size())b=min(b,n2(p-V[id]));return b;}
// sample / box exact simplifier
static bool tryBox(vector<V3>&OV,vector<F3>&OF){if(N>30)return false;vector<V3>V={{mxv.x,mxv.y,mxv.z},{mxv.x,mxv.y,mnv.z},{mxv.x,mnv.y,mxv.z},{mxv.x,mnv.y,mnv.z},{mnv.x,mxv.y,mxv.z},{mnv.x,mxv.y,mnv.z},{mnv.x,mnv.y,mxv.z},{mnv.x,mnv.y,mnv.z}};int t[12][3]={{0,2,3},{0,3,1},{4,5,7},{4,7,6},{0,1,5},{0,5,4},{2,6,7},{2,7,3},{0,4,6},{0,6,2},{1,3,7},{1,7,5}};vector<F3>A;for(auto &q:t)A.push_back({q[0],q[1],q[2]});if(!validMesh(V,A))return false;for(auto&p:P){double best=1e100;for(auto&q:V)best=min(best,n2(p-q));if(best>tau2*1.0001)return false;}if(!generatedNearOriginal(V))return false;OV=V;OF=A;return true;}
// ordered latitude-longitude sphere-like grid
static bool sameTriOrig(int fid,int a,int b,int c){if(fid<0||fid>=M)return false;array<int,3>x{F[fid].a,F[fid].b,F[fid].c},y{a,b,c};sort(x.begin(),x.end());sort(y.begin(),y.end());return x==y;}
static bool detectLatLong(int&R,int&V){if(N<10||M!=2*(N-2))return false;for(int v=8;v<=2048;v++){if((N-2)%v)continue;int r=(N-2)/v;if(r<3)continue;int st=max(1,v/64);bool ok=true;for(int j=0;j<v&&ok;j+=st){int a=1+j,b=1+(j+1)%v;if(!sameTriOrig(j,0,b,a))ok=false;int off=v+2*(r-1)*v+j;int c=1+(r-1)*v+j,d=1+(r-1)*v+(j+1)%v;if(ok&&!sameTriOrig(off,N-1,c,d))ok=false;}int span=max(1,(r-1)*v/256);for(int q=0;q<(r-1)*v&&ok;q+=span){int rr=q/v,j=q%v;int a=1+rr*v+j,b=1+rr*v+(j+1)%v,c=1+(rr+1)*v+j,d=1+(rr+1)*v+(j+1)%v;int fid=v+2*q;if(!sameTriOrig(fid,a,b,c)||!sameTriOrig(fid+1,b,d,c))ok=false;}if(ok){R=r;V=v;return true;}}return false;}
static int nearestInSortedCyclic(const vector<int>&s,int n,int x,int delta){int m=s.size();int pos=(int)((long long)x*m/n);int best=s[(pos%m+m)%m];int bd=1e9;for(int dd=-delta;dd<=delta;dd++){int y=s[(pos+dd)%m];if(y<0)y+=n;if(y>=n)y-=n;int d=abs(y-x);d=min(d,n-d);if(d<bd){bd=d;best=y;}}return best;}
static bool coverageLatLong(int R,int V,const vector<int>&rs,const vector<int>&ls,const vector<V3>&NV){for(int ri=0;ri<R;ri++){auto it=lower_bound(rs.begin(),rs.end(),ri);vector<int>candR;if(it!=rs.end())candR.push_back(*it);if(it!=rs.begin())candR.push_back(*prev(it));for(int j=0;j<V;j++){int lj=nearestInSortedCyclic(ls,V,j,2);int lj2=nearestInSortedCyclic(ls,V,(j+V/2)%V,0); // dummy no-op to avoid overly optimistic compiler assumptions
(void)lj2;double best=1e100;for(int rr:candR){int rid=find(rs.begin(),rs.end(),rr)-rs.begin();int lid=find(ls.begin(),ls.end(),lj)-ls.begin();int id=1+rid*(int)ls.size()+lid;best=min(best,n2(P[1+ri*V+j]-NV[id]));int lid2=(lid+1)%ls.size();best=min(best,n2(P[1+ri*V+j]-NV[1+rid*(int)ls.size()+lid2]));lid2=(lid-1+(int)ls.size())%(int)ls.size();best=min(best,n2(P[1+ri*V+j]-NV[1+rid*(int)ls.size()+lid2]));}if(best>tau2*1.0001)return false;}}return true;}
static bool makeLatLong(int R,int V,int R2,int V2,vector<V3>&NV,vector<F3>&NF){if(R2<2||V2<8||R2>R||V2>V)return false;vector<int>rs,ls;for(int i=0;i<R2;i++){int r=(int)llround((double)i*(R-1)/max(1,R2-1));if(!rs.empty()&&r<=rs.back())r=rs.back()+1;if(r>=R)r=R-1;rs.push_back(r);}sort(rs.begin(),rs.end());rs.erase(unique(rs.begin(),rs.end()),rs.end());if((int)rs.size()<2)return false;R2=rs.size();for(int j=0;j<V2;j++){int l=(int)((long long)j*V/V2);if(!ls.empty()&&l==ls.back())continue;ls.push_back(l);}if((int)ls.size()<8)return false;V2=ls.size();NV.clear();NF.clear();NV.reserve(2+R2*V2);NV.push_back(P[0]);for(int r:rs)for(int l:ls)NV.push_back(P[1+r*V+l]);int bot=NV.size();NV.push_back(P[N-1]);auto id=[&](int r,int j){return 1+r*V2+((j%V2+V2)%V2);};double sg=orientSignOrig();V3 C=ctr;for(int j=0;j<V2;j++)addFace(NV,NF,0,id(0,j+1),id(0,j),C,sg);for(int r=0;r+1<R2;r++)for(int j=0;j<V2;j++){int a=id(r,j),b=id(r,j+1),c=id(r+1,j),d=id(r+1,j+1);addFace(NV,NF,a,b,c,C,sg);addFace(NV,NF,b,d,c,C,sg);}for(int j=0;j<V2;j++)addFace(NV,NF,bot,id(R2-1,j),id(R2-1,j+1),C,sg);if(!coverageLatLong(R,V,rs,ls,NV))return false;return validMesh(NV,NF);}
// ordered torus/grid with wrap in both directions
static bool faceQuadMember(int fid,int a,int b,int c,int d){return sameTriOrig(fid,a,b,c)||sameTriOrig(fid,a,b,d)||sameTriOrig(fid,a,c,d)||sameTriOrig(fid,b,c,d);} 
static bool detectTorusGrid(int&U,int&V){if(N<36||M!=2*N)return false;vector<pair<int,int>>cand;for(int v=6;(long long)v*v<=N;v++)if(N%v==0){cand.push_back({N/v,v});cand.push_back({v,N/v});}sort(cand.begin(),cand.end(),[](auto&a,auto&b){return abs(a.first-a.second)<abs(b.first-b.second);});for(auto [u,v]:cand){if(u<6||v<6||u>10000||v>10000)continue;int st=max(1,N/800),tot=0,okc=0;for(int cell=0;cell<N&&tot<800;cell+=st){int i=cell/v,j=cell%v;int ni=(i+1==u?0:i+1),nj=(j+1==v?0:j+1);int a=i*v+j,b=i*v+nj,c=ni*v+j,d=ni*v+nj;int f0=2*cell,f1=f0+1;if(f1>=M)break;if(faceQuadMember(f0,a,b,c,d)&&faceQuadMember(f1,a,b,c,d))okc++;tot++;}if(tot>100&&okc*100>=tot*98){U=u;V=v;return true;}}return false;}
static bool coverageTorus(int U,int V,const vector<int>&us,const vector<int>&vs,const vector<V3>&NV){for(int i=0;i<U;i++)for(int j=0;j<V;j++){int bu=nearestInSortedCyclic(us,U,i,2),bv=nearestInSortedCyclic(vs,V,j,2);int uid=find(us.begin(),us.end(),bu)-us.begin();int vid=find(vs.begin(),vs.end(),bv)-vs.begin();double best=1e100;for(int du=-1;du<=1;du++)for(int dv=-1;dv<=1;dv++){int uu=(uid+du+(int)us.size())%(int)us.size(),vv=(vid+dv+(int)vs.size())%(int)vs.size();best=min(best,n2(P[i*V+j]-NV[uu*(int)vs.size()+vv]));}if(best>tau2*1.0001)return false;}return true;}
static bool makeTorusSub(int U,int V,int U2,int V2,vector<V3>&NV,vector<F3>&NF,bool flip=false){if(U2<4||V2<4||U2>U||V2>V||U2*V2>=N)return false;vector<int>us,vs;for(int i=0;i<U2;i++){int x=(int)((long long)i*U/U2);if(us.empty()||x!=us.back())us.push_back(x);}for(int j=0;j<V2;j++){int x=(int)((long long)j*V/V2);if(vs.empty()||x!=vs.back())vs.push_back(x);}U2=us.size();V2=vs.size();if(U2<4||V2<4)return false;NV.clear();NF.clear();NV.reserve(U2*V2);for(int u:us)for(int v:vs)NV.push_back(P[u*V+v]);auto id=[&](int i,int j){return ((i%U2+U2)%U2)*V2+((j%V2+V2)%V2);};for(int i=0;i<U2;i++)for(int j=0;j<V2;j++){F3 f{id(i,j),id(i,j+1),id(i+1,j)};if(flip)swap(f.b,f.c);NF.push_back(f);f={id(i,j+1),id(i+1,j+1),id(i+1,j)};if(flip)swap(f.b,f.c);NF.push_back(f);}if(!coverageTorus(U,V,us,vs,NV))return false;return validMesh(NV,NF);}
// analytic ellipsoid recognizer/generator
static V3 ellPoint(const V3&C,double rx,double ry,double rz,int lat,int lon,int ring,int j){double pi=acos(-1);if(ring==0)return {C.x,C.y,C.z+rz};if(ring==lat)return {C.x,C.y,C.z-rz};double th=pi*ring/lat,ph=2*pi*j/lon;return {C.x+rx*sin(th)*cos(ph),C.y+ry*sin(th)*sin(ph),C.z+rz*cos(th)};}
static bool ellCoverage(const V3&C,double rx,double ry,double rz,int lat,int lon,const vector<V3>&V){double pi=acos(-1);for(const auto&p:P){double x=(p.x-C.x)/rx,y=(p.y-C.y)/ry,z=(p.z-C.z)/rz;double rr=sqrt(x*x+y*y+z*z);if(rr<1e-12)return false;double th=acos(max(-1.0,min(1.0,z/rr))),ph=atan2(y,x);if(ph<0)ph+=2*pi;int ri=(int)llround(th/pi*lat);ri=max(0,min(lat,ri));double best=1e100;if(ri==0)best=n2(p-V[0]);else if(ri==lat)best=n2(p-V.back());else{int jj=(int)llround(ph/(2*pi)*lon);for(int dr=-1;dr<=1;dr++)for(int dj=-1;dj<=1;dj++){int r=max(1,min(lat-1,ri+dr));int j=(jj+dj)%lon;if(j<0)j+=lon;int id=1+(r-1)*lon+j;best=min(best,n2(p-V[id]));}}if(best>tau2*1.0001)return false;}return true;}
static bool makeEllipsoid(const V3&C,double rx,double ry,double rz,int lat,int lon,vector<V3>&V,vector<F3>&A){if(lat<4||lon<8||2+(lat-1)*lon>N)return false;V.clear();A.clear();V.reserve(2+(lat-1)*lon);V.push_back(ellPoint(C,rx,ry,rz,lat,lon,0,0));for(int r=1;r<lat;r++)for(int j=0;j<lon;j++)V.push_back(ellPoint(C,rx,ry,rz,lat,lon,r,j));int bot=V.size();V.push_back(ellPoint(C,rx,ry,rz,lat,lon,lat,0));auto id=[&](int r,int j){return 1+(r-1)*lon+((j%lon+lon)%lon);};double sg=orientSignOrig();for(int j=0;j<lon;j++)addFace(V,A,0,id(1,j+1),id(1,j),C,sg);for(int r=1;r<lat-1;r++)for(int j=0;j<lon;j++){int a=id(r,j),b=id(r,j+1),c=id(r+1,j),d=id(r+1,j+1);addFace(V,A,a,b,c,C,sg);addFace(V,A,b,d,c,C,sg);}for(int j=0;j<lon;j++)addFace(V,A,bot,id(lat-1,j),id(lat-1,j+1),C,sg);if(!validMesh(V,A))return false;if(!ellCoverage(C,rx,ry,rz,lat,lon,V))return false;if(!generatedNearOriginal(V))return false;return true;}
static bool tryEllipsoid(vector<V3>&OV,vector<F3>&OF){if(N<500)return false;V3 C=ctr;double rx=(mxv.x-mnv.x)/2,ry=(mxv.y-mnv.y)/2,rz=(mxv.z-mnv.z)/2;if(rx<=1e-9||ry<=1e-9||rz<=1e-9)return false;double rms=0,mxerr=0;int cnt=0,st=max(1,N/250000);for(int i=0;i<N;i+=st){double x=(P[i].x-C.x)/rx,y=(P[i].y-C.y)/ry,z=(P[i].z-C.z)/rz;double e=fabs(sqrt(x*x+y*y+z*z)-1);rms+=e*e;mxerr=max(mxerr,e);cnt++;}rms=sqrt(rms/max(1,cnt));if(rms>(N<5000?.012:.008)||mxerr>(N<5000?.055:.035))return false;vector<pair<int,int>>cand;for(int lon:{12,16,20,24,28,32,36,40,48,56,64,80,96})for(int lat:{6,8,10,12,14,16,18,20,24,28,32,40})cand.push_back({2+(lat-1)*lon,lat*1000+lon});sort(cand.begin(),cand.end());int R=(N<50000?512:256);double need=(N<50000?.904:.918);vector<V3>V;vector<F3>A;for(auto pr:cand){if(elap()>17.5)break;int lat=pr.second/1000,lon=pr.second%1000;if(!makeEllipsoid(C,rx,ry,rz,lat,lon,V,A))continue;double sc=visualScore(V,A,R);if(sc>=need){OV=V;OF=A;return true;}}return false;}
// analytic torus recognizer
static inline void coordAxis(const V3&p,int ax,double&t,double&u,double&v){if(ax==0){t=p.x;u=p.y;v=p.z;}else if(ax==1){t=p.y;u=p.x;v=p.z;}else{t=p.z;u=p.x;v=p.y;}}
static inline V3 makeAxis(int ax,double t,double u,double v){if(ax==0)return {t,u,v};if(ax==1)return {u,t,v};return {u,v,t};}
struct TorFit{bool ok=false;int ax=2;double ct,cu,cv,R,r,rms,mxe;};
static TorFit fitTorusAxis(int ax){TorFit f;f.ax=ax;if(N<500)return f;double mint=1e100,maxt=-1e100,minu=1e100,maxu=-1e100,minv=1e100,maxv=-1e100;for(auto&p:P){double t,u,v;coordAxis(p,ax,t,u,v);mint=min(mint,t);maxt=max(maxt,t);minu=min(minu,u);maxu=max(maxu,u);minv=min(minv,v);maxv=max(maxv,v);}f.ct=(mint+maxt)/2;f.cu=(minu+maxu)/2;f.cv=(minv+maxv)/2;double minrho=1e100,maxrho=0;for(auto&p:P){double t,u,v;coordAxis(p,ax,t,u,v);double rho=hypot(u-f.cu,v-f.cv);minrho=min(minrho,rho);maxrho=max(maxrho,rho);}f.R=(minrho+maxrho)/2;double r1=(maxrho-minrho)/2,r2=(maxt-mint)/2;f.r=(r1+r2)/2;if(!(f.R>f.r*1.25&&f.r>1e-9))return f;if(fabs(r1-r2)>f.r*.35)return f;int st=max(1,N/250000),cnt=0;double ss=0,me=0;for(int i=0;i<N;i+=st){double t,u,v;coordAxis(P[i],ax,t,u,v);double rho=hypot(u-f.cu,v-f.cv);double e=fabs(hypot(rho-f.R,t-f.ct)-f.r)/f.r;ss+=e*e;me=max(me,e);cnt++;}f.rms=sqrt(ss/max(1,cnt));f.mxe=me;if(f.rms>(N<5000?.025:.018)||f.mxe>(N<5000?.11:.075))return f;f.ok=true;return f;}
static V3 torPt(const TorFit&f,int U,int V,int i,int j){double pi=acos(-1),th=2*pi*i/U,ph=2*pi*j/V;double rho=f.R+f.r*cos(ph);return makeAxis(f.ax,f.ct+f.r*sin(ph),f.cu+rho*cos(th),f.cv+rho*sin(th));}
static bool torCoverage(const TorFit&f,int U,int V,const vector<V3>&VV){double pi=acos(-1);for(auto&p:P){double t,u,v;coordAxis(p,f.ax,t,u,v);double th=atan2(v-f.cv,u-f.cu);if(th<0)th+=2*pi;double rho=hypot(u-f.cu,v-f.cv);double ph=atan2(t-f.ct,rho-f.R);if(ph<0)ph+=2*pi;int ii=llround(th/(2*pi)*U),jj=llround(ph/(2*pi)*V);double best=1e100;for(int di=-1;di<=1;di++)for(int dj=-1;dj<=1;dj++){int a=(ii+di)%U;if(a<0)a+=U;int b=(jj+dj)%V;if(b<0)b+=V;best=min(best,n2(p-VV[a*V+b]));}if(best>tau2*1.0001)return false;}return true;}
static bool makeTorusAnalytic(const TorFit&f,int U,int V,vector<V3>&VV,vector<F3>&A,bool flip=false){if(U<8||V<6||U*V>N)return false;VV.clear();A.clear();VV.reserve(U*V);for(int i=0;i<U;i++)for(int j=0;j<V;j++)VV.push_back(torPt(f,U,V,i,j));auto id=[&](int i,int j){return ((i%U+U)%U)*V+((j%V+V)%V);};for(int i=0;i<U;i++)for(int j=0;j<V;j++){F3 q{id(i,j),id(i+1,j),id(i+1,j+1)};if(flip)swap(q.b,q.c);A.push_back(q);q={id(i,j),id(i+1,j+1),id(i,j+1)};if(flip)swap(q.b,q.c);A.push_back(q);}if(!validMesh(VV,A))return false;if(!torCoverage(f,U,V,VV))return false;if(!generatedNearOriginal(VV))return false;return true;}
static bool tryTorusAnalytic(vector<V3>&OV,vector<F3>&OF){TorFit best;for(int ax=0;ax<3;ax++){auto f=fitTorusAxis(ax);if(f.ok&&(!best.ok||f.rms<best.rms))best=f;}if(!best.ok)return false;vector<pair<int,int>>cand;for(int u:{24,28,32,36,40,48,56,64,72,80,96,112,128})for(int v:{8,10,12,14,16,18,20,24,28,32})cand.push_back({u*v,u*1000+v});sort(cand.begin(),cand.end());int R=(N<60000?512:256);double need=(N<60000?.904:.918);vector<V3>V;vector<F3>A,A2;for(auto pr:cand){if(elap()>17.5)break;int u=pr.second/1000,v=pr.second%1000;if(!makeTorusAnalytic(best,u,v,V,A,false))continue;double s1=visualScore(V,A,R);if(s1<need){if(makeTorusAnalytic(best,u,v,V,A2,true)){double s2=visualScore(V,A2,R);if(s2>s1){A.swap(A2);s1=s2;}}}if(s1>=need){OV=V;OF=A;return true;}}return false;}
// frustum/cylinder/cone of revolution around axis, with caps
struct FrFit{bool ok=false;int ax=2;double t0,t1,cu,cv,r0,r1,rms,mxe;};
static FrFit fitFrustum(int ax){FrFit f;f.ax=ax;if(N<500)return f;double mint=1e100,maxt=-1e100,minu=1e100,maxu=-1e100,minv=1e100,maxv=-1e100;for(auto&p:P){double t,u,v;coordAxis(p,ax,t,u,v);mint=min(mint,t);maxt=max(maxt,t);minu=min(minu,u);maxu=max(maxu,u);minv=min(minv,v);maxv=max(maxv,v);}double len=maxt-mint;if(!(len>1e-9))return f;f.t0=mint;f.t1=maxt;f.cu=(minu+maxu)/2;f.cv=(minv+maxv)/2;double maxr=0;for(auto&p:P){double t,u,v;coordAxis(p,ax,t,u,v);maxr=max(maxr,hypot(u-f.cu,v-f.cv));}if(maxr<=1e-9||len<maxr*.25)return f;int st=max(1,N/250000);double S=0,St=0,Stt=0,Sr=0,Str=0;int cnt=0,axisCnt=0;double eps=maxr*.04;for(int i=0;i<N;i+=st){double t,u,v;coordAxis(P[i],ax,t,u,v);double r=hypot(u-f.cu,v-f.cv);if(r<eps){axisCnt++;continue;}S++;St+=t;Stt+=t*t;Sr+=r;Str+=t*r;cnt++;}if(cnt<100)return f;double den=S*Stt-St*St;if(fabs(den)<1e-20)return f;double a=(S*Str-St*Sr)/den,b=(Sr-a*St)/S;f.r0=max(0.0,a*f.t0+b);f.r1=max(0.0,a*f.t1+b);if(max(f.r0,f.r1)<.2*maxr)return f;if(min(f.r0,f.r1)<0.0)return f;double ss=0,me=0;int cc=0;for(int i=0;i<N;i+=st){double t,u,v;coordAxis(P[i],ax,t,u,v);double r=hypot(u-f.cu,v-f.cv);double nearEnd=min(fabs(t-f.t0),fabs(t-f.t1));double pred=max(0.0,a*t+b);double err;if(r<eps){err=(nearEnd<.035*len)?0:1e9;}else err=fabs(r-pred)/max(1e-9,maxr);if(err>1e8)return f;ss+=err*err;me=max(me,err);cc++;}f.rms=sqrt(ss/max(1,cc));f.mxe=me;if(f.rms>.012||f.mxe>.055)return f;f.ok=true;return f;}
static V3 frPt(const FrFit&f,double t,double r,int sides,int j){double th=2*acos(-1)*j/sides;return makeAxis(f.ax,t,f.cu+r*cos(th),f.cv+r*sin(th));}
static bool makeFrustum(const FrFit&f,int sides,int seg,vector<V3>&V,vector<F3>&A){if(sides<8||seg<1)return false;V.clear();A.clear();double Csg=orientSignOrig();V3 C=makeAxis(f.ax,(f.t0+f.t1)/2,f.cu,f.cv);bool cone0=f.r0<max(f.r0,f.r1)*.03,cone1=f.r1<max(f.r0,f.r1)*.03;if(!cone0){V.push_back(makeAxis(f.ax,f.t0,f.cu,f.cv));}int botCenter=cone0?-1:0;vector<int>ring(seg+1,-1);for(int s=0;s<=seg;s++){double a=(double)s/seg,t=f.t0+(f.t1-f.t0)*a,r=f.r0+(f.r1-f.r0)*a;if((s==0&&cone0)||(s==seg&&cone1)){ring[s]=(int)V.size();V.push_back(makeAxis(f.ax,t,f.cu,f.cv));}else{ring[s]=V.size();for(int j=0;j<sides;j++)V.push_back(frPt(f,t,r,sides,j));}}int topCenter=-1;if(!cone1){topCenter=V.size();V.push_back(makeAxis(f.ax,f.t1,f.cu,f.cv));}auto rid=[&](int s,int j){int base=ring[s];if((s==0&&cone0)||(s==seg&&cone1))return base;return base+((j%sides+sides)%sides);};for(int s=0;s<seg;s++)for(int j=0;j<sides;j++){if(s==0&&cone0){addFace(V,A,rid(0,0),rid(1,j),rid(1,j+1),C,Csg);}else if(s+1==seg&&cone1){addFace(V,A,rid(seg,0),rid(s,j+1),rid(s,j),C,Csg);}else{addFace(V,A,rid(s,j),rid(s,j+1),rid(s+1,j),C,Csg);addFace(V,A,rid(s,j+1),rid(s+1,j+1),rid(s+1,j),C,Csg);}}if(botCenter>=0){for(int j=0;j<sides;j++)addFace(V,A,botCenter,rid(0,j+1),rid(0,j),C,Csg);}if(topCenter>=0){for(int j=0;j<sides;j++)addFace(V,A,topCenter,rid(seg,j),rid(seg,j+1),C,Csg);}if(!validMesh(V,A))return false;if(!generatedNearOriginal(V))return false; // original->generated checked approximately below
return true;}
static bool tryFrustum(vector<V3>&OV,vector<F3>&OF){FrFit best;for(int ax=0;ax<3;ax++){auto f=fitFrustum(ax);if(f.ok&&(!best.ok||f.rms<best.rms))best=f;}if(!best.ok)return false;int R=(N<60000?512:256);double need=(N<60000?.912:.93);double maxr=max(best.r0,best.r1);int minSide=max(12,(int)ceil(2*acos(-1)*maxr/(tau*.95)));minSide=min(max(minSide,12),96);int minSeg=max(1,(int)ceil((best.t1-best.t0)/(tau*.95)));minSeg=min(max(minSeg,1),80);vector<pair<int,int>>cand;for(int s:{12,16,20,24,28,32,36,40,48,56,64,80,96})for(int g:{1,2,3,4,6,8,10,12,16,20,24,32,40,56,72,80})if(s>=minSide&&g>=minSeg)cand.push_back({s*(g+1)+2,s*1000+g});sort(cand.begin(),cand.end());vector<V3>V;vector<F3>A;for(auto pr:cand){if(elap()>17.5)break;int sides=pr.second/1000,seg=pr.second%1000;if(!makeFrustum(best,sides,seg,V,A))continue; // original coverage rough check
bool cov=true;for(auto&p:P){double t,u,v;coordAxis(p,best.ax,t,u,v);double a=(t-best.t0)/(best.t1-best.t0);a=max(0.0,min(1.0,a));int si=round(a*seg);double r=best.r0+(best.r1-best.r0)*((double)si/seg);double th=atan2(v-best.cv,u-best.cu);if(th<0)th+=2*acos(-1);int j=round(th/(2*acos(-1))*sides);V3 q=frPt(best,best.t0+(best.t1-best.t0)*((double)si/seg),r,sides,j);double b=n2(p-q);if(b>tau2*1.0001){ // maybe cap center
 V3 c0=makeAxis(best.ax,best.t0,best.cu,best.cv),c1=makeAxis(best.ax,best.t1,best.cu,best.cv); b=min(b,min(n2(p-c0),n2(p-c1)));}
if(b>tau2*1.0001){cov=false;break;}}
if(!cov)continue;double sc=visualScore(V,A,R);if(sc>=need){OV=V;OF=A;return true;}}return false;}
// try ordered grid reductions
static bool tryLatLong(vector<V3>&OV,vector<F3>&OF){int R,V;if(!detectLatLong(R,V))return false;vector<pair<int,int>>cand;vector<int>rs={3,4,5,6,8,10,12,14,16,18,20,24,28,32,40,48};vector<int>ls={12,16,20,24,28,32,36,40,48,56,64,80,96,128};for(int r:rs)for(int l:ls)cand.push_back({2+r*l,r*1000+l});sort(cand.begin(),cand.end());int RR=(N<80000?512:256);double need=(N<80000?.9002:.918);vector<V3>Vv;vector<F3>A;for(auto pr:cand){if(elap()>17.5)break;int r=pr.second/1000,l=pr.second%1000;if(!makeLatLong(R,V,r,l,Vv,A))continue;double sc=visualScore(Vv,A,RR);if(sc>=need){OV=Vv;OF=A;return true;}}return false;}
static bool tryTorusGrid(vector<V3>&OV,vector<F3>&OF){int U,V;if(!detectTorusGrid(U,V))return false;vector<pair<int,int>>cand;for(int v2:{6,8,10,12,14,16,18,20,24,28,32,36,40,48,56,64,80,96}){double base=(double)U/V*v2;for(double m:{0.55,0.7,0.85,1.0,1.25,1.5}){int u2=max(4,(int)llround(base*m));u2=min(u2,U);if(v2<=V)cand.push_back({u2*v2,u2*1000+v2});}}sort(cand.begin(),cand.end());cand.erase(unique(cand.begin(),cand.end()),cand.end());int RR=(N<80000?512:256);double need=(N<80000?.9002:.918);vector<V3>Vv;vector<F3>A,A2;for(auto pr:cand){if(elap()>17.5)break;int u=pr.second/1000,v=pr.second%1000;if(!makeTorusSub(U,V,u,v,Vv,A,false))continue;double sc=visualScore(Vv,A,RR);if(sc<need&&makeTorusSub(U,V,u,v,Vv,A2,true)){double s2=visualScore(Vv,A2,RR);if(s2>sc){A.swap(A2);sc=s2;}}if(sc>=need){OV=Vv;OF=A;return true;}}return false;}

// conservative endpoint-only topology-preserving fallback.  It is deliberately gated by internal SSIM.
struct EdgeFallback{
    vector<V3> Q; vector<F3> G; vector<unsigned char> av,af; vector<vector<int>> adj; vector<array<float,3>> bmn,bmx; vector<int> ver,markA,markB; int stampA=1,stampB=100000; int alive=0,aliveF=0;
    struct Node{double c;int a,b,va,vb;bool operator<(const Node&o)const{return c>o.c;}}; priority_queue<Node>pq;
    bool has(int fid,int v)const{auto f=G[fid];return f.a==v||f.b==v||f.c==v;}
    int third(int fid,int a,int b)const{auto f=G[fid];int x[3]={f.a,f.b,f.c};for(int y:x)if(y!=a&&y!=b)return y;return -1;}
    V3 fn(int fid)const{auto f=G[fid];return crossp(Q[f.b]-Q[f.a],Q[f.c]-Q[f.a]);}
    bool edgeFaces(int a,int b,int ef[2],int op[2]){int c=0;auto &la=adj[a],&lb=adj[b];auto &small=la.size()<lb.size()?la:lb;for(int fid:small){if(!af[fid])continue;if(!has(fid,a)||!has(fid,b))continue;if(c>=2)return false;ef[c]=fid;op[c]=third(fid,a,b);c++;}return c==2&&op[0]>=0&&op[1]>=0&&op[0]!=op[1];}
    bool linkOK(int a,int b,const int op[2]){if(++stampA>2000000000){fill(markA.begin(),markA.end(),0);stampA=1;}if(++stampB>2000000000){fill(markB.begin(),markB.end(),0);stampB=100000;}for(int fid:adj[a])if(af[fid]&&has(fid,a)){auto f=G[fid];int x[3]={f.a,f.b,f.c};for(int y:x)if(y!=a&&y!=b)markA[y]=stampA;}int cc=0;for(int fid:adj[b])if(af[fid]&&has(fid,b)){auto f=G[fid];int x[3]={f.a,f.b,f.c};for(int y:x){if(y==a||y==b||markA[y]!=stampA)continue;if(y!=op[0]&&y!=op[1])return false;if(markB[y]!=stampB){markB[y]=stampB;cc++;}}}return cc==2&&markB[op[0]]==stampB&&markB[op[1]]==stampB;}
    bool bboxOK(int keep,int rem){array<float,3>mn,mx;for(int k=0;k<3;k++){mn[k]=min(bmn[keep][k],bmn[rem][k]);mx[k]=max(bmx[keep][k],bmx[rem][k]);}V3 p=Q[keep];double best=0;for(int m=0;m<8;m++){double x=(m&1)?mx[0]:mn[0],y=(m&2)?mx[1]:mn[1],z=(m&4)?mx[2]:mn[2];best=max(best,(p.x-x)*(p.x-x)+(p.y-y)*(p.y-y)+(p.z-z)*(p.z-z));}return best<=tau2*1.000001;}
    bool sameFace(int fid,int a,int b,int c){array<int,3>x{G[fid].a,G[fid].b,G[fid].c},y{a,b,c};sort(x.begin(),x.end());sort(y.begin(),y.end());return x==y;}
    bool dupAfter(int self,int rem,int e0,int e1,int a,int b,int c){int p=a;if(adj[b].size()<adj[p].size())p=b;if(adj[c].size()<adj[p].size())p=c;for(int fid:adj[p]){if(!af[fid]||fid==self||fid==e0||fid==e1)continue;if(has(fid,rem))continue;if(sameFace(fid,a,b,c))return true;}return false;}
    bool canDir(int keep,int rem,const int ef[2]){if(!bboxOK(keep,rem))return false;double minArea=max(1e-30,1e-24*diagLen*diagLen), minCos=(N<8000?0.20:0.05);for(int fid:adj[rem]){if(!af[fid]||!has(fid,rem))continue;if(fid==ef[0]||fid==ef[1])continue;if(has(fid,keep))return false;auto f=G[fid];int a=f.a,b=f.b,c=f.c;if(a==rem)a=keep;if(b==rem)b=keep;if(c==rem)c=keep;if(a==b||a==c||b==c)return false;V3 old=fn(fid),nw=crossp(Q[b]-Q[a],Q[c]-Q[a]);double o=nrm(old),nn=nrm(nw);if(o<=0||nn<=0||o*nn<minArea)return false;if(dotp(old,nw)/(o*nn)<minCos)return false;if(dupAfter(fid,rem,ef[0],ef[1],a,b,c))return false;}return true;}
    void compact(int v){if(!av[v]||adj[v].size()<128)return;int good=0;for(int fid:adj[v])if(af[fid]&&has(fid,v))good++;if((int)adj[v].size()<good*3+64)return;vector<int>n;n.reserve(good);for(int fid:adj[v])if(af[fid]&&has(fid,v))n.push_back(fid);adj[v].swap(n);} 
    void push(int a,int b){if(a==b||!av[a]||!av[b])return;double d=n2(Q[a]-Q[b]); if(d>tau2*4.0001)return; pq.push({d,a,b,ver[a],ver[b]});}
    void collapse(int keep,int rem,const int ef[2]){for(int k=0;k<3;k++){bmn[keep][k]=min(bmn[keep][k],bmn[rem][k]);bmx[keep][k]=max(bmx[keep][k],bmx[rem][k]);}for(int eid=0;eid<2;eid++)if(af[ef[eid]]){af[ef[eid]]=0;aliveF--;}vector<int>lst=adj[rem];for(int fid:lst){if(!af[fid]||!has(fid,rem))continue;if(has(fid,keep)){af[fid]=0;aliveF--;continue;}auto &f=G[fid];if(f.a==rem)f.a=keep;if(f.b==rem)f.b=keep;if(f.c==rem)f.c=keep;adj[keep].push_back(fid);}av[rem]=0;alive--;ver[keep]++;ver[rem]++;adj[rem].clear();compact(keep);vector<int>nei;nei.reserve(adj[keep].size()*2);for(int fid:adj[keep])if(af[fid]&&has(fid,keep)){auto f=G[fid];int x[3]={f.a,f.b,f.c};for(int y:x)if(y!=keep&&av[y])nei.push_back(y);}sort(nei.begin(),nei.end());nei.erase(unique(nei.begin(),nei.end()),nei.end());for(int y:nei)push(keep,y);} 
    bool attempt(int a,int b){if(a==b||!av[a]||!av[b])return false;int ef[2],op[2];if(!edgeFaces(a,b,ef,op))return false;if(!linkOK(a,b,op))return false;bool ab=canDir(a,b,ef),ba=canDir(b,a,ef);if(!ab&&!ba)return false;if(ab&&ba){if(adj[a].size()<=adj[b].size())collapse(b,a,ef);else collapse(a,b,ef);}else if(ab)collapse(a,b,ef);else collapse(b,a,ef);return true;}
    bool build(double ratio, vector<V3>&OV, vector<F3>&OF){Q=P;G=F;int n=N,m=M;av.assign(n,1);af.assign(m,1);bmn.resize(n);bmx.resize(n);for(int i=0;i<n;i++){bmn[i]={(float)Q[i].x,(float)Q[i].y,(float)Q[i].z};bmx[i]=bmn[i];}vector<int>deg(n);for(auto f:G){deg[f.a]++;deg[f.b]++;deg[f.c]++;}adj.assign(n,{});for(int i=0;i<n;i++)adj[i].reserve(deg[i]+4);for(int i=0;i<m;i++){adj[G[i].a].push_back(i);adj[G[i].b].push_back(i);adj[G[i].c].push_back(i);}ver.assign(n,0);markA.assign(n,0);markB.assign(n,0);alive=n;aliveF=m;vector<uint64_t>ed;ed.reserve((size_t)m*3);for(auto f:G){ed.push_back(ekey(f.a,f.b));ed.push_back(ekey(f.b,f.c));ed.push_back(ekey(f.c,f.a));}sort(ed.begin(),ed.end());ed.erase(unique(ed.begin(),ed.end()),ed.end());for(uint64_t k:ed)push(k>>32,k&0xffffffffu);int target=max(4,(int)ceil(N*ratio));long long pops=0;while(alive>target&&!pq.empty()&&elap()<13.2){auto x=pq.top();pq.pop();int a=x.a,b=x.b;if(a==b||!av[a]||!av[b])continue;if(ver[a]!=x.va||ver[b]!=x.vb){push(a,b);continue;}attempt(a,b);if((++pops&8191)==0&&elap()>13.2)break;}vector<int>id(n,-1);OV.clear();OF.clear();OV.reserve(alive);for(int i=0;i<n;i++)if(av[i]){id[i]=OV.size();OV.push_back(Q[i]);}for(int i=0;i<m;i++)if(af[i]){auto f=G[i];if(id[f.a]>=0&&id[f.b]>=0&&id[f.c]>=0&&f.a!=f.b&&f.a!=f.c&&f.b!=f.c)OF.push_back({id[f.a],id[f.b],id[f.c]});}if(OV.size()>=P.size()||!validMesh(OV,OF))return false;int R=(N<80000?512:256);double need=(N<8000?.925:(N<80000?.915:.925));if(elap()<18.2){double sc=visualScore(OV,OF,R);if(sc>=need)return true;}return false;}
};
static bool tryEdgeFallback(vector<V3>&OV,vector<F3>&OF){if(N<300||elap()>12.5)return false;double ratios[4];int cnt=0;if(N<5000){ratios[cnt++]=.18;ratios[cnt++]=.24;}else if(N<80000){ratios[cnt++]=.13;ratios[cnt++]=.18;}else{ratios[cnt++]=.10;ratios[cnt++]=.14;}for(int i=0;i<cnt&&elap()<18.5;i++){EdgeFallback E;if(E.build(ratios[i],OV,OF))return true;}return false;}

int main(){T0=chrono::steady_clock::now();read();vector<V3>OV;vector<F3>OF; // safest exact sample/box first
 if(tryBox(OV,OF)){writeMesh(OV,OF);return 0;}
 // ordered topologies are highest confidence because output vertices are original vertices and coverage is exact.
 if(tryLatLong(OV,OF)){writeMesh(OV,OF);return 0;}
 if(tryTorusGrid(OV,OF)){writeMesh(OV,OF);return 0;}
 // analytic primitives with explicit bidirectional vertex-Hausdorff checks.
 if(tryEllipsoid(OV,OF)){writeMesh(OV,OF);return 0;}
 if(tryTorusAnalytic(OV,OF)){writeMesh(OV,OF);return 0;}
 if(tryFrustum(OV,OF)){writeMesh(OV,OF);return 0;}
 if(tryEdgeFallback(OV,OF)){writeMesh(OV,OF);return 0;}
 writeOriginal();return 0;}
