#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <numeric>
#include <queue>
#include <unordered_map>
#include <unordered_set>
#include <vector>
using namespace std;
struct Vec{double x,y,z;};
static inline Vec operator+(const Vec&a,const Vec&b){return{a.x+b.x,a.y+b.y,a.z+b.z};}
static inline Vec operator-(const Vec&a,const Vec&b){return{a.x-b.x,a.y-b.y,a.z-b.z};}
static inline Vec operator*(const Vec&a,double s){return{a.x*s,a.y*s,a.z*s};}
static inline double dotv(const Vec&a,const Vec&b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline Vec crs(const Vec&a,const Vec&b){return{a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(const Vec&a){return dotv(a,a);} static inline double nrm(const Vec&a){return sqrt(max(0.0,n2(a)));}
static inline Vec unit(Vec a){double l=nrm(a);return l>1e-300?a*(1.0/l):Vec{0,0,0};}
struct Face{int v[3];};
struct DSU{vector<int>p,s;DSU(int n=0){init(n);}void init(int n){p.resize(n);s.assign(n,1);iota(p.begin(),p.end(),0);}int f(int x){while(p[x]!=x){p[x]=p[p[x]];x=p[x];}return x;}void u(int a,int b){a=f(a);b=f(b);if(a==b)return;if(s[a]<s[b])swap(a,b);p[b]=a;s[a]+=s[b];}};
struct In{vector<char>b;char*p;In(){char t[1<<16];size_t n;while((n=fread(t,1,sizeof(t),stdin))>0)b.insert(b.end(),t,t+n);b.push_back(0);p=b.data();}inline void ws(){while(*p==' '||*p=='\n'||*p=='\r'||*p=='\t')++p;}long li(){ws();return strtol(p,&p,10);}double ld(){ws();return strtod(p,&p);}void tag(){ws();if((*p>='a'&&*p<='z')||(*p>='A'&&*p<='Z'))++p;}};
static int N,M,AFc,ActN,origComp=1;static vector<Vec>P0,P;static vector<Face>F0,F;static vector<vector<int>>Inc;static vector<unsigned char>AV,AF,Prot;static vector<double>Rad;static Vec Bmin,Bmax;static double Diag=1,Lim=1,AreaEps=1e-30;static chrono::steady_clock::time_point T0;
static inline double el(){return chrono::duration<double>(chrono::steady_clock::now()-T0).count();}
static inline unsigned long long ek(int a,int b){if(a>b)swap(a,b);return (unsigned long long)(unsigned)a<<32|(unsigned)b;}
static inline Face mf(int a,int b,int c){Face f{{a,b,c}};return f;}
static inline array<int,3> sk(int a,int b,int c){array<int,3>r{{a,b,c}};sort(r.begin(),r.end());return r;}
static inline bool hasv(const Face&f,int x){return f.v[0]==x||f.v[1]==x||f.v[2]==x;}
static inline bool hasf(int i,int x){return hasv(F[i],x);} 
static inline int thirdv(const Face&f,int a,int b){for(int k=0;k<3;k++){int x=f.v[k];if(x!=a&&x!=b)return x;}return-1;}
static inline Vec fcross(const vector<Vec>&V,const Face&f){return crs(V[f.v[1]]-V[f.v[0]],V[f.v[2]]-V[f.v[0]]);} 
static long double svol(const vector<Vec>&V,const vector<Face>&FF){long double s=0;for(const auto&f:FF)s+=(long double)dotv(V[f.v[0]],crs(V[f.v[1]],V[f.v[2]]));return s;}
static void matchSign(vector<Vec>&V,vector<Face>&FF){long double a=svol(P0,F0),b=svol(V,FF);if(a*b<0)for(auto&f:FF)swap(f.v[1],f.v[2]);}
static void read(){In in;N=(int)in.li();M=(int)in.li();P0.resize(N);Bmin={1e100,1e100,1e100};Bmax={-1e100,-1e100,-1e100};for(int i=0;i<N;i++){in.tag();P0[i].x=in.ld();P0[i].y=in.ld();P0[i].z=in.ld();Bmin.x=min(Bmin.x,P0[i].x);Bmin.y=min(Bmin.y,P0[i].y);Bmin.z=min(Bmin.z,P0[i].z);Bmax.x=max(Bmax.x,P0[i].x);Bmax.y=max(Bmax.y,P0[i].y);Bmax.z=max(Bmax.z,P0[i].z);}Diag=nrm(Bmax-Bmin);if(!(Diag>0))Diag=1;Lim=.0495*Diag;AreaEps=1e-28*Diag*Diag;F0.resize(M);for(int i=0;i<M;i++){in.tag();int a=(int)in.li()-1,b=(int)in.li()-1,c=(int)in.li()-1;F0[i]=mf(a,b,c);}P=P0;F=F0;AV.assign(N,1);AF.assign(M,1);ActN=N;AFc=M;Rad.assign(N,0);Inc.assign(N,{});vector<int>d(N);for(auto&f:F){d[f.v[0]]++;d[f.v[1]]++;d[f.v[2]]++;}for(int i=0;i<N;i++)Inc[i].reserve(d[i]);for(int i=0;i<M;i++){Inc[F[i].v[0]].push_back(i);Inc[F[i].v[1]].push_back(i);Inc[F[i].v[2]].push_back(i);}Prot.assign(N,0);auto prot=[&](int id){if(id>=0)Prot[id]=1;};int ix0=0,ix1=0,iy0=0,iy1=0,iz0=0,iz1=0;for(int i=1;i<N;i++){if(P0[i].x<P0[ix0].x)ix0=i;if(P0[i].x>P0[ix1].x)ix1=i;if(P0[i].y<P0[iy0].y)iy0=i;if(P0[i].y>P0[iy1].y)iy1=i;if(P0[i].z<P0[iz0].z)iz0=i;if(P0[i].z>P0[iz1].z)iz1=i;}prot(ix0);prot(ix1);prot(iy0);prot(iy1);prot(iz0);prot(iz1);}
static int compCnt(const vector<Vec>&V,const vector<Face>&FF){int n=V.size();DSU d(n);vector<unsigned char>u(n);for(auto&f:FF){u[f.v[0]]=u[f.v[1]]=u[f.v[2]]=1;d.u(f.v[0],f.v[1]);d.u(f.v[1],f.v[2]);}int c=0;vector<int>seen(n);for(int i=0;i<n;i++)if(u[i]){int r=d.f(i);if(!seen[r])seen[r]=1,c++;}return max(1,c);} 
static bool validate(const vector<Vec>&V,const vector<Face>&FF){if(V.empty()||FF.empty())return false;Vec mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100};vector<unsigned char>used(V.size());for(const auto&f:FF){int a=f.v[0],b=f.v[1],c=f.v[2];if(a<0||b<0||c<0||a>=int(V.size())||b>=int(V.size())||c>=int(V.size())||a==b||a==c||b==c)return false;Vec q=fcross(V,f);if(!(n2(q)>1e-32*Diag*Diag*Diag*Diag))return false;used[a]=used[b]=used[c]=1;}for(int i=0;i<(int)V.size();i++)if(used[i]){mn.x=min(mn.x,V[i].x);mn.y=min(mn.y,V[i].y);mn.z=min(mn.z,V[i].z);mx.x=max(mx.x,V[i].x);mx.y=max(mx.y,V[i].y);mx.z=max(mx.z,V[i].z);}double be=1e-8*max(1.0,Diag);if(fabs(mn.x-Bmin.x)>be||fabs(mn.y-Bmin.y)>be||fabs(mn.z-Bmin.z)>be||fabs(mx.x-Bmax.x)>be||fabs(mx.y-Bmax.y)>be||fabs(mx.z-Bmax.z)>be)return false;unordered_map<unsigned long long,int>cnt,dir;cnt.reserve(FF.size()*3+7);dir.reserve(FF.size()*3+7);for(auto&f:FF){for(int k=0;k<3;k++){int a=f.v[k],b=f.v[(k+1)%3];auto key=ek(a,b);cnt[key]++;dir[key]+=(a<b?1:-1);}}for(auto&p:cnt)if(p.second!=2||dir[p.first]!=0)return false;return compCnt(V,FF)==origComp;}
static void outputOrig(){printf("%d %d\n",N,M);for(auto&p:P0)printf("v %.17g %.17g %.17g\n",p.x,p.y,p.z);for(auto&f:F0)printf("f %d %d %d\n",f.v[0]+1,f.v[1]+1,f.v[2]+1);} 
static void outputCur(){vector<int>mp(N,-1),use(N);vector<Face>outF;outF.reserve(F.size());for(int i=0;i<(int)F.size();i++)if(AF[i]){Face f=F[i];if(!AV[f.v[0]]||!AV[f.v[1]]||!AV[f.v[2]])continue;if(f.v[0]==f.v[1]||f.v[0]==f.v[2]||f.v[1]==f.v[2])continue;if(n2(fcross(P,f))<=1e-32*Diag*Diag*Diag*Diag)continue;use[f.v[0]]=use[f.v[1]]=use[f.v[2]]=1;outF.push_back(f);}vector<Vec>outV;for(int i=0;i<N;i++)if(use[i]){mp[i]=outV.size();outV.push_back(P[i]);}for(auto&f:outF){f.v[0]=mp[f.v[0]];f.v[1]=mp[f.v[1]];f.v[2]=mp[f.v[2]];}matchSign(outV,outF);if(!validate(outV,outF)){outputOrig();return;}printf("%d %d\n",(int)outV.size(),(int)outF.size());for(auto&p:outV)printf("v %.17g %.17g %.17g\n",p.x,p.y,p.z);for(auto&f:outF)printf("f %d %d %d\n",f.v[0]+1,f.v[1]+1,f.v[2]+1);} 
static int aliveN(){return ActN;}
static bool edgeFaces(int u,int v,int by[2],int op[2]){int c=0;for(int id:Inc[u])if(id>=0&&id<(int)F.size()&&AF[id]&&hasf(id,u)&&hasf(id,v)){if(c>=2)return false;by[c]=id;op[c]=thirdv(F[id],u,v);c++;}return c==2&&op[0]>=0&&op[1]>=0&&op[0]!=op[1];}
static bool linkOK(int u,int v,const int op[2]){static vector<int>mk,seen;if((int)mk.size()!=N){mk.assign(N,0);seen.assign(N,0);}static int tok=1,tk2=100000000;tok++;tk2++;if(tok>900000000){fill(mk.begin(),mk.end(),0);tok=1;}if(tk2>1800000000){fill(seen.begin(),seen.end(),0);tk2=100000000;}for(int id:Inc[u])if(AF[id]&&hasf(id,u)){for(int k=0;k<3;k++){int x=F[id].v[k];if(x!=u&&x!=v)mk[x]=tok;}}int cc=0;for(int id:Inc[v])if(AF[id]&&hasf(id,v)){for(int k=0;k<3;k++){int x=F[id].v[k];if(x==u||x==v)continue;if(mk[x]!=tok)continue;if(x!=op[0]&&x!=op[1])return false;if(seen[x]!=tk2){seen[x]=tk2;cc++;}}}return cc==2&&seen[op[0]]==tk2&&seen[op[1]]==tk2;}
static bool dupFace(int rem,int fid,int a,int b,int c,const int by[2]){int s=a;if(Inc[b].size()<Inc[s].size())s=b;if(Inc[c].size()<Inc[s].size())s=c;auto key=sk(a,b,c);for(int id:Inc[s])if(AF[id]&&id!=fid&&id!=by[0]&&id!=by[1]&&!hasf(id,rem)){Face&f=F[id];if(sk(f.v[0],f.v[1],f.v[2])==key)return true;}return false;}
struct Par{double h,pl,cs;};struct Can{bool ok;double cost,rad;};
static Can canCol(int keep,int rem,const int by[2],const Par&p){if(Prot[rem])return{false,0,0};double rr=max(Rad[keep],Rad[rem]+nrm(P[keep]-P[rem]));if(rr>p.h)return{false,0,0};int ch=0;double worst=0,distp=0;for(int id:Inc[rem])if(AF[id]&&hasf(id,rem)){if(id==by[0]||id==by[1])continue;if(hasf(id,keep))return{false,0,0};Face f=F[id];int a=f.v[0],b=f.v[1],c=f.v[2];if(a==rem)a=keep;if(b==rem)b=keep;if(c==rem)c=keep;if(a==b||a==c||b==c)return{false,0,0};Vec old=fcross(P,f),nw=crs(P[b]-P[a],P[c]-P[a]);double lo=nrm(old),ln=nrm(nw);if(!(lo>AreaEps&&ln>AreaEps)||ln<lo*1e-9)return{false,0,0};double co=dotv(old,nw)/(lo*ln);if(co<p.cs)return{false,0,0};Vec un=old*(1.0/lo);double pd=fabs(dotv(un,P[keep]-P[f.v[0]]));if(pd>p.pl)return{false,0,0};if(dupFace(rem,id,a,b,c,by))return{false,0,0};worst=max(worst,1.0-co);distp=max(distp,pd);ch++;}if(!ch)return{false,0,0};return{true,n2(P[keep]-P[rem])/(Diag*Diag+1e-300)+20*worst+distp/(p.pl+1e-300)+0.0001*ch,rr};}
static void mergeInc(int keep,int rem){vector<int>v;v.reserve(Inc[keep].size()+Inc[rem].size());for(int id:Inc[keep])if(id>=0&&id<(int)F.size()&&AF[id]&&hasf(id,keep))v.push_back(id);for(int id:Inc[rem])if(id>=0&&id<(int)F.size()&&AF[id]&&hasf(id,keep))v.push_back(id);sort(v.begin(),v.end());v.erase(unique(v.begin(),v.end()),v.end());Inc[keep].swap(v);vector<int>().swap(Inc[rem]);}
static void doCol(int keep,int rem,const int by[2],double rr){for(int i=0;i<2;i++)if(AF[by[i]]){AF[by[i]]=0;AFc--;}for(int id:Inc[rem])if(AF[id]&&hasf(id,rem)){for(int k=0;k<3;k++)if(F[id].v[k]==rem)F[id].v[k]=keep;}AV[rem]=0;--ActN;Rad[keep]=rr;mergeInc(keep,rem);} 
static bool tryEdge(int u,int v,const Par&p){if(u==v||!AV[u]||!AV[v])return false;int by[2]={-1,-1},op[2]={-1,-1};if(!edgeFaces(u,v,by,op)||!linkOK(u,v,op))return false;Can a=canCol(u,v,by,p),b=canCol(v,u,by,p);if(!a.ok&&!b.ok)return false;if(b.ok&&(!a.ok||b.cost<a.cost))doCol(v,u,by,b.rad);else doCol(u,v,by,a.rad);return true;}
static void collapsePass(double target,double sec,const Par&p){while(aliveN()>target*N&&el()<sec){vector<unsigned long long>ks;ks.reserve((size_t)AFc*3);for(int i=0;i<(int)F.size();i++)if(AF[i]){Face&f=F[i];ks.push_back(ek(f.v[0],f.v[1]));ks.push_back(ek(f.v[1],f.v[2]));ks.push_back(ek(f.v[2],f.v[0]));if((i&262143)==0&&el()>sec-.4)break;}sort(ks.begin(),ks.end());ks.erase(unique(ks.begin(),ks.end()),ks.end());struct E{float l;unsigned long long k;};vector<E>es;es.reserve(ks.size());for(auto k:ks){int a=k>>32,b=(int)(k&0xffffffffu);if(a>=0&&b>=0&&a<N&&b<N&&AV[a]&&AV[b]&&(!Prot[a]||!Prot[b]))es.push_back({(float)n2(P[a]-P[b]),k});}sort(es.begin(),es.end(),[](const E&a,const E&b){return a.l<b.l;});int ok=0;for(auto&e:es){if(aliveN()<=target*N||el()>sec)break;int a=e.k>>32,b=(int)(e.k&0xffffffffu);if(a>=0&&b>=0&&a<N&&b<N&&AV[a]&&AV[b]&&tryEdge(a,b,p))ok++;}if(!ok)break;}}
static bool ufeq(const Face&f,int a,int b,int c){return sk(f.v[0],f.v[1],f.v[2])==sk(a,b,c);} 
static bool detectLat(int&R,int&S){if(N<10||M!=2*(N-2))return false;for(int s=8;s<=4096;s++){if((N-2)%s)continue;int r=(N-2)/s;if(r<3)continue;bool ok=true;for(int j=0;j<s&&ok;j++){int a=1+j,b=1+(j+1)%s;if(!ufeq(F0[j],0,b,a))ok=false;}for(int q=0;q<(r-1)*s&&ok;q++){int rr=q/s,j=q%s;int a=1+rr*s+j,b=1+rr*s+(j+1)%s,c=1+(rr+1)*s+j,d=1+(rr+1)*s+(j+1)%s;int id=s+2*q;if(id+1>=M||!ufeq(F0[id],a,b,c)||!ufeq(F0[id+1],b,d,c))ok=false;if((q&65535)==0&&el()>4.5)return false;}int bot=s+2*(r-1)*s;for(int j=0;j<s&&ok;j++){int c=1+(r-1)*s+j,d=1+(r-1)*s+(j+1)%s;if(bot+j>=M||!ufeq(F0[bot+j],N-1,c,d))ok=false;}if(ok){R=r;S=s;return true;}}return false;}
static bool adj3(const int a[3],int m,int&base){for(int t=0;t<3;t++)for(int s=0;s<2;s++){int x=(a[t]-s+m)%m;bool ok=true;for(int i=0;i<3;i++){int d=(a[i]-x+m)%m;if(d!=0&&d!=1){ok=false;break;}}if(ok){base=x;return true;}}return false;}
static bool cellOK(const Face&f,int S){if(S<4||N%S)return false;int U=N/S;if(U<4)return false;int r[3]={f.v[0]/S,f.v[1]/S,f.v[2]/S},c[3]={f.v[0]%S,f.v[1]%S,f.v[2]%S},br=0,bc=0;if(!adj3(r,U,br)||!adj3(c,S,bc))return false;int mask=0;for(int i=0;i<3;i++){int x=(r[i]-br+U)%U,y=(c[i]-bc+S)%S;if(x>1||y>1)return false;mask|=1<<(2*x+y);}return __builtin_popcount((unsigned)mask)==3;}
static vector<int> torusS(){vector<int>r;if(M!=2*N)return r;unordered_map<int,int>h;int st=max(1,M/200000);for(int i=0;i<M;i+=st){Face f=F0[i];for(int k=0;k<3;k++){int d=abs(f.v[k]-f.v[(k+1)%3]);d=min(d,N-d);if(d>=4&&d<=4096)h[d]++;}}vector<pair<int,int>>v;for(auto&p:h)v.push_back({p.second,p.first});sort(v.rbegin(),v.rend());auto add=[&](int s){if(s>=6&&s<=4096&&N%s==0&&find(r.begin(),r.end(),s)==r.end())r.push_back(s);};for(int i=0;i<(int)v.size()&&i<20;i++)for(int e=-2;e<=2;e++)add(v[i].second+e);for(int s=6;s<=256;s++)if(N%s==0)add(s);return r;}
static bool goodTorus(int S){if(M!=2*N||N%S)return false;for(int i=0;i<M;i++){if(!cellOK(F0[i],S))return false;if((i&131071)==0&&el()>5.5)return false;}return true;}
static void addUni(vector<int>&v,int x,int m){x=(x%m+m)%m;if(find(v.begin(),v.end(),x)==v.end())v.push_back(x);} 
static vector<int> pickCyclic(int n,int want,const vector<int>&must){vector<int>v;want=max(3,min(want,n));for(int i=0;i<want;i++)addUni(v,(long long)i*n/want,n);for(int x:must)addUni(v,x,n);sort(v.begin(),v.end());return v;}
static vector<int> pickLine(int n,int want,const vector<int>&must){vector<int>v;want=max(2,min(want,n));for(int i=0;i<want;i++)addUni(v,(long long)i*(n-1)/max(1,want-1),n);for(int x:must)addUni(v,x,n);sort(v.begin(),v.end());return v;}
static double guardTorus(int S,const vector<int>&rs,const vector<int>&cs){int U=N/S;double mx=0;for(int id=0;id<N;id++){int r=id/S,c=id%S;auto ir=lower_bound(rs.begin(),rs.end(),r)-rs.begin(),ic=lower_bound(cs.begin(),cs.end(),c)-cs.begin();double best=1e100;for(int dr=-2;dr<=2;dr++)for(int dc=-2;dc<=2;dc++){int rr=rs[(ir+dr+(int)rs.size()*4)%rs.size()],cc=cs[(ic+dc+(int)cs.size()*4)%cs.size()];best=min(best,n2(P0[id]-P0[rr*S+cc]));}mx=max(mx,best);if(mx>Lim*Lim)return sqrt(mx);}return sqrt(mx);} 
static double guardLat(int R,int S,const vector<int>&rs,const vector<int>&cs){double mx=0;auto upd=[&](int id,double&best){if(id>=0&&id<N)best=min(best,n2(P0[id]-P0[id]));};(void)upd;for(int id=0;id<N;id++){double best=1e100;if(id==0||id==N-1)best=0;else{int q=id-1,r=q/S,c=q%S;auto ir=lower_bound(rs.begin(),rs.end(),r)-rs.begin(),ic=lower_bound(cs.begin(),cs.end(),c)-cs.begin();for(int dr=-2;dr<=2;dr++){int xr=min((int)rs.size()-1,max(0,(int)ir+dr));for(int dc=-2;dc<=2;dc++){int cc=cs[(ic+dc+(int)cs.size()*4)%cs.size()];best=min(best,n2(P0[id]-P0[1+rs[xr]*S+cc]));}}best=min(best,n2(P0[id]-P0[0]));best=min(best,n2(P0[id]-P0[N-1]));}mx=max(mx,best);if(mx>Lim*Lim)return sqrt(mx);}return sqrt(mx);} 
static bool tryStructured(vector<Vec>&BV,vector<Face>&BF){vector<int>mustR,mustC;for(int i=0;i<N;i++)if(Prot[i]){}int R=0,S=0;int bestN=N;auto consider=[&](vector<Vec>V,vector<Face>FF){matchSign(V,FF);if((int)V.size()<bestN&&validate(V,FF)){bestN=V.size();BV.swap(V);BF.swap(FF);}};if(detectLat(R,S)){mustR={0,R-1};for(int i=0;i<N;i++)if(Prot[i]&&i>0&&i<N-1){int q=i-1;mustR.push_back(q/S);mustC.push_back(q%S);}vector<int>wants={8,10,12,14,16,20,24,28,32,40,48,64,80,96,128};for(int wr:wants)for(int wc:wants){if(el()>7.2)break;auto rs=pickLine(R,wr,mustR),cs=pickCyclic(S,wc,mustC);int cnt=2+(int)rs.size()*(int)cs.size();if(cnt>=bestN||cnt>=N)continue;if(guardLat(R,S,rs,cs)>Lim)continue;vector<Vec>V;vector<Face>FF;V.reserve(cnt);V.push_back(P0[0]);V.push_back(P0[N-1]);auto id=[&](int a,int b){return 2+a*(int)cs.size()+b;};for(int a=0;a<(int)rs.size();a++)for(int b=0;b<(int)cs.size();b++)V.push_back(P0[1+rs[a]*S+cs[b]]);int C=cs.size();for(int j=0;j<C;j++){int k=(j+1)%C;FF.push_back(mf(0,id(0,k),id(0,j)));}for(int i=0;i+1<(int)rs.size();i++)for(int j=0;j<C;j++){int k=(j+1)%C;int a=id(i,j),b=id(i,k),c=id(i+1,j),d=id(i+1,k);FF.push_back(mf(a,b,c));FF.push_back(mf(b,d,c));}int last=rs.size()-1;for(int j=0;j<C;j++){int k=(j+1)%C;FF.push_back(mf(1,id(last,j),id(last,k)));}consider(move(V),move(FF));}}for(int S0:torusS())if(goodTorus(S0)){int U=N/S0;mustR.clear();mustC.clear();for(int i=0;i<N;i++)if(Prot[i]){mustR.push_back(i/S0);mustC.push_back(i%S0);}vector<int>wants={8,10,12,14,16,20,24,28,32,40,48,64,80,96,128,160,192,224,256};for(int wr:wants)for(int wc:wants){if(el()>9.5)break;auto rs=pickCyclic(U,wr,mustR),cs=pickCyclic(S0,wc,mustC);int cnt=(int)rs.size()*(int)cs.size();if(cnt<8||cnt>=bestN||cnt>=N)continue;if(guardTorus(S0,rs,cs)>Lim)continue;vector<Vec>V;vector<Face>FF;V.reserve(cnt);int C=cs.size(),RR=rs.size();auto id=[&](int a,int b){return ((a%RR+RR)%RR)*C+((b%C+C)%C);};for(int a=0;a<RR;a++)for(int b=0;b<C;b++)V.push_back(P0[rs[a]*S0+cs[b]]);for(int a=0;a<RR;a++)for(int b=0;b<C;b++){int A=id(a,b),B=id(a+1,b),C1=id(a,b+1),D=id(a+1,b+1);FF.push_back(mf(A,B,C1));FF.push_back(mf(B,D,C1));}consider(move(V),move(FF));}}return bestN<N;}
int main(){T0=chrono::steady_clock::now();read();origComp=compCnt(P0,F0);vector<Vec>SV;vector<Face>SF;if(tryStructured(SV,SF)&&SV.size()<P0.size()*0.82){printf("%d %d\n",(int)SV.size(),(int)SF.size());for(auto&p:SV)printf("v %.17g %.17g %.17g\n",p.x,p.y,p.z);for(auto&f:SF)printf("f %d %d %d\n",f.v[0]+1,f.v[1]+1,f.v[2]+1);return 0;}Par p1{.020*Diag,.004*Diag,cos(25.0*acos(-1.0)/180.0)};Par p2{.036*Diag,.012*Diag,cos(55.0*acos(-1.0)/180.0)};Par p3{Lim,.026*Diag,cos(78.0*acos(-1.0)/180.0)};collapsePass(.48,13.0,p1);collapsePass(.30,17.2,p2);collapsePass(.18,20.35,p3);outputCur();return 0;}
