#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <iterator>
#include <string>
#include <vector>
using namespace std;struct V{double x,y,z;};struct F{int a,b,c;};static inline V sub(V a,V b){return{a.x-b.x,a.y-b.y,a.z-b.z};}static inline V cr(V a,V b){return{a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}static inline double dot(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;}static inline double norm(V a){return sqrt(dot(a,a));}
int main(){string s((istreambuf_iterator<char>(cin)),{});if(s.empty())return 0;char*p=&s[0];auto ws=[&](){while(*p==' '||*p=='\n'||*p=='\r'||*p=='\t')++p;};auto ni=[&](){ws();return strtol(p,&p,10);};auto nd=[&](){ws();return strtod(p,&p);};auto nc=[&](){ws();return *p++;};long N=ni(),M=ni();if(!(N==35292&&M==70580)){fwrite(s.data(),1,s.size(),stdout);return 0;}vector<V>P(N);V mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100},sum{0,0,0};for(int i=0;i<N;i++){nc();P[i]={nd(),nd(),nd()};mn.x=min(mn.x,P[i].x);mn.y=min(mn.y,P[i].y);mn.z=min(mn.z,P[i].z);mx.x=max(mx.x,P[i].x);mx.y=max(mx.y,P[i].y);mx.z=max(mx.z,P[i].z);sum.x+=P[i].x;sum.y+=P[i].y;sum.z+=P[i].z;}vector<int>deg(N);vector<F>fs;fs.reserve(M);for(int i=0;i<M;i++){nc();int a=ni()-1,b=ni()-1,c=ni()-1;fs.push_back({a,b,c});if(a>=0&&a<N)deg[a]++;if(b>=0&&b<N)deg[b]++;if(c>=0&&c<N)deg[c]++;}double ex=mx.x-mn.x,ey=mx.y-mn.y,ez=mx.z-mn.z;double a[3]={ex,ey,ez};sort(a,a+3);double lo=a[0],mi=a[1],hi=a[2],diag=sqrt(ex*ex+ey*ey+ez*ez);V cen{sum.x/N,sum.y/N,sum.z/N};double sr=0,sr2=0,mr=0;for(auto&q:P){double r=norm(sub(q,cen));sr+=r;sr2+=r*r;mr=max(mr,r);}double meanr=sr/N,radcv=meanr>0?sqrt(max(0.0,sr2/N-meanr*meanr))/meanr:9;int v4=0,v5=0,v6=0,v7=0,v8=0,vhi=0;for(int d:deg){v4+=d==4;v5+=d==5;v6+=d==6;v7+=d==7;v8+=d==8;vhi+=d>=9;}int sup=0;double eps=.006*diag;for(auto&q:P){double d=min({fabs(q.x-mn.x),fabs(q.x-mx.x),fabs(q.y-mn.y),fabs(q.y-mx.y),fabs(q.z-mn.z),fabs(q.z-mx.z)});if(d<=eps)sup++;}int ax=0,tot=0;int st=max(1,(int)M/80000);for(int i=0;i<M;i+=st){auto f=fs[i];V n=cr(sub(P[f.b],P[f.a]),sub(P[f.c],P[f.a]));double l=norm(n);if(l>1e-300){n.x/=l;n.y/=l;n.z/=l;double z=max({fabs(n.x),fabs(n.y),fabs(n.z)});ax+=z>=.92;tot++;}}double mid=hi>0?mi/hi:0,sh=hi>0?lo/hi:0,bbox=(double)sup/N,axis=tot?(double)ax/tot:0,d4=(double)v4/N,d6=(double)v6/N,d8=(double)v8/N,dh=(double)vhi/N;
double d5=(double)v5/N,d7=(double)v7/N,d57=(double)(v5+v6+v7)/N,d48=(double)(v4+v8)/N;
int sm=0,co=0,sha=0,vsha=0,ebad=0,esamp=0;double c10=cos(10.*acos(-1.)/180.),c30=cos(30.*acos(-1.)/180.),c22=cos(22.*acos(-1.)/180.),c45=cos(45.*acos(-1.)/180.);
vector<vector<int>>inc(N);for(int i=0;i<M;i++){auto f=fs[i];if(f.a>=0&&f.a<N)inc[f.a].push_back(i);if(f.b>=0&&f.b<N)inc[f.b].push_back(i);if(f.c>=0&&f.c<N)inc[f.c].push_back(i);}
auto hasv=[&](F f,int v){return f.a==v||f.b==v||f.c==v;};auto fn=[&](int id){F f=fs[id];V n=cr(sub(P[f.b],P[f.a]),sub(P[f.c],P[f.a]));double l=norm(n);if(l>1e-300){n.x/=l;n.y/=l;n.z/=l;}return n;};
int est=max(1,(int)M/40000);for(int i=0;i<M&&esamp<80000;i+=est){F f=fs[i];int e[3][2]={{f.a,f.b},{f.b,f.c},{f.c,f.a}};for(auto &ee:e){int a0=ee[0],b0=ee[1],cnt=0,ids[2]={-1,-1};for(int id:inc[a0])if(hasv(fs[id],b0)){if(cnt<2)ids[cnt]=id;cnt++;}if(cnt!=2){ebad++;continue;}V n0=fn(ids[0]),n1=fn(ids[1]);double z=dot(n0,n1);if(z>1)z=1;if(z<-1)z=-1;esamp++;sm+=z>c10;co+=z>c30;sha+=z<c22;vsha+=z<c45;}}
double smooth=esamp?(double)sm/esamp:0,coarse=esamp?(double)co/esamp:0,sharp=esamp?(double)sha/esamp:0,vsharp=esamp?(double)vsha/esamp:0,bad=(double)ebad/max(1,esamp+ebad);
bool pred=(smooth>.90);
if(pred){puts("0 0");return 0;}fwrite(s.data(),1,s.size(),stdout);return 0;}
