#include <bits/stdc++.h>
using namespace std;

struct V3{double x,y,z;};
static inline V3 operator+(const V3&a,const V3&b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline V3 operator-(const V3&a,const V3&b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline V3 operator*(const V3&a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline double dot3(const V3&a,const V3&b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline V3 cross3(const V3&a,const V3&b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(const V3&a){return dot3(a,a);} static inline double len(const V3&a){return sqrt(n2(a));}
struct F3{int a,b,c;};
int N,M; vector<V3>P,Orig; vector<F3>F; vector<unsigned char>av,af,locked; vector<double>rad,imp; vector<vector<int>>inc; double D=1,EPS=1; chrono::steady_clock::time_point t0;
static inline double secs(){return chrono::duration<double>(chrono::steady_clock::now()-t0).count();}
static inline bool has(const F3&f,int v){return f.a==v||f.b==v||f.c==v;}
static inline int third(const F3&f,int u,int v){if(f.a!=u&&f.a!=v)return f.a;if(f.b!=u&&f.b!=v)return f.b;return f.c;}
static inline unsigned long long ekey(int a,int b){if(a>b)swap(a,b);return (unsigned long long)(unsigned int)a<<32|(unsigned int)b;}
static inline array<int,3> triKey(int a,int b,int c){array<int,3>s={a,b,c};sort(s.begin(),s.end());return s;}
static inline V3 fcross(const F3&f,const vector<V3>&Q){return cross3(Q[f.b]-Q[f.a],Q[f.c]-Q[f.a]);}
void readmesh(){ios::sync_with_stdio(false);cin.tie(nullptr); if(!(cin>>N>>M)) exit(0); P.resize(N);Orig.resize(N);av.assign(N,1);af.assign(M,1);rad.assign(N,0);imp.assign(N,0); V3 mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100}; for(int i=0;i<N;i++){char ch;cin>>ch>>P[i].x>>P[i].y>>P[i].z;Orig[i]=P[i];mn.x=min(mn.x,P[i].x);mn.y=min(mn.y,P[i].y);mn.z=min(mn.z,P[i].z);mx.x=max(mx.x,P[i].x);mx.y=max(mx.y,P[i].y);mx.z=max(mx.z,P[i].z);} D=len(mx-mn);if(!(D>0))D=1;EPS=.05*D; F.resize(M); for(int i=0;i<M;i++){char ch;cin>>ch>>F[i].a>>F[i].b>>F[i].c;--F[i].a;--F[i].b;--F[i].c;}}
void rebuild(){inc.assign(N,{});vector<int>d(N,0);for(int i=0;i<(int)F.size();i++)if(af[i]){d[F[i].a]++;d[F[i].b]++;d[F[i].c]++;}for(int i=0;i<N;i++)if(av[i])inc[i].reserve(d[i]);for(int i=0;i<(int)F.size();i++)if(af[i]){inc[F[i].a].push_back(i);inc[F[i].b].push_back(i);inc[F[i].c].push_back(i);}}
void computeImportanceAndLocks(){rebuild();vector<V3>fn(F.size());vector<double>fa(F.size());for(int i=0;i<(int)F.size();i++){fn[i]=fcross(F[i],P);fa[i]=len(fn[i]);if(fa[i]>0)fn[i]=fn[i]*(1.0/fa[i]);}locked.assign(N,0);for(int v=0;v<N;v++)if(av[v]){double worst=1.0,area=0;for(int i:inc[v])if(fa[i]>0){area+=fa[i];for(int j:inc[v])if(j>i&&fa[j]>0)worst=min(worst,dot3(fn[i],fn[j]));}double sharp=max(0.0,1.0-worst);imp[v]=.05*inc[v].size()+3.0*sharp+1e-6*area/(D*D+1e-30);if(sharp>.72||inc[v].size()<=4)locked[v]=1;}V3 mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100};for(int i=0;i<N;i++)if(av[i]){mn.x=min(mn.x,P[i].x);mn.y=min(mn.y,P[i].y);mn.z=min(mn.z,P[i].z);mx.x=max(mx.x,P[i].x);mx.y=max(mx.y,P[i].y);mx.z=max(mx.z,P[i].z);}int B=max(6,min(42,(int)sqrt((double)max(1,N))/3));auto bin=[&](double v,double a,double b){if(!(b>a))return 0;int q=(int)((v-a)/(b-a)*B);if(q<0)q=0;if(q>=B)q=B-1;return q;};for(int ax=0;ax<3;ax++){int SZ=B*B;vector<int>lo(SZ,-1),hi(SZ,-1);for(int i=0;i<N;i++)if(av[i]){double dep,u,v,ua,ub,va,vb;if(ax==0){dep=P[i].x;u=P[i].y;v=P[i].z;ua=mn.y;ub=mx.y;va=mn.z;vb=mx.z;}else if(ax==1){dep=P[i].y;u=P[i].x;v=P[i].z;ua=mn.x;ub=mx.x;va=mn.z;vb=mx.z;}else{dep=P[i].z;u=P[i].x;v=P[i].y;ua=mn.x;ub=mx.x;va=mn.y;vb=mx.y;}int id=bin(u,ua,ub)*B+bin(v,va,vb);double oldlo=(lo[id]<0?0:(ax==0?P[lo[id]].x:(ax==1?P[lo[id]].y:P[lo[id]].z)));double oldhi=(hi[id]<0?0:(ax==0?P[hi[id]].x:(ax==1?P[hi[id]].y:P[hi[id]].z)));if(lo[id]<0||dep<oldlo)lo[id]=i;if(hi[id]<0||dep>oldhi)hi[id]=i;}for(int x:lo)if(x>=0)locked[x]=1;for(int x:hi)if(x>=0)locked[x]=1;}}
bool edgeFaces(int u,int v,int ef[2],int op[2]){int c=0;if(u<0||v<0||u>=N||v>=N||!av[u]||!av[v])return false;for(int id:inc[u])if(af[id]&&has(F[id],v)){if(c>=2)return false;ef[c]=id;op[c]=third(F[id],u,v);c++;}return c==2&&op[0]>=0&&op[1]>=0&&op[0]!=op[1];}
bool linkok(int u,int v,int o0,int o1){static vector<int>mk;static int st=1;if((int)mk.size()!=N)mk.assign(N,0);if(++st==INT_MAX){fill(mk.begin(),mk.end(),0);st=1;}for(int id:inc[u])if(af[id]){int a[3]={F[id].a,F[id].b,F[id].c};for(int x:a)if(x!=u&&x!=v)mk[x]=st;}int g0=0,g1=0;for(int id:inc[v])if(af[id]){int a[3]={F[id].a,F[id].b,F[id].c};for(int x:a)if(x!=u&&x!=v&&mk[x]==st){if(x==o0)g0=1;else if(x==o1)g1=1;else return false;}}return g0&&g1;}
bool dupAfter(int keep,int rem,int s0,int s1,int a,int b,int c){auto tk=triKey(a,b,c);int small=keep;if(inc[rem].size()<inc[small].size())small=rem;for(int id:inc[small])if(af[id]&&id!=s0&&id!=s1){F3 g=F[id];if(g.a==rem)g.a=keep;if(g.b==rem)g.b=keep;if(g.c==rem)g.c=keep;if(g.a==g.b||g.a==g.c||g.b==g.c)continue;if(triKey(g.a,g.b,g.c)==tk)return true;}return false;}
struct Trial{bool ok=false;int k=-1,r=-1;double nr=0,cost=1e100;};
Trial eval(int keep,int rem,int e0,int e1,double minDot,double minArea,double planeTol,bool mayRemoveLocked){Trial t;t.k=keep;t.r=rem;if(!mayRemoveLocked&&locked[rem])return t;double nr=max(rad[keep],rad[rem]+len(P[rem]-P[keep]));if(nr>EPS*.998)return t;vector<int>ids;ids.reserve(inc[rem].size());for(int id:inc[rem])if(af[id]&&id!=e0&&id!=e1)ids.push_back(id);double maxB=0,maxP=0,areaLoss=0;for(int id:ids){F3 old=F[id],nw=old;if(nw.a==rem)nw.a=keep;if(nw.b==rem)nw.b=keep;if(nw.c==rem)nw.c=keep;if(nw.a==nw.b||nw.a==nw.c||nw.b==nw.c)return t;V3 co=fcross(old,P),cn=fcross(nw,P);double ao=len(co),an=len(cn);if(!(ao>1e-22*D*D)||!(an>1e-22*D*D))return t;double d=dot3(co,cn)/(ao*an);if(d<minDot)return t;if(an<ao*minArea)return t;V3 no=co*(1.0/ao);double pd=fabs(dot3(no,P[keep]-P[old.a]));if(pd>planeTol)return t;if(dupAfter(keep,rem,e0,e1,nw.a,nw.b,nw.c))return t;maxB=max(maxB,1.0-d);maxP=max(maxP,pd);areaLoss=max(areaLoss,max(0.0,1.0-an/ao));}t.ok=true;t.nr=nr;t.cost=nr/EPS+.15*locked[keep]+2.0*imp[rem]+15.0*maxB+1.8*maxP/(EPS+1e-30)+.25*areaLoss+.002*ids.size();return t;}
bool collapse(int u,int v,double minDot,double minArea,double planeTol,bool mayRemoveLocked){if(u==v||!av[u]||!av[v])return false;int ef[2]={-1,-1},op[2]={-1,-1};if(!edgeFaces(u,v,ef,op))return false;if(!linkok(u,v,op[0],op[1]))return false;Trial a=eval(u,v,ef[0],ef[1],minDot,minArea,planeTol,mayRemoveLocked),b=eval(v,u,ef[0],ef[1],minDot,minArea,planeTol,mayRemoveLocked),t;if(a.ok&&(!b.ok||a.cost<=b.cost))t=a;else if(b.ok)t=b;else return false;int keep=t.k,rem=t.r;if(af[ef[0]])af[ef[0]]=0;if(af[ef[1]])af[ef[1]]=0;for(int id:inc[rem])if(af[id]){if(F[id].a==rem)F[id].a=keep;if(F[id].b==rem)F[id].b=keep;if(F[id].c==rem)F[id].c=keep;if(F[id].a==F[id].b||F[id].a==F[id].c||F[id].b==F[id].c)af[id]=0;else inc[keep].push_back(id);}av[rem]=0;rad[keep]=t.nr;locked[keep]=locked[keep]||locked[rem];vector<int>().swap(inc[rem]);return true;}
struct EC{int u,v;double c;};vector<EC> edges(){unordered_set<unsigned long long>seen;seen.reserve(F.size()*3+7);vector<EC>out;out.reserve(F.size()*2);for(int i=0;i<(int)F.size();i++)if(af[i]){int a[3]={F[i].a,F[i].b,F[i].c};for(int k=0;k<3;k++){int u=a[k],v=a[(k+1)%3];if(!av[u]||!av[v])continue;auto key=ekey(u,v);if(!seen.insert(key).second)continue;double L=len(P[u]-P[v]);if(L<=EPS*2.0){double lockpen=(locked[u]+locked[v])*EPS*.20;out.push_back({u,v,L+lockpen+EPS*.02*(imp[u]+imp[v])});}}}sort(out.begin(),out.end(),[](const EC&a,const EC&b){return a.c<b.c;});return out;}
void simplify(){if(N<=8)return;computeImportanceAndLocks();struct Phase{double md,ma,pt;bool rm;int sw;};vector<Phase>ph={{.999,.35,EPS*.08,false,2},{.992,.22,EPS*.15,false,2},{.975,.14,EPS*.25,false,2},{.945,.08,EPS*.38,false,2},{.905,.04,EPS*.55,false,2},{.860,.02,EPS*.75,true,1},{.800,.006,EPS*.95,true,1}};for(size_t pi=0;pi<ph.size()&&secs()<8.8;pi++){for(int sw=0;sw<ph[pi].sw&&secs()<8.8;sw++){auto es=edges();int done=0,tried=0;for(const auto&e:es){if(secs()>8.9)break;tried++;if(collapse(e.u,e.v,ph[pi].md,ph[pi].ma,ph[pi].pt,ph[pi].rm)){done++;if((done&511)==0)rebuild();}if(tried>350000&&done<16)break;}rebuild();if(done<4)break;}if(pi==1||pi==3)computeImportanceAndLocks();}}
bool finalClosedCheck(){unordered_map<unsigned long long,int>cnt;cnt.reserve(F.size()*3+1);for(int i=0;i<(int)F.size();i++)if(af[i]){F3 f=F[i];if(!av[f.a]||!av[f.b]||!av[f.c]||f.a==f.b||f.a==f.c||f.b==f.c)return false;cnt[ekey(f.a,f.b)]++;cnt[ekey(f.b,f.c)]++;cnt[ekey(f.c,f.a)]++;}for(auto&p:cnt)if(p.second!=2)return false;return true;}
void emitOriginal(){cout.setf(ios::fixed);cout<<setprecision(10);cout<<N<<" "<<M<<"\n";for(auto&p:Orig)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n";for(auto&f:F)cout<<"f "<<f.a+1<<" "<<f.b+1<<" "<<f.c+1<<"\n";}
void output(){if(!finalClosedCheck()){emitOriginal();return;}unordered_set<string>used;used.reserve(F.size()*2+1);vector<F3>of;of.reserve(F.size());vector<int>use(N,0);for(int i=0;i<(int)F.size();i++)if(af[i]){F3 f=F[i];if(!av[f.a]||!av[f.b]||!av[f.c])continue;if(f.a==f.b||f.a==f.c||f.b==f.c)continue;if(len(fcross(f,P))<=1e-22*D*D)continue;auto s=triKey(f.a,f.b,f.c);string key=to_string(s[0])+"/"+to_string(s[1])+"/"+to_string(s[2]);if(used.insert(key).second){of.push_back(f);use[f.a]=use[f.b]=use[f.c]=1;}}vector<int>id(N,-1);vector<V3>op;op.reserve(N);for(int i=0;i<N;i++)if(av[i]&&use[i]){id[i]=(int)op.size()+1;op.push_back(P[i]);}cout.setf(ios::fixed);cout<<setprecision(10);cout<<op.size()<<" "<<of.size()<<"\n";for(auto&p:op)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n";for(auto&f:of)cout<<"f "<<id[f.a]<<" "<<id[f.b]<<" "<<id[f.c]<<"\n";}
int main(){t0=chrono::steady_clock::now();readmesh();simplify();output();return 0;}
