#include <bits/stdc++.h>
using namespace std;

struct Vec3{double x,y,z;};
static inline Vec3 operator+(Vec3 a,Vec3 b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline Vec3 operator-(Vec3 a,Vec3 b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline Vec3 operator*(Vec3 a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline Vec3 operator/(Vec3 a,double s){return {a.x/s,a.y/s,a.z/s};}
static inline double dot3(Vec3 a,Vec3 b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline Vec3 cross3(Vec3 a,Vec3 b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(Vec3 a){return dot3(a,a);} static inline double norm(Vec3 a){return sqrt(max(0.0,n2(a)));}
static inline Vec3 unit(Vec3 a){double l=norm(a);return l>1e-300?a/l:Vec3{0,0,0};}
struct Face{int a,b,c; unsigned char alive; Vec3 n;};
struct Box{Vec3 mn,mx;};
struct Plan{vector<array<int,3>> tri; int recv=-1; double score=1e100; vector<int> ring, star;};
struct Cand{double score; int v,ver,pass; bool operator<(Cand const&o)const{return score>o.score;}};

static int N0,F0,aliveV,aliveF; static vector<Vec3>P; static vector<array<int,3>> Fin; static vector<Face> F; static vector<vector<int>> inc; static vector<unsigned char> alive; static vector<int> ver; static vector<Box> bbox; static double diagLen,tol,tol2,areaFloor; static Vec3 BBmn,BBmx; static clock_t T0;
static unordered_map<unsigned long long,int> edgeCnt; static unordered_set<unsigned long long> faceSet;
static inline double elapsed(){return double(clock()-T0)/CLOCKS_PER_SEC;}
static inline unsigned long long ekey(int a,int b){if(a>b)swap(a,b);return (unsigned long long)(unsigned int)a<<32 | (unsigned int)b;}
static inline unsigned long long fkey(int a,int b,int c){if(a>b)swap(a,b);if(b>c)swap(b,c);if(a>b)swap(a,b);return ((unsigned long long)(unsigned int)a*11995408973635179863ull)^((unsigned long long)(unsigned int)b*10150724397891781847ull)^((unsigned long long)(unsigned int)c*5714713534750834931ull);} 
static inline bool hasv(const Face&f,int v){return f.a==v||f.b==v||f.c==v;} static inline double area2(int a,int b,int c){return n2(cross3(P[b]-P[a],P[c]-P[a]));} static inline Vec3 fnorm(int a,int b,int c){return unit(cross3(P[b]-P[a],P[c]-P[a]));}
static void eadd(int a,int b,int d){auto k=ekey(a,b);int &x=edgeCnt[k];x+=d;if(x==0)edgeCnt.erase(k);} static void fEdgeAdd(const Face&f,int d){eadd(f.a,f.b,d);eadd(f.b,f.c,d);eadd(f.c,f.a,d);} 

static vector<char> slurp(){vector<char>b;char buf[1<<16];size_t n;while((n=fread(buf,1,sizeof(buf),stdin))>0)b.insert(b.end(),buf,buf+n);b.push_back(0);return b;} static inline void sws(char*&p){while(*p==' '||*p=='\n'||*p=='\r'||*p=='\t')++p;}
static bool readInput(){auto buf=slurp();char*p=buf.data();N0=(int)strtol(p,&p,10);F0=(int)strtol(p,&p,10);if(N0<=0||F0<=0)return false;P.resize(N0);inc.assign(N0,{});alive.assign(N0,1);ver.assign(N0,0);bbox.resize(N0);F.reserve((size_t)F0+N0);Fin.reserve(F0);BBmn={1e100,1e100,1e100};BBmx={-1e100,-1e100,-1e100};for(int i=0;i<N0;i++){sws(p);if(*p=='v'||*p=='V')++p;double x=strtod(p,&p),y=strtod(p,&p),z=strtod(p,&p);P[i]={x,y,z};bbox[i]={P[i],P[i]};BBmn.x=min(BBmn.x,x);BBmn.y=min(BBmn.y,y);BBmn.z=min(BBmn.z,z);BBmx.x=max(BBmx.x,x);BBmx.y=max(BBmx.y,y);BBmx.z=max(BBmx.z,z);}edgeCnt.reserve((size_t)F0*4+100);faceSet.reserve((size_t)F0*2+100);for(int i=0;i<F0;i++){sws(p);if(*p=='f'||*p=='F')++p;int a=(int)strtol(p,&p,10)-1,b=(int)strtol(p,&p,10)-1,c=(int)strtol(p,&p,10)-1;if(a<0||b<0||c<0||a>=N0||b>=N0||c>=N0||a==b||b==c||a==c)return false;Fin.push_back({a,b,c});Face f{a,b,c,1,fnorm(a,b,c)};int id=(int)F.size();F.push_back(f);inc[a].push_back(id);inc[b].push_back(id);inc[c].push_back(id);fEdgeAdd(f,1);faceSet.insert(fkey(a,b,c));}diagLen=norm(BBmx-BBmn);if(!(diagLen>0))diagLen=1;tol=0.05*diagLen*0.992;tol2=tol*tol;areaFloor=max(1e-32,diagLen*diagLen*1e-30);aliveV=N0;aliveF=F0;return true;}

static void outputIdentity(){printf("%d %d\n",N0,F0);for(auto p:P)printf("v %.15g %.15g %.15g\n",p.x,p.y,p.z);for(auto t:Fin)printf("f %d %d %d\n",t[0]+1,t[1]+1,t[2]+1);} 

struct PGrid{Vec3 mn,mx;double cell,r2;int nx,ny,nz;vector<vector<int>> bin;const vector<Vec3>*Q=nullptr;int cl(int x,int n)const{return x<0?0:(x>=n?n-1:x);}int ix(double x)const{return cl((int)((x-mn.x)/cell),nx);}int iy(double y)const{return cl((int)((y-mn.y)/cell),ny);}int iz(double z)const{return cl((int)((z-mn.z)/cell),nz);}int key(int x,int y,int z)const{return (z*ny+y)*nx+x;}void init(const vector<Vec3>&A,double R){Q=&A;r2=R*R;mn=mx=A[0];for(auto&p:A){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);}cell=max(R,1e-12);nx=max(1,(int)((mx.x-mn.x)/cell)+1);ny=max(1,(int)((mx.y-mn.y)/cell)+1);nz=max(1,(int)((mx.z-mn.z)/cell)+1);if((long long)nx*ny*nz>1500000){nx=ny=nz=1;cell=max({mx.x-mn.x,mx.y-mn.y,mx.z-mn.z})+1;}bin.assign((size_t)nx*ny*nz,{});for(int i=0;i<(int)A.size();i++)bin[key(ix(A[i].x),iy(A[i].y),iz(A[i].z))].push_back(i);}bool hasNear(Vec3 p)const{int X=ix(p.x),Y=iy(p.y),Z=iz(p.z);for(int z=Z-1;z<=Z+1;z++)if(z>=0&&z<nz)for(int y=Y-1;y<=Y+1;y++)if(y>=0&&y<ny)for(int x=X-1;x<=X+1;x++)if(x>=0&&x<nx)for(int q:bin[key(x,y,z)])if(n2((*Q)[q]-p)<=r2)return true;return false;}};

static bool tryBoxGrid(){
    if(N0<80)return false; double eps=max(1e-10,diagLen*2e-6); int on=0; for(auto&p:P){double d=min({fabs(p.x-BBmn.x),fabs(p.x-BBmx.x),fabs(p.y-BBmn.y),fabs(p.y-BBmx.y),fabs(p.z-BBmn.z),fabs(p.z-BBmx.z)}); if(d<=eps)on++;}
    if(on<N0*995/1000)return false; double sx=BBmx.x-BBmn.x,sy=BBmx.y-BBmn.y,sz=BBmx.z-BBmn.z; if(sx<=0||sy<=0||sz<=0)return false; double step=max(tol*0.90,diagLen*1e-6); int Kx=max(1,(int)ceil(sx/step)),Ky=max(1,(int)ceil(sy/step)),Kz=max(1,(int)ceil(sz/step)); long long est=2ll*(Kx+1)*(Ky+1)+2ll*(Kx+1)*(Kz+1)+2ll*(Ky+1)*(Kz+1); if(est>=N0*75ll/100||est>N0)return false;
    vector<Vec3> Vout; vector<array<int,3>> Fout; unordered_map<unsigned long long,int> id; id.reserve((size_t)est*2+100); auto key=[&](int i,int j,int k){return ((unsigned long long)(unsigned int)i<<42)^((unsigned long long)(unsigned int)j<<21)^(unsigned int)k;}; auto coord=[&](int i,int j,int k){return Vec3{BBmn.x+sx*(double)i/Kx,BBmn.y+sy*(double)j/Ky,BBmn.z+sz*(double)k/Kz};}; auto get=[&](int i,int j,int k)->int{auto kk=key(i,j,k);auto it=id.find(kk);if(it!=id.end())return it->second;int r=(int)Vout.size();id[kk]=r;Vout.push_back(coord(i,j,k));return r;}; auto add=[&](int a,int b,int c,Vec3 out){Vec3 cr=cross3(Vout[b]-Vout[a],Vout[c]-Vout[a]); if(dot3(cr,out)<0)swap(b,c); Fout.push_back({a,b,c});};
    for(int side=0;side<2;side++){int i=side?Kx:0;Vec3 out{side?1.0:-1.0,0,0};for(int j=0;j<Ky;j++)for(int k=0;k<Kz;k++){int v00=get(i,j,k),v10=get(i,j+1,k),v01=get(i,j,k+1),v11=get(i,j+1,k+1);add(v00,v10,v11,out);add(v00,v11,v01,out);}}
    for(int side=0;side<2;side++){int j=side?Ky:0;Vec3 out{0,side?1.0:-1.0,0};for(int i=0;i<Kx;i++)for(int k=0;k<Kz;k++){int v00=get(i,j,k),v10=get(i+1,j,k),v01=get(i,j,k+1),v11=get(i+1,j,k+1);add(v00,v10,v11,out);add(v00,v11,v01,out);}}
    for(int side=0;side<2;side++){int k=side?Kz:0;Vec3 out{0,0,side?1.0:-1.0};for(int i=0;i<Kx;i++)for(int j=0;j<Ky;j++){int v00=get(i,j,k),v10=get(i+1,j,k),v01=get(i,j+1,k),v11=get(i+1,j+1,k);add(v00,v10,v11,out);add(v00,v11,v01,out);}}
    if((int)Vout.size()>=N0)return false; PGrid pg; pg.init(P,tol*1.0001); for(auto&q:Vout)if(!pg.hasNear(q))return false; auto nearGrid=[&](Vec3 p){double best=1e100; int face=0; double d[6]={fabs(p.x-BBmn.x),fabs(p.x-BBmx.x),fabs(p.y-BBmn.y),fabs(p.y-BBmx.y),fabs(p.z-BBmn.z),fabs(p.z-BBmx.z)};for(int i=1;i<6;i++)if(d[i]<d[face])face=i; int ix=(int)llround((p.x-BBmn.x)/sx*Kx),iy=(int)llround((p.y-BBmn.y)/sy*Ky),iz=(int)llround((p.z-BBmn.z)/sz*Kz);ix=max(0,min(Kx,ix));iy=max(0,min(Ky,iy));iz=max(0,min(Kz,iz)); if(face==0)ix=0; if(face==1)ix=Kx; if(face==2)iy=0; if(face==3)iy=Ky; if(face==4)iz=0; if(face==5)iz=Kz; return n2(p-coord(ix,iy,iz));}; for(auto&p:P)if(nearGrid(p)>tol2)return false;
    printf("%d %d\n",(int)Vout.size(),(int)Fout.size());for(auto&p:Vout)printf("v %.15g %.15g %.15g\n",p.x,p.y,p.z);for(auto&t:Fout)printf("f %d %d %d\n",t[0]+1,t[1]+1,t[2]+1);return true;
}

static void cleanInc(int v){if(!alive[v]){vector<int>().swap(inc[v]);return;}vector<int>r;r.reserve(inc[v].size());for(int id:inc[v])if(id>=0&&id<(int)F.size()&&F[id].alive&&hasv(F[id],v))r.push_back(id);sort(r.begin(),r.end());r.erase(unique(r.begin(),r.end()),r.end());inc[v].swap(r);} 
static bool boxWithin(int recv,Box b){Box u;u.mn={min(bbox[recv].mn.x,b.mn.x),min(bbox[recv].mn.y,b.mn.y),min(bbox[recv].mn.z,b.mn.z)};u.mx={max(bbox[recv].mx.x,b.mx.x),max(bbox[recv].mx.y,b.mx.y),max(bbox[recv].mx.z,b.mx.z)};for(int m=0;m<8;m++){Vec3 c{(m&1)?u.mx.x:u.mn.x,(m&2)?u.mx.y:u.mn.y,(m&4)?u.mx.z:u.mn.z};if(n2(c-P[recv])>tol2)return false;}return true;}
static void mergeBox(int recv,Box b){bbox[recv].mn={min(bbox[recv].mn.x,b.mn.x),min(bbox[recv].mn.y,b.mn.y),min(bbox[recv].mn.z,b.mn.z)};bbox[recv].mx={max(bbox[recv].mx.x,b.mx.x),max(bbox[recv].mx.y,b.mx.y),max(bbox[recv].mx.z,b.mx.z)};}
static bool linkCycle(int v,vector<int>&ring,vector<int>&star,Vec3&avgN,double&oldArea){if(!alive[v])return false;cleanInc(v);star=inc[v];int d=star.size();if(d<3||d>18)return false;vector<int>nodes;vector<pair<int,int>>edges;nodes.reserve(d*2);edges.reserve(d);avgN={0,0,0};oldArea=0;for(int id:star){Face&f=F[id];if(!f.alive||!hasv(f,v))return false;int x,y;if(f.a==v){x=f.b;y=f.c;}else if(f.b==v){x=f.c;y=f.a;}else{x=f.a;y=f.b;}if(!alive[x]||!alive[y]||x==y)return false;nodes.push_back(x);nodes.push_back(y);edges.push_back({x,y});Vec3 cr=cross3(P[f.b]-P[f.a],P[f.c]-P[f.a]);double ar=norm(cr);oldArea+=0.5*ar;if(ar>0)avgN=avgN+cr;}sort(nodes.begin(),nodes.end());nodes.erase(unique(nodes.begin(),nodes.end()),nodes.end());if((int)nodes.size()!=d)return false;vector<vector<int>>adj(d);auto idx=[&](int x){auto it=lower_bound(nodes.begin(),nodes.end(),x);return (it==nodes.end()||*it!=x)?-1:(int)(it-nodes.begin());};for(auto&e:edges){int a=idx(e.first),b=idx(e.second);if(a<0||b<0||a==b)return false;adj[a].push_back(b);adj[b].push_back(a);}for(auto&a:adj){sort(a.begin(),a.end());a.erase(unique(a.begin(),a.end()),a.end());if(a.size()!=2)return false;}ring.clear();ring.reserve(d);int cur=0,pre=-1;for(int k=0;k<d;k++){ring.push_back(nodes[cur]);int nx=(adj[cur][0]==pre?adj[cur][1]:adj[cur][0]);pre=cur;cur=nx;}if(cur!=0)return false;avgN=unit(avgN);if(n2(avgN)<0.5)return false;Vec3 cen{0,0,0};for(int x:ring)cen=cen+P[x];cen=cen*(1.0/d);Vec3 poly{0,0,0};for(int i=0;i<d;i++)poly=poly+cross3(P[ring[i]]-cen,P[ring[(i+1)%d]]-cen);if(dot3(poly,avgN)<0)reverse(ring.begin(),ring.end());return true;}
static bool pointInTri2(double px,double py,double ax,double ay,double bx,double by,double cx,double cy){double c1=(bx-ax)*(py-ay)-(by-ay)*(px-ax),c2=(cx-bx)*(py-by)-(cy-by)*(px-bx),c3=(ax-cx)*(py-cy)-(ay-cy)*(px-cx);return c1>=-1e-12&&c2>=-1e-12&&c3>=-1e-12;}
static bool triangulateRing(const vector<int>&ring,Vec3 n,vector<array<int,3>>&tri){int m=ring.size();tri.clear();if(m<3)return false;Vec3 u=cross3(n,{1,0,0});if(n2(u)<1e-20)u=cross3(n,{0,1,0});u=unit(u);Vec3 v=cross3(n,u);vector<double>x(m),y(m);Vec3 cen{0,0,0};for(int id:ring)cen=cen+P[id];cen=cen*(1.0/m);for(int i=0;i<m;i++){Vec3 q=P[ring[i]]-cen;x[i]=dot3(q,u);y[i]=dot3(q,v);}double A=0;for(int i=0;i<m;i++){int j=(i+1)%m;A+=x[i]*y[j]-y[i]*x[j];}vector<int>idx(m);iota(idx.begin(),idx.end(),0);if(A<0)reverse(idx.begin(),idx.end());int guard=0;while(idx.size()>3&&guard++<m*m){int L=idx.size();int best=-1;double ba=-1;for(int ii=0;ii<L;ii++){int ip=idx[(ii+L-1)%L],ic=idx[ii],in=idx[(ii+1)%L];double cr=(x[ic]-x[ip])*(y[in]-y[ip])-(y[ic]-y[ip])*(x[in]-x[ip]);if(cr<=1e-15)continue;bool inside=false;for(int jj=0;jj<L&&!inside;jj++){int t=idx[jj];if(t==ip||t==ic||t==in)continue;if(pointInTri2(x[t],y[t],x[ip],y[ip],x[ic],y[ic],x[in],y[in]))inside=true;}if(inside)continue;if(cr>ba){ba=cr;best=ii;}}if(best<0)return false;int L2=idx.size();int ip=idx[(best+L2-1)%L2],ic=idx[best],in=idx[(best+1)%L2];tri.push_back({ring[ip],ring[ic],ring[in]});idx.erase(idx.begin()+best);}if(idx.size()==3)tri.push_back({ring[idx[0]],ring[idx[1]],ring[idx[2]]});return (int)tri.size()==m-2;}
static bool localEdgesOK(const vector<int>&star,const vector<array<int,3>>&tri){unordered_map<unsigned long long,int>rem,add;rem.reserve(star.size()*3+8);add.reserve(tri.size()*3+8);for(int id:star){Face&f=F[id];rem[ekey(f.a,f.b)]++;rem[ekey(f.b,f.c)]++;rem[ekey(f.c,f.a)]++;}for(auto&t:tri){add[ekey(t[0],t[1])]++;add[ekey(t[1],t[2])]++;add[ekey(t[2],t[0])]++;}for(auto&kv:add){int base=edgeCnt.count(kv.first)?edgeCnt[kv.first]:0;int r=rem.count(kv.first)?rem[kv.first]:0;int fin=base-r+kv.second;if(fin!=2)return false;}for(auto&kv:rem){int base=edgeCnt.count(kv.first)?edgeCnt[kv.first]:0;int a=add.count(kv.first)?add[kv.first]:0;int fin=base-kv.second+a;if(fin!=0&&fin!=2)return false;}return true;}
static bool buildPlan(int v,int pass,Plan&pl){vector<int>ring,star;Vec3 n;double oldA;if(!linkCycle(v,ring,star,n,oldA))return false;double minDot[3]={0.99995,0.9992,0.9965};double maxPlane[3]={0.050,0.105,0.160};double maxAreaRel[3]={0.020,0.055,0.090};if(pass<0||pass>2)pass=0;int deg=ring.size();if(pass==2&&deg>12)return false;double worstDot=1,plane=0;for(int id:star){Face&f=F[id];double d=max(-1.0,min(1.0,dot3(f.n,n)));worstDot=min(worstDot,d);plane=max(plane,fabs(dot3(n,P[v]-P[f.a])));}if(worstDot<minDot[pass]||plane>tol*maxPlane[pass])return false;vector<array<int,3>>tri;if(!triangulateRing(ring,n,tri))return false;double newA=0,nloss=0;for(auto&t:tri){if(t[0]==t[1]||t[1]==t[2]||t[0]==t[2])return false;if(faceSet.count(fkey(t[0],t[1],t[2])))return false;double a2=area2(t[0],t[1],t[2]);if(a2<=areaFloor)return false;Vec3 nn=fnorm(t[0],t[1],t[2]);double d=dot3(nn,n);if(d<minDot[pass]-0.003)return false;newA+=0.5*sqrt(a2);nloss+=max(0.0,1.0-d)*sqrt(a2);}double ar=oldA>1e-300?fabs(newA-oldA)/oldA:0;if(ar>maxAreaRel[pass])return false;if(!localEdgesOK(star,tri))return false;int recv=-1;double bd=1e100;for(int r:ring)if(boxWithin(r,bbox[v])){double d=n2(P[v]-P[r]);if(d<bd){bd=d;recv=r;}}if(recv<0)return false;pl.tri.swap(tri);pl.recv=recv;pl.ring=ring;pl.star=star;pl.score=(1.0-worstDot)*1e5+plane/(tol+1e-300)*20+ar*40+sqrt(bd)/(tol+1e-300)+0.02*deg+nloss/(oldA+1e-300)*10;return true;}
static void pushCand(int v,int pass,priority_queue<Cand>&pq){if(!alive[v])return;Plan p;if(buildPlan(v,pass,p))pq.push({p.score,v,ver[v],pass});}
static bool applyPlan(int v,int pass,priority_queue<Cand>&pq){Plan p;if(!buildPlan(v,pass,p))return false;for(int id:p.star){Face &f=F[id];if(!f.alive)continue;fEdgeAdd(f,-1);faceSet.erase(fkey(f.a,f.b,f.c));f.alive=0;aliveF--;}for(auto&t:p.tri){Face nf{t[0],t[1],t[2],1,fnorm(t[0],t[1],t[2])};int id=(int)F.size();F.push_back(nf);fEdgeAdd(nf,1);faceSet.insert(fkey(nf.a,nf.b,nf.c));inc[nf.a].push_back(id);inc[nf.b].push_back(id);inc[nf.c].push_back(id);aliveF++;}mergeBox(p.recv,bbox[v]);alive[v]=0;aliveV--;ver[v]++;vector<int>().swap(inc[v]);unordered_set<int>upd;upd.reserve(128);for(int r:p.ring){upd.insert(r);cleanInc(r);for(int id:inc[r])if(id>=0&&id<(int)F.size()&&F[id].alive){upd.insert(F[id].a);upd.insert(F[id].b);upd.insert(F[id].c);}}for(int x:upd)if(alive[x]){ver[x]++;pushCand(x,pass,pq);}return true;}
static bool finalValid(){unordered_map<unsigned long long,int>ec;ec.reserve((size_t)aliveF*4+10);vector<unsigned char>used(N0,0);for(auto&f:F)if(f.alive){if(!alive[f.a]||!alive[f.b]||!alive[f.c])return false;if(f.a==f.b||f.b==f.c||f.a==f.c)return false;if(area2(f.a,f.b,f.c)<=areaFloor)return false;used[f.a]=used[f.b]=used[f.c]=1;ec[ekey(f.a,f.b)]++;ec[ekey(f.b,f.c)]++;ec[ekey(f.c,f.a)]++;}for(auto&kv:ec)if(kv.second!=2)return false;for(int i=0;i<N0;i++)if(alive[i]){if(!used[i])return false;for(int m=0;m<8;m++){Vec3 c{(m&1)?bbox[i].mx.x:bbox[i].mn.x,(m&2)?bbox[i].mx.y:bbox[i].mn.y,(m&4)?bbox[i].mx.z:bbox[i].mn.z};if(n2(c-P[i])>tol2*1.00001)return false;}}return true;}
static void outputCurrent(){vector<int>id(N0,-1),rev;rev.reserve(aliveV);for(int i=0;i<N0;i++)if(alive[i]){id[i]=(int)rev.size();rev.push_back(i);}vector<array<int,3>>out;out.reserve(aliveF);for(auto&f:F)if(f.alive){int a=id[f.a],b=id[f.b],c=id[f.c];if(a>=0&&b>=0&&c>=0&&a!=b&&b!=c&&a!=c)out.push_back({a,b,c});}printf("%d %d\n",(int)rev.size(),(int)out.size());for(int oi:rev){auto p=P[oi];printf("v %.15g %.15g %.15g\n",p.x,p.y,p.z);}for(auto&t:out)printf("f %d %d %d\n",t[0]+1,t[1]+1,t[2]+1);} 
static void planarPasses(){double limits[3]={5.6,10.8,15.4};for(int pass=0;pass<3;pass++){priority_queue<Cand>pq;for(int i=0;i<N0;i++)pushCand(i,pass,pq);int pops=0;while(!pq.empty()&&elapsed()<limits[pass]){Cand c=pq.top();pq.pop();if(!alive[c.v]||ver[c.v]!=c.ver)continue;applyPlan(c.v,pass,pq);if((++pops&1023)==0&&aliveV<8)break;}}}
int main(){T0=clock();if(!readInput())return 0;if(N0<=8||F0<=12||diagLen<=0){outputIdentity();return 0;}if(tryBoxGrid())return 0;planarPasses();if(!finalValid())outputIdentity();else outputCurrent();return 0;}