#include <bits/stdc++.h>
using namespace std;
struct V{double x,y,z;};
static inline V operator+(V a,V b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline V operator-(V a,V b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline V operator*(V a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline V operator/(V a,double s){return {a.x/s,a.y/s,a.z/s};}
static inline double dotp(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline V crossp(V a,V b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(V a){return dotp(a,a);} static inline double norm(V a){return sqrt(max(0.0,n2(a)));}
struct F{int a,b,c;};
static inline uint64_t ek(int a,int b){if(a>b)swap(a,b);return (uint64_t)(uint32_t)a<<32|(uint32_t)b;}
static inline array<int,3> tk(int a,int b,int c){array<int,3> r{a,b,c};sort(r.begin(),r.end());return r;}
int N,M; vector<V> P0; vector<F> F0; double diagL=1,tau=1,tau2=1;
struct KD{
    vector<V>*p=nullptr; vector<int> id; struct Node{int l=-1,r=-1,ax=0,idx=-1;}; vector<Node> tr;
    KD(){} KD(vector<V>&pts){build(pts);} static double coord(const V&v,int ax){return ax==0?v.x:ax==1?v.y:v.z;}
    int rec(int l,int r,int dep){if(l>=r)return -1;int m=(l+r)/2,ax=dep%3;nth_element(id.begin()+l,id.begin()+m,id.begin()+r,[&](int a,int b){return coord((*p)[a],ax)<coord((*p)[b],ax);});int cur=tr.size();tr.push_back({-1,-1,ax,id[m]});tr[cur].l=rec(l,m,dep+1);tr[cur].r=rec(m+1,r,dep+1);return cur;}
    void build(vector<V>&pts){p=&pts;id.resize(pts.size());iota(id.begin(),id.end(),0);tr.reserve(pts.size());rec(0,id.size(),0);} 
    void q(int t,const V&v,double&best)const{if(t<0)return;const Node&n=tr[t];double d=n2(v-(*p)[n.idx]);if(d<best)best=d;double df=coord(v,n.ax)-coord((*p)[n.idx],n.ax);int a=df<0?n.l:n.r,b=df<0?n.r:n.l;q(a,v,best);if(df*df<best)q(b,v,best);} 
    double nearest2(const V&v)const{double b=1e300;q(0,v,b);return b;}
};
static bool closed(const vector<V>&Vv,const vector<F>&Fs){
    if(Vv.size()<4||Fs.size()<4||Vv.size()>(size_t)N)return false; unordered_map<uint64_t,int> ec; ec.reserve(Fs.size()*3+8); set<array<int,3>> st; double mina=max(1e-32,1e-28*diagL*diagL*diagL*diagL);
    for(auto f:Fs){if(f.a<0||f.b<0||f.c<0||f.a>=(int)Vv.size()||f.b>=(int)Vv.size()||f.c>=(int)Vv.size())return false; if(f.a==f.b||f.b==f.c||f.a==f.c)return false; if(n2(crossp(Vv[f.b]-Vv[f.a],Vv[f.c]-Vv[f.a]))<=mina)return false; if(!st.insert(tk(f.a,f.b,f.c)).second)return false; ec[ek(f.a,f.b)]++;ec[ek(f.b,f.c)]++;ec[ek(f.c,f.a)]++;}
    for(auto &kv:ec)if(kv.second!=2)return false; return true;
}
static bool hausdorff(vector<V>&cand){
    if(cand.empty()||cand.size()>P0.size())return false; KD ko(P0),kc(cand); double lim=tau2*1.000001; for(const V&p:P0)if(kc.nearest2(p)>lim)return false; for(const V&p:cand)if(ko.nearest2(p)>lim)return false; return true;
}
static bool valid(vector<V>&Vv,vector<F>&Fs){return closed(Vv,Fs)&&hausdorff(Vv);} 
static void orient(vector<V>&Vv,F&f,V center){V cr=crossp(Vv[f.b]-Vv[f.a],Vv[f.c]-Vv[f.a]);V cc=(Vv[f.a]+Vv[f.b]+Vv[f.c])/3.0;if(dotp(cr,cc-center)<0)swap(f.b,f.c);} 
static void out(vector<V>&Vv,vector<F>&Fs){cout<<Vv.size()<<" "<<Fs.size()<<"\n";cout.setf(ios::fixed);cout<<setprecision(10);for(auto p:Vv)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n";for(auto f:Fs)cout<<"f "<<f.a+1<<" "<<f.b+1<<" "<<f.c+1<<"\n";}
static void original(){cout<<P0.size()<<" "<<F0.size()<<"\n";cout.setf(ios::fixed);cout<<setprecision(10);for(auto p:P0)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n";for(auto f:F0)cout<<"f "<<f.a+1<<" "<<f.b+1<<" "<<f.c+1<<"\n";}
static bool boxGrid(vector<V>&Vv,vector<F>&Fs){
    V mn=P0[0],mx=P0[0];for(auto p:P0){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);} double dx=mx.x-mn.x,dy=mx.y-mn.y,dz=mx.z-mn.z;if(min({dx,dy,dz})<=diagL*1e-8)return false; double nearTol=min(tau*.18,diagL*.004); int near=0; for(auto p:P0){double d=min({fabs(p.x-mn.x),fabs(p.x-mx.x),fabs(p.y-mn.y),fabs(p.y-mx.y),fabs(p.z-mn.z),fabs(p.z-mx.z)}); if(d<=nearTol)near++;} if(near*100<(int)P0.size()*985/10)return false;
    double step=tau*.72; int nx=max(1,(int)ceil(dx/step)),ny=max(1,(int)ceil(dy/step)),nz=max(1,(int)ceil(dz/step)); long long est=2LL*((nx+1)*(ny+1)+(nx+1)*(nz+1)+(ny+1)*(nz+1)); if(est>2LL*N||est>200000)return false; unordered_map<unsigned long long,int> mp; mp.reserve(est*2+10); Vv.clear();Fs.clear();V cen=(mn+mx)/2.0; auto key=[&](int ix,int iy,int iz){return ((unsigned long long)ix<<42)^((unsigned long long)iy<<21)^(unsigned long long)iz;}; auto addv=[&](int ix,int iy,int iz){unsigned long long k=key(ix,iy,iz);auto it=mp.find(k);if(it!=mp.end())return it->second;double x=mn.x+dx*(double)ix/nx,y=mn.y+dy*(double)iy/ny,z=mn.z+dz*(double)iz/nz;int id=Vv.size();mp[k]=id;Vv.push_back({x,y,z});return id;}; auto tri=[&](int a,int b,int c){F f{a,b,c};orient(Vv,f,cen);Fs.push_back(f);}; auto quad=[&](int a,int b,int c,int d){tri(a,b,c);tri(a,c,d);};
    for(int ix=0;ix<nx;ix++)for(int iy=0;iy<ny;iy++){quad(addv(ix,iy,0),addv(ix+1,iy,0),addv(ix+1,iy+1,0),addv(ix,iy+1,0));quad(addv(ix,iy,nz),addv(ix,iy+1,nz),addv(ix+1,iy+1,nz),addv(ix+1,iy,nz));}
    for(int ix=0;ix<nx;ix++)for(int iz=0;iz<nz;iz++){quad(addv(ix,0,iz),addv(ix,0,iz+1),addv(ix+1,0,iz+1),addv(ix+1,0,iz));quad(addv(ix,ny,iz),addv(ix+1,ny,iz),addv(ix+1,ny,iz+1),addv(ix,ny,iz+1));}
    for(int iy=0;iy<ny;iy++)for(int iz=0;iz<nz;iz++){quad(addv(0,iy,iz),addv(0,iy+1,iz),addv(0,iy+1,iz+1),addv(0,iy,iz+1));quad(addv(nx,iy,iz),addv(nx,iy,iz+1),addv(nx,iy+1,iz+1),addv(nx,iy+1,iz));}
    return Vv.size()<P0.size()&&valid(Vv,Fs);
}
static void axisCoord(V p,int ax,double&t,double&u,double&v){if(ax==0){t=p.x;u=p.y;v=p.z;}else if(ax==1){t=p.y;u=p.x;v=p.z;}else{t=p.z;u=p.x;v=p.y;}}
static V makeAxis(int ax,double t,double u,double v){if(ax==0)return {t,u,v};if(ax==1)return {u,t,v};return {u,v,t};}
static bool torus(vector<V>&Vv,vector<F>&Fs){
    if(N<1000)return false; for(int ax=0;ax<3;ax++){double t0=1e100,t1=-1e100,u0=1e100,u1=-1e100,v0=1e100,v1=-1e100;for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);t0=min(t0,t);t1=max(t1,t);u0=min(u0,u);u1=max(u1,u);v0=min(v0,v);v1=max(v1,v);}double ct=(t0+t1)/2,cu=(u0+u1)/2,cv=(v0+v1)/2;double rmin=1e100,rmax=0;for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);double rho=hypot(u-cu,v-cv);rmin=min(rmin,rho);rmax=max(rmax,rho);}double R=(rmax+rmin)/2,r=(rmax-rmin)/2,rt=(t1-t0)/2;if(r<=1e-12||R<r*1.25||fabs(rt-r)>tau*.45)continue;double rms=0,ma=0;for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);double rho=hypot(u-cu,v-cv);double e=fabs(hypot(rho-R,t-ct)-r);rms+=e*e;ma=max(ma,e);}rms=sqrt(rms/N);if(ma>tau*.38||rms>tau*.085)continue;int U=max(16,(int)ceil(2*M_PI*(R+r)/(tau*.72)));int W=max(8,(int)ceil(2*M_PI*r/(tau*.72)));U=min(U,256);W=min(W,96);if((long long)U*W>=N||U*W>220000)continue;Vv.clear();Fs.clear();for(int i=0;i<U;i++){double th=2*M_PI*i/U;for(int j=0;j<W;j++){double ph=2*M_PI*j/W,rr=R+r*cos(ph);Vv.push_back(makeAxis(ax,ct+r*sin(ph),cu+rr*cos(th),cv+rr*sin(th)));}}auto id=[&](int i,int j){return ((i%U+U)%U)*W+(j%W+W)%W;};auto normalPred=[&](V p){double t,u,v;axisCoord(p,ax,t,u,v);double th=atan2(v-cv,u-cu),rho=hypot(u-cu,v-cv);return makeAxis(ax,t-ct,(rho-R)*cos(th),(rho-R)*sin(th));};for(int i=0;i<U;i++)for(int j=0;j<W;j++){int a=id(i,j),b=id(i+1,j),c=id(i+1,j+1),d=id(i,j+1);F f1{a,b,c};V ce=(Vv[a]+Vv[b]+Vv[c])/3.0;if(dotp(crossp(Vv[f1.b]-Vv[f1.a],Vv[f1.c]-Vv[f1.a]),normalPred(ce))<0)swap(f1.b,f1.c);Fs.push_back(f1);F f2{a,c,d};ce=(Vv[a]+Vv[c]+Vv[d])/3.0;if(dotp(crossp(Vv[f2.b]-Vv[f2.a],Vv[f2.c]-Vv[f2.a]),normalPred(ce))<0)swap(f2.b,f2.c);Fs.push_back(f2);}if(valid(Vv,Fs))return true;}return false;
}
static bool lathe(vector<V>&Vv,vector<F>&Fs){
    if(N<1200)return false; for(int ax=0;ax<3;ax++){double t0=1e100,t1=-1e100,u0=1e100,u1=-1e100,v0=1e100,v1=-1e100;for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);t0=min(t0,t);t1=max(t1,t);u0=min(u0,u);u1=max(u1,u);v0=min(v0,v);v1=max(v1,v);}double H=t1-t0,cu=(u0+u1)/2,cv=(v0+v1)/2;if(H<=diagL*1e-8)continue;int B=max(4,min(180,(int)ceil(H/(tau*.7))));vector<double> rmax(B+1,0),cnt(B+1,0);for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);int b=min(B,max(0,(int)llround((t-t0)/H*B)));double r=hypot(u-cu,v-cv);rmax[b]=max(rmax[b],r);cnt[b]++;}for(int i=0;i<=B;i++)if(cnt[i]==0){int l=i-1,r=i+1;while(l>=0&&cnt[l]==0)l--;while(r<=B&&cnt[r]==0)r++;if(l>=0&&r<=B)rmax[i]=(rmax[l]*(r-i)+rmax[r]*(i-l))/(r-l);else if(l>=0)rmax[i]=rmax[l];else if(r<=B)rmax[i]=rmax[r];}
        double R=*max_element(rmax.begin(),rmax.end());if(R<=1e-12)continue;int bad=0,tot=0;for(auto p:P0){double t,u,v;axisCoord(p,ax,t,u,v);double pos=(t-t0)/H*B;int b=min(B-1,max(0,(int)floor(pos)));double a=pos-b;double pr=rmax[b]*(1-a)+rmax[b+1]*a;double r=hypot(u-cu,v-cv);bool cap=(fabs(t-t0)<tau*.65)||(fabs(t-t1)<tau*.65);if(!cap&&r<pr-tau*.42)bad++;tot++;}if(bad*100>tot*2)continue;int S=max(12,(int)ceil(2*M_PI*R/(tau*.72)));S=min(S,256);long long est=2LL+(long long)(B+1)*S;if(est>=N||est>240000)continue;Vv.clear();Fs.clear();vector<vector<int>> ring(B+1);V center=makeAxis(ax,(t0+t1)/2,cu,cv);auto add=[&](int a,int b,int c){F f{a,b,c};orient(Vv,f,center);Fs.push_back(f);};for(int i=0;i<=B;i++){double t=t0+H*i/B,r=rmax[i];if(r<tau*.22){ring[i].push_back((int)Vv.size());Vv.push_back(makeAxis(ax,t,cu,cv));}else{ring[i].resize(S);for(int j=0;j<S;j++){double th=2*M_PI*j/S;ring[i][j]=Vv.size();Vv.push_back(makeAxis(ax,t,cu+r*cos(th),cv+r*sin(th)));}}}
        for(int i=0;i<B;i++){bool p0=ring[i].size()==1,p1=ring[i+1].size()==1;if(p0&&p1)continue;if(p0){int pole=ring[i][0];for(int j=0;j<S;j++)add(pole,ring[i+1][j],ring[i+1][(j+1)%S]);}else if(p1){int pole=ring[i+1][0];for(int j=0;j<S;j++)add(pole,ring[i][(j+1)%S],ring[i][j]);}else{for(int j=0;j<S;j++){int a=ring[i][j],b=ring[i+1][j],c=ring[i+1][(j+1)%S],d=ring[i][(j+1)%S];add(a,b,c);add(a,c,d);}}}
        if(ring[0].size()>1){int cen=Vv.size();Vv.push_back(makeAxis(ax,t0,cu,cv));for(int j=0;j<S;j++)add(cen,ring[0][(j+1)%S],ring[0][j]);}
        if(ring[B].size()>1){int cen=Vv.size();Vv.push_back(makeAxis(ax,t1,cu,cv));for(int j=0;j<S;j++)add(cen,ring[B][j],ring[B][(j+1)%S]);}
        if(valid(Vv,Fs))return true;}return false;
}

struct K3{int x,y,z;bool operator<(const K3&o)const{return x!=o.x?x<o.x:(y!=o.y?y<o.y:z<o.z);}};
static int qcube(double t,int n){int q=(int)llround((t+1.0)*0.5*n);q=max(0,min(n,q));return -n+2*q;}
static bool cubemapStar(vector<V>&Vv,vector<F>&Fs){
    if(N<1500)return false;V mn=P0[0],mx=P0[0],cen{0,0,0};for(auto p:P0){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);cen=cen+p;}cen=cen/(double)N;double ex=mx.x-mn.x,ey=mx.y-mn.y,ez=mx.z-mn.z;if(min({ex,ey,ez})<max({ex,ey,ez})*.45)return false;
    auto keyface=[&](int face,int i,int j,int n){int a=-n+2*i,b=-n+2*j;if(face==0)return K3{ n,a,b};if(face==1)return K3{-n,a,b};if(face==2)return K3{a, n,b};if(face==3)return K3{a,-n,b};if(face==4)return K3{a,b, n};return K3{a,b,-n};};
    auto nodeOf=[&](V q,int n){double ax=fabs(q.x),ay=fabs(q.y),az=fabs(q.z);if(ax>=ay&&ax>=az){double s=max(ax,1e-300);return K3{q.x>=0?n:-n,qcube(q.y/s,n),qcube(q.z/s,n)};}if(ay>=ax&&ay>=az){double s=max(ay,1e-300);return K3{qcube(q.x/s,n),q.y>=0?n:-n,qcube(q.z/s,n)};}double s=max(az,1e-300);return K3{qcube(q.x/s,n),qcube(q.y/s,n),q.z>=0?n:-n};};
    int ns[]={6,8,10,12,14,16,18,20,24,28,32,36};
    for(int n:ns){map<K3,int> id;vector<K3> keys;vector<V> dir;auto gid=[&](K3 k){auto it=id.find(k);if(it!=id.end())return it->second;int r=id.size();id[k]=r;keys.push_back(k);double l=sqrt((double)k.x*k.x+(double)k.y*k.y+(double)k.z*k.z);dir.push_back({k.x/l,k.y/l,k.z/l});return r;};vector<F> topo;for(int face=0;face<6;face++)for(int i=0;i<n;i++)for(int j=0;j<n;j++){int a=gid(keyface(face,i,j,n)),b=gid(keyface(face,i+1,j,n)),c=gid(keyface(face,i+1,j+1,n)),d=gid(keyface(face,i,j+1,n));topo.push_back({a,b,c});topo.push_back({a,c,d});}int K=keys.size();if(K>=N||K>12000)continue;vector<int> pick(K,-1);vector<double> best(K,-1e300);for(int i=0;i<N;i++){V q=P0[i]-cen;double r=norm(q);if(r<=1e-14)continue;K3 k=nodeOf(q,n);auto it=id.find(k);if(it==id.end())continue;int h=it->second;double sc=dotp(q,dir[h])+0.015*r;if(sc>best[h]){best[h]=sc;pick[h]=i;}}int filled=0;for(int x:pick)filled+=x>=0;if(filled*100<K*72)continue;for(int h=0;h<K;h++)if(pick[h]<0){double bs=-1e300;int bi=-1;for(int i=0;i<N;i++){V q=P0[i]-cen;double r=norm(q);if(r<=1e-14)continue;double sc=dotp(q/r,dir[h])+0.01*r/diagL;if(sc>bs){bs=sc;bi=i;}}pick[h]=bi;}vector<int> tmp=pick;sort(tmp.begin(),tmp.end());if(unique(tmp.begin(),tmp.end())!=tmp.end())continue;Vv.clear();Fs=topo;Vv.reserve(K);for(int idx:pick)Vv.push_back(P0[idx]);for(auto &f:Fs)orient(Vv,f,cen);if(valid(Vv,Fs))return true;}
    return false;
}

int main(){ios::sync_with_stdio(false);cin.tie(nullptr);if(!(cin>>N>>M))return 0;P0.resize(N);string s;for(int i=0;i<N;i++)cin>>s>>P0[i].x>>P0[i].y>>P0[i].z;F0.resize(M);for(int i=0;i<M;i++){cin>>s>>F0[i].a>>F0[i].b>>F0[i].c;--F0[i].a;--F0[i].b;--F0[i].c;}if(N==8&&M==12){cout<<"8 12\n";cout.setf(ios::fixed);cout<<setprecision(9);for(auto p:P0)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n";for(auto f:F0)cout<<"f "<<f.a+1<<" "<<f.b+1<<" "<<f.c+1<<"\n";return 0;}V mn=P0[0],mx=P0[0];for(auto p:P0){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);}diagL=norm(mx-mn);if(diagL<=0)diagL=1;tau=.05*diagL;tau2=tau*tau;vector<V>bestV,cv;vector<F>bestF,cf;bool have=false;auto take=[&](vector<V>&v,vector<F>&f){if(v.size()<P0.size()&&(!have||v.size()<bestV.size())){bestV=v;bestF=f;have=true;}};if(boxGrid(cv,cf))take(cv,cf);if(cubemapStar(cv,cf))take(cv,cf);if(torus(cv,cf))take(cv,cf);if(lathe(cv,cf))take(cv,cf);if(have)out(bestV,bestF);else original();}