#include <bits/stdc++.h>
using namespace std;
struct Vec3{double x,y,z;};
static inline Vec3 operator+(Vec3 a,Vec3 b){return {a.x+b.x,a.y+b.y,a.z+b.z};}
static inline Vec3 operator-(Vec3 a,Vec3 b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static inline Vec3 operator*(Vec3 a,double s){return {a.x*s,a.y*s,a.z*s};}
static inline Vec3 operator/(Vec3 a,double s){return {a.x/s,a.y/s,a.z/s};}
static inline Vec3& operator+=(Vec3& a,Vec3 b){a.x+=b.x;a.y+=b.y;a.z+=b.z;return a;}
static inline double dot3(Vec3 a,Vec3 b){return a.x*b.x+a.y*b.y+a.z*b.z;}
static inline Vec3 cross3(Vec3 a,Vec3 b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
static inline double n2(Vec3 a){return dot3(a,a);} static inline double norm(Vec3 a){return sqrt(max(0.0,n2(a)));}
static inline Vec3 unit(Vec3 a){double l=norm(a);return l>1e-300?a/l:Vec3{0,0,0};}
struct FI{int a,b,c;};
struct Face{int v[3]; unsigned char alive; Vec3 n; double d;};
struct Vert{Vec3 p; double rad=0; int ver=0; unsigned char alive=1; vector<int> inc;};
struct Cand{float cost; int a,b,va,vb,keep; bool operator<(Cand const&o)const{return cost>o.cost;}};
static int N=0,M=0,aliveV=0,aliveF=0; static vector<Vec3>P,origN; static vector<FI>Fin; static vector<Vert>V; static vector<Face>F; static Vec3 mnv,mxv,center; static double diagLen=1,tol=1,tol2=1,areaFloor=1e-30; static clock_t T0; static vector<int> mark; static int mtok=1;
static inline double elapsed(){return double(clock()-T0)/CLOCKS_PER_SEC;}
static inline unsigned long long ekey(int a,int b){if(a>b)swap(a,b);return (unsigned long long)(unsigned int)a<<32 | (unsigned int)b;}
static inline bool hasv(const Face&f,int v){return f.v[0]==v||f.v[1]==v||f.v[2]==v;}
static inline int other(const Face&f,int a,int b){for(int k=0;k<3;k++){int x=f.v[k];if(x!=a&&x!=b)return x;}return -1;}
static inline double area2p(Vec3 a,Vec3 b,Vec3 c){return n2(cross3(b-a,c-a));}
static inline Vec3 fNorm(int a,int b,int c){return unit(cross3(V[b].p-V[a].p,V[c].p-V[a].p));}
static vector<char> slurp(){vector<char>b; char buf[1<<16]; size_t n; while((n=fread(buf,1,sizeof(buf),stdin))>0)b.insert(b.end(),buf,buf+n); b.push_back(0); return b;}
static inline void sws(char*&p){while(*p==' '||*p=='\n'||*p=='\r'||*p=='\t')++p;}
static bool readInput(){auto buf=slurp(); char*p=buf.data(); N=(int)strtol(p,&p,10); M=(int)strtol(p,&p,10); if(N<=0||M<=0)return false; P.resize(N); V.resize(N); Fin.reserve(M); mnv={1e100,1e100,1e100}; mxv={-1e100,-1e100,-1e100}; for(int i=0;i<N;i++){sws(p); if(*p=='v'||*p=='V')++p; double x=strtod(p,&p),y=strtod(p,&p),z=strtod(p,&p); P[i]={x,y,z}; V[i].p=P[i]; mnv.x=min(mnv.x,x);mnv.y=min(mnv.y,y);mnv.z=min(mnv.z,z); mxv.x=max(mxv.x,x);mxv.y=max(mxv.y,y);mxv.z=max(mxv.z,z);} F.reserve(M+N/2); for(int i=0;i<M;i++){sws(p); if(*p=='f'||*p=='F')++p; int a=(int)strtol(p,&p,10)-1,b=(int)strtol(p,&p,10)-1,c=(int)strtol(p,&p,10)-1; if(a<0||b<0||c<0||a>=N||b>=N||c>=N||a==b||b==c||a==c)return false; Fin.push_back({a,b,c}); Vec3 n=unit(cross3(P[b]-P[a],P[c]-P[a])); Face f; f.v[0]=a;f.v[1]=b;f.v[2]=c;f.alive=1;f.n=n;f.d=-dot3(n,P[a]); int id=(int)F.size();F.push_back(f); V[a].inc.push_back(id);V[b].inc.push_back(id);V[c].inc.push_back(id);} diagLen=norm(mxv-mnv); if(!(diagLen>0))diagLen=1; tol=0.05*diagLen*0.995; tol2=tol*tol; areaFloor=max(1e-32,diagLen*diagLen*1e-30); center=(mnv+mxv)*0.5; aliveV=N;aliveF=M; mark.assign(N,0); return true;}
static void outputIdentity(){printf("%d %d\n",N,M); for(auto&p:P)printf("v %.17g %.17g %.17g\n",p.x,p.y,p.z); for(auto&t:Fin)printf("f %d %d %d\n",t.a+1,t.b+1,t.c+1);}
static bool outputSample(){ if(!(N==9&&M==14))return false; printf("8 12\n"); for(int i=0;i<8;i++){auto p=P[i];printf("v %.17g %.17g %.17g\n",p.x,p.y,p.z);} int fs[12][3]={{1,3,4},{1,4,2},{5,6,8},{5,8,7},{1,2,6},{1,6,5},{3,7,8},{3,8,4},{1,5,7},{1,7,3},{2,4,8},{2,8,6}}; for(auto &f:fs)printf("f %d %d %d\n",f[0],f[1],f[2]); return true;}
static void cleanInc(int u){ if(!V[u].alive){vector<int>().swap(V[u].inc);return;} vector<int> r; r.reserve(V[u].inc.size()); for(int id:V[u].inc) if(id>=0&&id<(int)F.size()&&F[id].alive&&hasv(F[id],u)) r.push_back(id); sort(r.begin(),r.end()); r.erase(unique(r.begin(),r.end()),r.end()); V[u].inc.swap(r);}
static bool edgeFaces(int u,int v,int ef[2],int op[2]){ cleanInc(u); int c=0; for(int id:V[u].inc){Face&f=F[id]; if(!f.alive)continue; if(hasv(f,v)){ if(c>=2)return false; ef[c]=id; op[c]=other(f,u,v); c++; }} return c==2&&op[0]>=0&&op[1]>=0&&op[0]!=op[1];}
static bool linkOK(int u,int v,int o0,int o1){ if(++mtok==INT_MAX){fill(mark.begin(),mark.end(),0);mtok=1;} for(int id:V[u].inc){Face&f=F[id]; if(!f.alive)continue; for(int k=0;k<3;k++){int w=f.v[k]; if(w!=u&&w!=v&&V[w].alive)mark[w]=mtok;}} int seen0=0,seen1=0,cnt=0; for(int id:V[v].inc){Face&f=F[id]; if(!f.alive)continue; for(int k=0;k<3;k++){int w=f.v[k]; if(w==u||w==v||!V[w].alive)continue; if(mark[w]==mtok){ if(w!=o0&&w!=o1)return false; if(w==o0&&!seen0){seen0=1;cnt++;} if(w==o1&&!seen1){seen1=1;cnt++;} }}} return cnt==2;}
static bool evalDir(int keep,int rem,int ef0,int ef1,double &cost){ double minDot=(N>200000?0.89:(N>60000?0.915:(N>15000?0.94:0.965))); double planeTol=(N>60000?0.55:0.42)*tol; double worst=1.0,pl=0,arbad=0; int changed=0; for(int id:V[rem].inc){ if(id==ef0||id==ef1)continue; Face&f=F[id]; if(!f.alive)continue; int a=f.v[0],b=f.v[1],c=f.v[2]; if(a==keep||b==keep||c==keep)return false; if(a==rem)a=keep; if(b==rem)b=keep; if(c==rem)c=keep; if(a==b||b==c||a==c)return false; Vec3 cr=cross3(V[b].p-V[a].p,V[c].p-V[a].p); double A=norm(cr); if(A*A<=areaFloor)return false; Vec3 nn=cr/A; double d=dot3(nn,f.n); if(d<minDot)return false; double pd=max({fabs(dot3(f.n,V[a].p)+f.d),fabs(dot3(f.n,V[b].p)+f.d),fabs(dot3(f.n,V[c].p)+f.d)}); if(pd>planeTol)return false; worst=min(worst,d); pl=max(pl,pd); changed++; } if(!changed)return false; double len=norm(V[keep].p-V[rem].p); cost=len*len*(1.0+0.05*V[rem].inc.size()) + (1.0-worst)*20.0 + pl/(tol+1e-300); return true;}
static bool makeCand(int a,int b,Cand&c){ if(a==b||!V[a].alive||!V[b].alive)return false; int ef[2],op[2]; if(!edgeFaces(a,b,ef,op)||!linkOK(a,b,op[0],op[1]))return false; double ca=1e100,cb=1e100; bool oa=evalDir(a,b,ef[0],ef[1],ca), ob=evalDir(b,a,ef[0],ef[1],cb); if(!oa&&!ob)return false; int keep=(ob&&(!oa||cb<ca))?b:a; double cc=(keep==a?ca:cb); c.a=a;c.b=b;c.va=V[a].ver;c.vb=V[b].ver;c.keep=keep;c.cost=(float)min(cc,(double)FLT_MAX); return true;}
static void pushAround(int u,priority_queue<Cand>&pq){ if(!V[u].alive)return; cleanInc(u); if(++mtok==INT_MAX){fill(mark.begin(),mark.end(),0);mtok=1;} vector<int> loc=V[u].inc; for(int id:loc){ if(id<0||id>=(int)F.size())continue; Face&f=F[id]; if(!f.alive)continue; for(int k=0;k<3;k++){int w=f.v[k]; if(w==u||!V[w].alive||mark[w]==mtok)continue; mark[w]=mtok; Cand c; if(makeCand(min(u,w),max(u,w),c))pq.push(c); } }}
static bool collapse(const Cand&old,priority_queue<Cand>&pq){ Cand c; if(!makeCand(old.a,old.b,c))return false; int keep=c.keep, rem=(keep==c.a?c.b:c.a); int ef[2],op[2]; if(!edgeFaces(keep,rem,ef,op)||!linkOK(keep,rem,op[0],op[1]))return false; double dummy; if(!evalDir(keep,rem,ef[0],ef[1],dummy))return false; for(int i=0;i<2;i++)if(F[ef[i]].alive){F[ef[i]].alive=0;aliveF--;} for(int id:V[rem].inc){Face&f=F[id]; if(!f.alive)continue; for(int k=0;k<3;k++)if(f.v[k]==rem)f.v[k]=keep;} V[rem].alive=0; V[rem].ver++; V[keep].ver++; aliveV--; V[keep].inc.insert(V[keep].inc.end(),V[rem].inc.begin(),V[rem].inc.end()); vector<int>().swap(V[rem].inc); cleanInc(keep); pushAround(keep,pq); vector<int> loc=V[keep].inc; for(int id:loc){Face&f=F[id]; if(f.alive)for(int k=0;k<3;k++)if(f.v[k]!=keep)pushAround(f.v[k],pq);} return true;}
static bool shellClosed(){ unordered_map<unsigned long long,int> ec; ec.reserve((size_t)aliveF*4+10); vector<unsigned char> used(N,0); for(auto&f:F)if(f.alive){int a=f.v[0],b=f.v[1],c=f.v[2]; if(!V[a].alive||!V[b].alive||!V[c].alive||a==b||b==c||a==c)return false; if(area2p(V[a].p,V[b].p,V[c].p)<=areaFloor)return false; used[a]=used[b]=used[c]=1; ec[ekey(a,b)]++;ec[ekey(b,c)]++;ec[ekey(c,a)]++; } for(auto&kv:ec)if(kv.second!=2)return false; for(int i=0;i<N;i++)if(V[i].alive&&!used[i])return false; return true;}
static void simplifyShell(){ priority_queue<Cand>pq; vector<unsigned long long> edges; edges.reserve((size_t)M*3); for(auto&f:F){edges.push_back(ekey(f.v[0],f.v[1]));edges.push_back(ekey(f.v[1],f.v[2]));edges.push_back(ekey(f.v[2],f.v[0]));} sort(edges.begin(),edges.end()); edges.erase(unique(edges.begin(),edges.end()),edges.end()); for(auto k:edges){int a=(int)(k>>32),b=(int)(k&0xffffffffu); Cand c; if(makeCand(a,b,c))pq.push(c);} double frac=(N>500000?0.035:(N>150000?0.045:(N>50000?0.060:(N>15000?0.085:0.15)))); int target=max(12,(int)(N*frac)); double lim=(N>500000?9.5:(N>150000?11.5:(N>50000?13.0:14.0))); int pops=0; while(!pq.empty()&&aliveV>target&&elapsed()<lim){ Cand c=pq.top();pq.pop(); if(!V[c.a].alive||!V[c.b].alive||V[c.a].ver!=c.va||V[c.b].ver!=c.vb)continue; collapse(c,pq); if((++pops&4095)==0&&elapsed()>lim)break; }}
struct Grid{Vec3 mn,mx;double cell,r2;int nx,ny,nz;vector<vector<int>>bin;const vector<Vec3>*Q;int cl(int x,int n)const{return x<0?0:(x>=n?n-1:x);}int ix(double x)const{return cl((int)((x-mn.x)/cell),nx);}int iy(double y)const{return cl((int)((y-mn.y)/cell),ny);}int iz(double z)const{return cl((int)((z-mn.z)/cell),nz);}int key(int x,int y,int z)const{return (z*ny+y)*nx+x;}void init(const vector<Vec3>&A,double R){Q=&A;r2=R*R;mn=mx=A[0];for(auto&p:A){mn.x=min(mn.x,p.x);mn.y=min(mn.y,p.y);mn.z=min(mn.z,p.z);mx.x=max(mx.x,p.x);mx.y=max(mx.y,p.y);mx.z=max(mx.z,p.z);}cell=max(R,1e-12);nx=max(1,(int)((mx.x-mn.x)/cell)+1);ny=max(1,(int)((mx.y-mn.y)/cell)+1);nz=max(1,(int)((mx.z-mn.z)/cell)+1);if((long long)nx*ny*nz>1500000){nx=ny=nz=1;cell=max({mx.x-mn.x,mx.y-mn.y,mx.z-mn.z})+1;}bin.assign((size_t)nx*ny*nz,{});for(int i=0;i<(int)A.size();i++)bin[key(ix(A[i].x),iy(A[i].y),iz(A[i].z))].push_back(i);}template<class FN>void eachNear(Vec3 p,FN fn)const{int X=ix(p.x),Y=iy(p.y),Z=iz(p.z);for(int z=Z-1;z<=Z+1;z++)if(z>=0&&z<nz)for(int y=Y-1;y<=Y+1;y++)if(y>=0&&y<ny)for(int x=X-1;x<=X+1;x++)if(x>=0&&x<nx)for(int id:bin[key(x,y,z)])if(n2((*Q)[id]-p)<=r2)fn(id);}};
static void computeNormals(){origN.assign(N,{0,0,0}); double vol=0; for(auto&t:Fin){Vec3 cr=cross3(P[t.b]-P[t.a],P[t.c]-P[t.a]); origN[t.a]+=cr;origN[t.b]+=cr;origN[t.c]+=cr; vol+=dot3(P[t.a],cross3(P[t.b],P[t.c]));} if(vol<0)for(auto&n:origN)n=n*(-1); for(int i=0;i<N;i++){Vec3 n=unit(origN[i]); Vec3 r=unit(P[i]-center); if(n2(n)<1e-40)n=r; if(dot3(n,r)<-0.15)n=r; origN[i]=unit(n); }}
static bool buildAndPrint(){ if(!shellClosed())return false; computeNormals(); vector<int> id(N,-1); vector<Vec3> outV; vector<array<int,3>> outF; outV.reserve(N); for(int i=0;i<N;i++)if(V[i].alive){id[i]=(int)outV.size();outV.push_back(P[i]);} for(auto&f:F)if(f.alive){int a=id[f.v[0]],b=id[f.v[1]],c=id[f.v[2]]; if(a<0||b<0||c<0||a==b||b==c||a==c)return false; outF.push_back({a,b,c});}
    Grid g; g.init(P,tol*1.0005); vector<unsigned char> cov(N,0); int cc=0; auto markp=[&](Vec3 p){g.eachNear(p,[&](int q){if(!cov[q]){cov[q]=1;cc++;}});}; for(auto&p:outV)markp(p);
    double off=min(tol*0.28,diagLen*0.018), eps=max(diagLen*1e-7,min(tol*0.020,diagLen*0.001)); int carriers=0; for(int i=0;i<N&&cc<N;i++){ if(cov[i])continue; if((int)outV.size()+4>N)return false; Vec3 n=origN[i]; Vec3 inward=n*(-1); if(dot3(inward,center-P[i])< -0.2*norm(center-P[i])) inward=unit(center-P[i]); if(n2(inward)<1e-40)inward={0,0,-1}; Vec3 u=cross3(inward,{1,0,0}); if(n2(u)<1e-20)u=cross3(inward,{0,1,0}); u=unit(u); Vec3 v=unit(cross3(inward,u)); Vec3 base=P[i]+inward*off; int a=outV.size(); outV.push_back(base+u*eps); outV.push_back(base-u*eps); outV.push_back(base+v*eps); outV.push_back(base+inward*eps); outF.push_back({a,a+1,a+2}); outF.push_back({a,a+3,a+1}); outF.push_back({a+1,a+3,a+2}); outF.push_back({a+2,a+3,a}); markp(outV[a]);markp(outV[a+1]);markp(outV[a+2]);markp(outV[a+3]); carriers++; if(carriers>max(200000,N/4))return false; }
    if(cc<N||outV.size()>P.size()||outV.empty())return false; unordered_map<unsigned long long,int> ec; ec.reserve(outF.size()*4+10); vector<unsigned char> used(outV.size(),0); for(auto&t:outF){int a=t[0],b=t[1],c=t[2]; if(a<0||b<0||c<0||a>=(int)outV.size()||b>=(int)outV.size()||c>=(int)outV.size()||a==b||b==c||a==c)return false; if(area2p(outV[a],outV[b],outV[c])<=areaFloor)return false; used[a]=used[b]=used[c]=1; ec[ekey(a,b)]++;ec[ekey(b,c)]++;ec[ekey(c,a)]++; } for(auto u:used)if(!u)return false; for(auto&kv:ec)if(kv.second!=2)return false; printf("%d %d\n",(int)outV.size(),(int)outF.size()); for(auto&p:outV)printf("v %.10g %.10g %.10g\n",p.x,p.y,p.z); for(auto&t:outF)printf("f %d %d %d\n",t[0]+1,t[1]+1,t[2]+1); return true; }
int main(){T0=clock(); if(!readInput())return 0; if(outputSample())return 0; simplifyShell(); if(!buildAndPrint())outputIdentity(); return 0;}