#include <bits/stdc++.h>
using namespace std;
struct P{double x,y,z;}; struct T{int a,b,c;};
P operator+(P a,P b){return {a.x+b.x,a.y+b.y,a.z+b.z};} P operator-(P a,P b){return {a.x-b.x,a.y-b.y,a.z-b.z};} P operator*(P a,double s){return {a.x*s,a.y*s,a.z*s};} P operator/(P a,double s){return {a.x/s,a.y/s,a.z/s};}
double dot(P a,P b){return a.x*b.x+a.y*b.y+a.z*b.z;} P cross(P a,P b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};} double n2(P a){return dot(a,a);} double norm(P a){return sqrt(max(0.0,n2(a)));}
int N,M; vector<P> V0; vector<T> F0; P mnv,mxv; double diagv,epsv; chrono::steady_clock::time_point startTime; double sec(){return chrono::duration<double>(chrono::steady_clock::now()-startTime).count();}
struct Scan{string s; size_t p=0; Scan(){ios::sync_with_stdio(false);cin.tie(nullptr);ostringstream o;o<<cin.rdbuf();s=o.str();} string next(){while(p<s.size()&&isspace((unsigned char)s[p]))p++; size_t q=p; while(q<s.size()&&!isspace((unsigned char)s[q]))q++; string r=s.substr(p,q-p); p=q; return r;}};
bool num(const string&s){return !s.empty()&&(s[0]=='-'||s[0]=='+'||s[0]=='.'||isdigit((unsigned char)s[0]));}
int ix(const string&s){return (int)strtol(s.c_str(),nullptr,10)-1;}
void read(){Scan sc; string h=sc.next(); if(h.empty()) exit(0); N=stoi(h); M=stoi(sc.next()); V0.resize(N); F0.resize(M); mnv={1e100,1e100,1e100}; mxv={-1e100,-1e100,-1e100}; for(int i=0;i<N;i++){string a=sc.next(),x,y,z; if(num(a)){x=a;y=sc.next();z=sc.next();}else{x=sc.next();y=sc.next();z=sc.next();} P p{stod(x),stod(y),stod(z)}; V0[i]=p; mnv.x=min(mnv.x,p.x); mnv.y=min(mnv.y,p.y); mnv.z=min(mnv.z,p.z); mxv.x=max(mxv.x,p.x); mxv.y=max(mxv.y,p.y); mxv.z=max(mxv.z,p.z);} for(int i=0;i<M;i++){string a=sc.next(),b,c,d; if(num(a)){b=a;c=sc.next();d=sc.next();}else{b=sc.next();c=sc.next();d=sc.next();} F0[i]={ix(b),ix(c),ix(d)};} diagv=norm(mxv-mnv); if(!(diagv>0)) diagv=1; epsv=.05*diagv;}
uint64_t ek(int a,int b){if(a>b)swap(a,b); return (uint64_t)(uint32_t)a<<32 | (uint32_t)b;} uint64_t tk(int a,int b,int c){if(a>b)swap(a,b); if(b>c)swap(b,c); if(a>b)swap(a,b); return ((uint64_t)(uint32_t)a<<42)^((uint64_t)(uint32_t)b<<21)^(uint32_t)c;}
bool same(T f,int a,int b,int c){return tk(f.a,f.b,f.c)==tk(a,b,c);} 
bool valid(const vector<P>&v,const vector<T>&f){if(v.size()<4||f.size()<4||v.size()>(size_t)max(1,N))return false; double amin=max(1e-32,1e-26*diagv*diagv*diagv*diagv); vector<uint64_t> e; e.reserve(f.size()*3); for(auto&q:f){if(q.a<0||q.b<0||q.c<0||q.a>=(int)v.size()||q.b>=(int)v.size()||q.c>=(int)v.size())return false; if(q.a==q.b||q.a==q.c||q.b==q.c)return false; if(n2(cross(v[q.b]-v[q.a],v[q.c]-v[q.a]))<=amin)return false; e.push_back(ek(q.a,q.b)); e.push_back(ek(q.b,q.c)); e.push_back(ek(q.c,q.a));} sort(e.begin(),e.end()); for(size_t i=0;i<e.size();){size_t j=i+1; while(j<e.size()&&e[j]==e[i])j++; if(j-i!=2)return false; i=j;} return true;}
void orient(vector<P>&v,vector<T>&f){P c{0,0,0}; for(auto&p:v)c=c+p; c=c/(double)max<size_t>(1,v.size()); for(auto&q:f){P n=cross(v[q.b]-v[q.a],v[q.c]-v[q.a]); P fc=(v[q.a]+v[q.b]+v[q.c])/3.0; if(dot(n,fc-c)<0)swap(q.b,q.c);}}
struct KD{struct Nn{int id,l,r,ax; double s;}; const vector<P>*p; vector<int> id; vector<Nn> tr; int build(int l,int r){if(l>=r)return -1; P mn{1e100,1e100,1e100},mx{-1e100,-1e100,-1e100}; for(int i=l;i<r;i++){auto&q=(*p)[id[i]]; mn.x=min(mn.x,q.x); mn.y=min(mn.y,q.y); mn.z=min(mn.z,q.z); mx.x=max(mx.x,q.x); mx.y=max(mx.y,q.y); mx.z=max(mx.z,q.z);} P d=mx-mn; int ax=d.y>d.x&&d.y>=d.z?1:(d.z>d.x&&d.z>=d.y?2:0),m=(l+r)/2; nth_element(id.begin()+l,id.begin()+m,id.begin()+r,[&](int a,int b){auto&A=(*p)[a],&B=(*p)[b]; return ax==0?A.x<B.x:ax==1?A.y<B.y:A.z<B.z;}); int o=tr.size(); double sp=ax==0?(*p)[id[m]].x:ax==1?(*p)[id[m]].y:(*p)[id[m]].z; tr.push_back({id[m],-1,-1,ax,sp}); tr[o].l=build(l,m); tr[o].r=build(m+1,r); return o;} void init(const vector<P>&a){p=&a; id.resize(a.size()); iota(id.begin(),id.end(),0); tr.clear(); tr.reserve(a.size()); build(0,id.size());} void q(int o,P x,double&b)const{if(o<0)return; auto&n=tr[o]; double d=n2((*p)[n.id]-x); if(d<b)b=d; double v=n.ax==0?x.x:n.ax==1?x.y:x.z,df=v-n.s; int A=df<0?n.l:n.r,B=df<0?n.r:n.l; q(A,x,b); if(df*df<b)q(B,x,b);} double near2(P x)const{double b=1e300; q(0,x,b); return b;}};
bool hd(const vector<P>&v,double e){if(v.empty())return false; double e2=e*e; KD a,b; a.init(v); for(auto&p:V0) if(a.near2(p)>e2*1.000001) return false; b.init(V0); for(auto&p:v) if(b.near2(p)>e2*1.000001) return false; return true;}
void compact(vector<P>&v,vector<T>&f){vector<int> mp(v.size(),-1); int n=0; for(auto&q:f){if(mp[q.a]<0)mp[q.a]=n++; if(mp[q.b]<0)mp[q.b]=n++; if(mp[q.c]<0)mp[q.c]=n++;} vector<P> nv(n); for(int i=0;i<(int)v.size();i++)if(mp[i]>=0)nv[mp[i]]=v[i]; for(auto&q:f){q.a=mp[q.a]; q.b=mp[q.b]; q.c=mp[q.c];} v.swap(nv);} 
vector<int> divs(int n){vector<int>d; for(int i=1;(long long)i*i<=n;i++) if(n%i==0){d.push_back(i); if(i*i!=n)d.push_back(n/i);} sort(d.begin(),d.end()); return d;}

bool exactBox(vector<P>&v,vector<T>&f){vector<P> c={{mnv.x,mnv.y,mnv.z},{mxv.x,mnv.y,mnv.z},{mxv.x,mxv.y,mnv.z},{mnv.x,mxv.y,mnv.z},{mnv.x,mnv.y,mxv.z},{mxv.x,mnv.y,mxv.z},{mxv.x,mxv.y,mxv.z},{mnv.x,mxv.y,mxv.z}}; double e2=epsv*epsv*.98; for(auto&p:V0){double b=1e300; for(auto&q:c)b=min(b,n2(p-q)); if(b>e2)return false;} int t[12][3]={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,1,5},{0,5,4},{1,2,6},{1,6,5},{2,7,6},{2,3,7},{3,4,7},{3,0,4}}; v=c; f.clear(); for(auto&r:t)f.push_back({r[0],r[1],r[2]}); orient(v,f); return valid(v,f);} 
bool aabbGrid(vector<P>&v,vector<T>&f){double lx=mxv.x-mnv.x,ly=mxv.y-mnv.y,lz=mxv.z-mnv.z; if(N<80||lx<=1e-12*diagv||ly<=1e-12*diagv||lz<=1e-12*diagv)return false; double tol=.006*diagv; int c[6]={},bad=0,st=max(1,N/200000); for(int i=0;i<N;i+=st){auto&p=V0[i]; double d[6]={fabs(p.x-mnv.x),fabs(p.x-mxv.x),fabs(p.y-mnv.y),fabs(p.y-mxv.y),fabs(p.z-mnv.z),fabs(p.z-mxv.z)}; int b=0; for(int k=1;k<6;k++)if(d[k]<d[b])b=k; if(d[b]>tol)bad++; else c[b]++;} int tot=bad; for(int x:c)tot+=x; if(tot<20||bad*250>tot)return false; for(int k=0;k<6;k++) if(c[k]<max(1,tot/3000)) return false; double h=epsv*1.38; int nx=max(1,(int)ceil(lx/h)),ny=max(1,(int)ceil(ly/h)),nz=max(1,(int)ceil(lz/h)); unordered_map<unsigned long long,int> mp; v.clear(); f.clear(); auto pos=[&](int i,int j,int k){return P{mnv.x+lx*i/nx,mnv.y+ly*j/ny,mnv.z+lz*k/nz};}; auto get=[&](int i,int j,int k){unsigned long long key=((unsigned long long)i<<42)^((unsigned long long)j<<21)^(unsigned)k; auto it=mp.find(key); if(it!=mp.end())return it->second; int id=v.size(); mp[key]=id; v.push_back(pos(i,j,k)); return id;}; auto q=[&](int a,int b,int c,int d){f.push_back({a,b,c}); f.push_back({a,c,d});}; for(int i=0;i<nx;i++)for(int j=0;j<ny;j++){q(get(i,j,0),get(i+1,j,0),get(i+1,j+1,0),get(i,j+1,0)); q(get(i,j,nz),get(i,j+1,nz),get(i+1,j+1,nz),get(i+1,j,nz));} for(int i=0;i<nx;i++)for(int k=0;k<nz;k++){q(get(i,0,k),get(i,0,k+1),get(i+1,0,k+1),get(i+1,0,k)); q(get(i,ny,k),get(i+1,ny,k),get(i+1,ny,k+1),get(i,ny,k+1));} for(int j=0;j<ny;j++)for(int k=0;k<nz;k++){q(get(0,j,k),get(0,j+1,k),get(0,j+1,k+1),get(0,j,k+1)); q(get(nx,j,k),get(nx,j,k+1),get(nx,j+1,k+1),get(nx,j+1,k));} orient(v,f); return v.size()<V0.size()*.9&&valid(v,f)&&hd(v,epsv*.995);} 
struct GI{int H,W,dg,ori; double good;};
vector<int> candWidths(){unordered_map<int,int> cnt; int st=max(1,M/50000); for(int i=0;i<M;i+=st){int a[3]={F0[i].a,F0[i].b,F0[i].c}; for(int u=0;u<3;u++){int d=abs(a[u]-a[(u+1)%3]); for(int q=-1;q<=1;q++){int w=d+q; if(w>=4&&w<=N/4&&N%w==0)cnt[w]++;}}} vector<pair<int,int>> p; for(auto&x:cnt)p.push_back({-x.second,x.first}); sort(p.begin(),p.end()); vector<int> r; for(int i=0;i<(int)p.size()&&i<24;i++)r.push_back(p[i].second); for(int w:divs(N)) if(w>=8&&N/w>=8&&((int)r.size()<40)) r.push_back(w); sort(r.begin(),r.end()); r.erase(unique(r.begin(),r.end()),r.end()); return r;}
bool checkTorus(int W,GI&g,bool full){if(W<4||N%W||M!=2*N)return false; int H=N/W; if(H<4)return false; int step=full?1:max(1,N/1500),tot=0,good[2]={0,0},sg[2]={0,0}; auto id=[&](int i,int j){return ((i+H)%H)*W+((j+W)%W);}; for(int cell=0;cell<N;cell+=step){int i=cell/W,j=cell-i*W,fi=2*cell; if(fi+1>=M)break; int a=id(i,j),b=id(i,j+1),c=id(i+1,j),d=id(i+1,j+1); T f0=F0[fi],f1=F0[fi+1]; bool ok0=same(f0,a,b,c)&&same(f1,b,d,c), ok1=same(f0,a,b,d)&&same(f1,a,d,c); if(ok0){good[0]++; P cr0=cross(V0[b]-V0[a],V0[c]-V0[a]); P cr1=cross(V0[f0.b]-V0[f0.a],V0[f0.c]-V0[f0.a]); sg[0]+=dot(cr0,cr1)>=0?1:-1;} if(ok1){good[1]++; P cr0=cross(V0[b]-V0[a],V0[d]-V0[a]); P cr1=cross(V0[f0.b]-V0[f0.a],V0[f0.c]-V0[f0.a]); sg[1]+=dot(cr0,cr1)>=0?1:-1;} tot++;} int dg=good[1]>good[0]; if(tot<20||good[dg]*1000<tot*(full?998:985))return false; g={H,W,dg,sg[dg]>=0?1:-1,(double)good[dg]/tot}; return true;}
vector<int> pick(int n,int k){k=max(3,min(k,n)); vector<int>a(k); for(int i=0;i<k;i++)a[i]=(long long)i*n/k; sort(a.begin(),a.end()); a.erase(unique(a.begin(),a.end()),a.end()); return a;}
int near1(const vector<int>&a,int x,int mod,int out[2]){int k=lower_bound(a.begin(),a.end(),x)-a.begin(); vector<int> c; for(int d=-1;d<=1;d++){int j=k+d; if(j>=0&&j<(int)a.size())c.push_back(j);} c.push_back(0); c.push_back((int)a.size()-1); sort(c.begin(),c.end()); c.erase(unique(c.begin(),c.end()),c.end()); vector<pair<int,int>> b; for(int j:c){int d=abs(a[j]-x); d=min(d,mod-d); b.push_back({d,j});} sort(b.begin(),b.end()); int m=min(2,(int)b.size()); for(int i=0;i<m;i++)out[i]=b[i].second; return m;}
bool coverTorus(const GI&g,const vector<int>&rs,const vector<int>&cs){double e=epsv*.992; e*=e; int ri[2],ci[2]; for(int q=0;q<N;q++){int r=q/g.W,c=q-r*g.W,nr=near1(rs,r,g.H,ri),nc=near1(cs,c,g.W,ci); double best=1e300; for(int a=0;a<nr;a++)for(int b=0;b<nc;b++){int id=rs[ri[a]]*g.W+cs[ci[b]]; best=min(best,n2(V0[q]-V0[id]));} if(best>e)return false;} return true;}
bool buildTorus(const GI&g,int rh,int cw,vector<P>&v,vector<T>&f){auto rs=pick(g.H,rh),cs=pick(g.W,cw); if(!coverTorus(g,rs,cs))return false; int H=rs.size(),W=cs.size(); v.clear(); f.clear(); for(int r:rs)for(int c:cs)v.push_back(V0[r*g.W+c]); auto id=[&](int i,int j){return ((i+H)%H)*W+((j+W)%W);}; auto add=[&](int a,int b,int c){if(g.ori>0)f.push_back({a,b,c}); else f.push_back({a,c,b});}; for(int i=0;i<H;i++)for(int j=0;j<W;j++){int a=id(i,j),b=id(i,j+1),c=id(i+1,j),d=id(i+1,j+1); if(!g.dg){add(a,b,c); add(b,d,c);} else {add(a,b,d); add(a,d,c);}} return v.size()<V0.size()&&valid(v,f);}
bool indexedTorus(vector<P>&v,vector<T>&f){if(N<1000||M!=2*N||sec()>7)return false; vector<GI> gs; for(int W:candWidths()){GI g; if(checkTorus(W,g,false)){GI h; if(checkTorus(W,h,true))gs.push_back(h);} if(sec()>6&&gs.empty())break;} if(gs.empty())return false; sort(gs.begin(),gs.end(),[](const GI&a,const GI&b){return a.good>b.good;}); vector<int>C={8,10,12,14,16,18,20,24,28,32,40,48,56,64,80,96,128,160,200,240,320}; for(auto&g:gs){vector<pair<int,pair<int,int>>> cand; for(int a:C)for(int b:C)if(a<=g.H&&b<=g.W)cand.push_back({a*b,{a,b}}); sort(cand.begin(),cand.end()); for(auto&pp:cand){vector<P>x; vector<T>y; if(buildTorus(g,pp.second.first,pp.second.second,x,y)&&hd(x,epsv*.992)){v.swap(x); f.swap(y); return true;} if(sec()>15)break;} if(sec()>15)break;} return false;}
bool sphereGrid(vector<P>&v,vector<T>&f){if(N<1000||sec()>8)return false; int X=N-2; if(X<=0)return false; for(int W:divs(X)){int H=X/W+1; if(W<12||H<8||W>1000||H>1000||M!=2*W*(H-1))continue; auto id=[&](int r,int c){return 1+(r-1)*W+((c%W+W)%W);}; int st=max(1,W/60),good=0,tot=0; for(int j=0;j<W;j+=st){if(same(F0[j],0,id(1,j+1),id(1,j)))good++; tot++;} if(tot<4||good*100<tot*90)continue; vector<int>C={8,10,12,14,16,18,20,24,28,32,40,48,64,80,96}; for(int hh:C)for(int ww:C){if(hh>=H||ww>W)continue; vector<int> rs; rs.push_back(0); for(int r=1;r<hh;r++)rs.push_back((long long)r*H/hh); rs.push_back(H); vector<int> cs=pick(W,ww); v.clear(); f.clear(); v.push_back(V0[0]); v.push_back(V0[N-1]); auto vid=[&](int ri,int cj){if(ri==0)return 0; if(ri==(int)rs.size()-1)return 1; return (int)(2+(ri-1)*cs.size()+cj);}; for(int ri=1;ri+1<(int)rs.size();ri++)for(int c:cs)v.push_back(V0[id(rs[ri],c)]); for(int j=0;j<(int)cs.size();j++)f.push_back({0,vid(1,(j+1)%cs.size()),vid(1,j)}); for(int r=1;r+2<(int)rs.size();r++)for(int j=0;j<(int)cs.size();j++){int a=vid(r,j),b=vid(r,(j+1)%cs.size()),c=vid(r+1,j),d=vid(r+1,(j+1)%cs.size()); f.push_back({a,b,c}); f.push_back({b,d,c});} int lr=rs.size()-2; for(int j=0;j<(int)cs.size();j++)f.push_back({1,vid(lr,j),vid(lr,(j+1)%cs.size())}); orient(v,f); if(valid(v,f)&&hd(v,epsv*.99)&&v.size()<V0.size()*.85)return true;}} return false;}
struct Cell{int x,y,z; bool operator==(const Cell&o)const{return x==o.x&&y==o.y&&z==o.z;}}; struct CH{size_t operator()(const Cell&k)const{return (uint32_t)k.x*11995408973635179863ull^(uint32_t)k.y*10150724397891781847ull^(uint32_t)k.z*780291637ull;}};
bool quant(double q,vector<P>&v,vector<T>&f){unordered_map<Cell,int,CH> mp; mp.reserve(N*2); vector<int> rm(N); for(int i=0;i<N;i++){auto&p=V0[i]; Cell k{(int)floor((p.x-mnv.x)/q),(int)floor((p.y-mnv.y)/q),(int)floor((p.z-mnv.z)/q)}; auto it=mp.find(k); if(it==mp.end()){int id=v.size(); mp[k]=id; v.push_back(p); rm[i]=id;} else rm[i]=it->second;} if(v.size()<4||v.size()>=V0.size()*.96)return false; set<array<int,3>> seen; for(auto&o:F0){int a=rm[o.a],b=rm[o.b],c=rm[o.c]; if(a==b||a==c||b==c)continue; array<int,3>s={a,b,c}; sort(s.begin(),s.end()); if(seen.insert(s).second)f.push_back({a,b,c});} compact(v,f); orient(v,f); return valid(v,f)&&hd(v,epsv*.99);}
void out(const vector<P>&v,const vector<T>&f){cout<<v.size()<<" "<<f.size()<<"\n"<<fixed<<setprecision(10); for(auto&p:v)cout<<"v "<<p.x<<" "<<p.y<<" "<<p.z<<"\n"; for(auto&q:f)cout<<"f "<<q.a+1<<" "<<q.b+1<<" "<<q.c+1<<"\n";}
int main(){startTime=chrono::steady_clock::now(); read(); vector<P> best=V0,x; vector<T> bf=F0,y; if(exactBox(x,y)){out(x,y);return 0;} if(aabbGrid(x,y)){out(x,y);return 0;} if(indexedTorus(x,y)){out(x,y);return 0;} if(sphereGrid(x,y)){out(x,y);return 0;} double qs[]={.55,.45,.35,.27}; for(double k:qs){if(sec()>17)break; x.clear(); y.clear(); if(quant(epsv*k,x,y)&&x.size()<best.size()){best=x; bf=y; break;}} if(!valid(best,bf)){best=V0; bf=F0;} out(best,bf);}
